WAN/Wi-Fi Bytes, Errors, Discards
anlix-io/flashman pull request #1002
Opened 2023-12-28 15:46 UTC by lucasperovani

2023-12-29 21:43 UTC, GThurler requested changes
Review preliminar sem testar na minha máquina - vou fazer isso agora e volto aqui pra contar como foi, rs

2023-12-29 21:43 UTC, GThurler commented on public/javascripts/widgets/html.js
> + * @param {boolean} end - If the element should be closed.
Deixo mais uma vez meu desejo de não ter uma classe dessas, por ser abstração demais para os nossos casos - muito boilerplate pra pouco benefício. Mas se for usar, no mínimo tem que dar os nomes certos aos bois:
```suggestion
 * @param {string} tagName - The type of the HTML element.
 * @param {string} id - The ID of the HTML element.
 * @param {array<string>} classes - The classes of the HTML element.
 * @param {string} innerHTML - The content of the HTML element.
 * @param {object} attributes - The extra content of the element, that the key is the
 * data or another structure and the value.
 * @param {boolean} tagNeedsClosing - If the element should be closed.
```

2023-12-29 21:43 UTC, GThurler commented on controllers/device_info.js
> +
`device_info` é firmware, está 100% certo que vai querer inserir essa lógica aqui???

2023-12-29 21:46 UTC, lucasperovani commented on controllers/handlers/acs/bytes.js
> +  }
Isso! Pelo que eu lembre eu não alterei nada significativo nessa função não, eu acho haha

2023-12-29 21:47 UTC, lucasperovani commented on controllers/device_info.js
> +
Copy paste kkkkk vou retirar

2023-12-29 22:01 UTC, lucasperovani commented on controllers/handlers/acs/bytes.js
> +  }
Desculpa, mudei os `debug` para `console.debug` e `console.error`

2023-12-29 22:02 UTC, GThurler requested changes
EG8145V5 não me deu a opção de trocar de WAN para Wi-Fi
![image](https://github.com/anlix-io/flashman/assets/37554452/6def8f12-56b6-4353-97a2-24d467ea3b81)

F670 v9 não me mostrou nem o gráfico da WAN
![image](https://github.com/anlix-io/flashman/assets/37554452/84397abf-5094-4673-b883-ac0bf415bcec)

AX2S não me mostrou nenhum dado
![image](https://github.com/anlix-io/flashman/assets/37554452/d0e0b1da-eabc-4c28-9027-5ffb1ed4d30c)

2023-12-29 22:03 UTC, GThurler commented on controllers/handlers/acs/bytes.js
> +  }
Se foi só isso tá de boa :+1:

2024-01-02 22:24 UTC, rilpires reviewed
Consertei vários problemas que tinha:
- Não se lia wan_bytes que viessem string (caso do F6600)
- Nada no handlers/acs/wifi funcionava, pois tinha uma linha: `const bytes = require('../utils.js')`
- Além disso, o erro anterior só não explodia pq nenhuma CPE tinha uma permission que não tava nem no base-model (features.wifiBytes).

E depois de consertar tudo isso, os testes passaram a quebrar pro Wi-Fi. Passava antes pq eles estavam errados mesmo

2024-01-05 00:21 UTC, GThurler approved these changes

2024-01-05 21:35 UTC, merged