Feature/vlan
anlix-io/flashman pull request #113
Opened 2021-03-17 23:37 UTC by W1N3

📋 Lista de modificações: ✔️
- Criação, edição e remoção de Perfis de VLAN
- Opção de Administrar VLAN de um dispositivo no menu de Opções
- Modal para configurar a VLAN de um dispositivo
- Menu de Opções do dispositivo dividido e balanceado em duas partes
- Permissão do usuário referentes a edição de Perfis de VLAN e a informações de VLANs do dispositivo
- Dependência da biblioteca asyncawait removida
- Testes unitários no controle da VLAN

📋 Ainda falta: 🔧
- Completar os testes unitários
- Visto que está em andamento a implementação do flashman-openwrt-plugin:
- 1. Homologar integração com o flashbox
- 2. Possíveis modificações na função retrieveVlansToDevice

2021-03-31 19:05 UTC, W1N3 commented on controllers/acs_device_info.js
> +        interfaces.forEach((iface)=>{
Changed the 'interface' variable name to 'iface' because jest pointed as an error: reserved word. However, is a future reserved word as pointed in [this](https://stackoverflow.com/a/29600585/11803523) answer.

2021-04-07 02:11 UTC, guissenges requested changes

2021-04-07 02:11 UTC, guissenges commented on public/javascripts/showvlanprofiles_actions.js
> +    input.setCustomValidity('O VLAN ID não pode ser menor que 10 ou maior que 127.');
Já fiz essa obs. antes. Precisa dessas limitações de mínimo e máximo? @W1N3  e @danielatk

2021-04-07 02:11 UTC, guissenges commented on views/showvlanprofiles.pug
> +              .invalid-feedback O VLAN ID deve ser distinto, não pode ser menor que 10 ou maior que 127
Mesmos comentários de antes

2021-04-07 02:22 UTC, ggbruno commented on models/config.js
> +    vlan_id: {type: Number, required: true, min: 1, max: 128},
Por definição, o 802.1q vai até 4095 e o 802.1aq pode chegar a 16M ... O aq ainda é pouco usado... Concordo com o Guilherme... Ou tira, ou pelo menos sobe para 4095

2021-04-07 02:51 UTC, GThurler commented on controllers/device_list.js
>  const downloadStockFirmware = function(model) {
É o correto mesmo, não sei porque na época fiz(emos?) assim. A gente nem usa o reject, dá pra colocar a função inteira como async e nem vai precisar trocar a maneira como chamamos essa função

2021-04-07 02:56 UTC, GThurler commented on controllers/update_scheduler.js
> +  watchdogIntervalID = setInterval(async () => markSeveral(), interval);
A real é que nem precisa marcar essa função como async, pelo que vi. O que essa linha faz é chamar markSeveral() a cada interval milissegundos, tendo um await ali não vai alterar nada por ser a única instrução dessa função dentro do setInterval

2021-04-07 03:09 UTC, GThurler commented on controllers/update_scheduler.js
>        meshHandler.propagateUpdate(slave, rule.release);
Não precisa, nós não precisamos esperar o flashman enviar o update para o slave para continuar a execução, que nesse caso é só um return mesmo

2021-04-07 03:15 UTC, GThurler commented on controllers/update_scheduler.js
> +        return new Promise(async (resolve)=>{
Pode ser, o motivo de usar promises aqui é só pra poder usar o Promise.all ali embaixo. Tem que ver qual a sintaxe certinha para usar um map com async/await e garantir que todas as funções async concluíram antes de dar sequência na execução. Talvez ajude: https://stackoverflow.com/questions/40140149/use-async-await-with-array-map

2021-04-07 03:17 UTC, GThurler commented on controllers/update_scheduler.js
> +          return new Promise(async (resolve) => {
Só apontando que tem o mesmo lance de map com async/await aqui, pra tirar essa Promise junto do async/await vai cair na mesma solução para o trecho de código logo acima

2021-04-07 03:26 UTC, GThurler commented on controllers/vlan.js
> +        config.vlans_profiles[i].profile_name = req.body.profilename;
Senti falta da validação desse campo antes de sair encaixando ele na base assim. No add vocês verificam se ele é único dentre os perfis existentes e se tem menos de 32 caracteres, aqui vocês já colocam direto.

2021-04-07 03:36 UTC, GThurler commented on controllers/vlan.js
> +    for(i = 0; i < req.body.ids.length ; i++) {
Não é que não funcione do jeito que está feito, mas esse for inteiro aqui pode ser substituído por um filter. Tendo o seu array atual e um array de ids pra deletar, poderia ser algo assim:

```
let current = [{id: 1},{id: 2},{id: 3}];
let toDelete = [2, 3];
current = current.filter((obj)=>!toDelete.includes(obj.id));
```

2021-04-07 03:50 UTC, GThurler commented on controllers/vlan.js
> +    device.vlan = JSON.parse(req.body.vlans);
Senti falta de uma validação desse campo aqui também, tem até um comentário falando que precisa de validação :)
Alguém mal intencionado pode forjar uma requisição do frontend e colocar o json que ele quiser na nossa base de dados, sem validação nenhuma. Inclusive pode gerar crashes na base já que não necessariamente esse json está seguindo o schema definido no models/device

2021-04-07 03:58 UTC, GThurler commented on public/javascripts/show_vlan_actions.js
> +};
Newline no final do arquivo, cadê o linter? :)

2021-04-07 04:06 UTC, GThurler commented on scss/custom-bootstrap.scss
> +}
Newline de novo

2021-04-07 04:07 UTC, GThurler commented on views/vlanprofile.pug
> +  script(src='/javascripts/vlanprofile_actions.js')
Newline

2021-04-07 12:10 UTC, W1N3 commented on controllers/user.js
> +    idList.forEach(async (userId) => {
A versão mais nova já troquei para "for of"

2021-04-07 12:19 UTC, W1N3 commented on controllers/vlan.js
> +  if (newVlanProfile.vlan_id != 1 && (newVlanProfile.vlan_id < 10 || newVlanProfile.vlan_id > 127)) {
A limitação de abaixo de 10 é por conta do realtek ter as vlan's padrão 8 e 9 para wan e lan, respectivamente

2021-04-07 12:23 UTC, guissenges commented on controllers/vlan.js
> +  if (newVlanProfile.vlan_id != 1 && (newVlanProfile.vlan_id < 10 || newVlanProfile.vlan_id > 127)) {
Deixa só um comentário pra essa limitação então no código... Eu colocaria uma restrição somente pra esses valores. É possível que provedores usem as VLANs 1, 2, 3 etc. na rede deles e essa limitação gere um conflito

2021-04-07 18:34 UTC, GThurler requested changes

2021-04-07 18:34 UTC, GThurler commented on controllers/device_list.js
> +        return false;
Eu acho que essa alteração me fez lembrar do porquê usamos uma Promise nessa função... Esse return false aqui NÃO vai retornar false para quem chamou essa função, vai retornar false pra essa callback do .on('error'), e vai deixar quem chamou a downloadStockFirmware com retorno undefined. Essa parte de event handling meio que precisa usar promises, não tem muito jeito, até onde sei.

Isso vale para todos os retornos desta função que estão dentro desses event handlers.

2021-04-07 18:34 UTC, GThurler commented on controllers/vlan.js
> +          config.vlans_profiles[i].profile_name = req.body.profilename;
Ainda faltou validar se o novo nome é único dentre os já existentes, não?

2021-04-07 20:21 UTC, GThurler requested changes

2021-04-07 20:21 UTC, GThurler commented on controllers/vlan.js
> +        } else if (config.vlans_profiles[i].profile_name === req.body.profile_name) {
Com a nova alteração você só vê se o novo é igual ao anterior, e ainda tem como inserir um nome igual ao nome associado a outro perfil. Exemplo:
> Criar perfil 1 com nome "asd"
> Criar perfil 2 com nome "qwe"
> Editar nome do perfil 2 para nome "asd"
> Espera-se que a alteração falhe, do jeito que está ela vai passar

2021-04-07 21:43 UTC, W1N3 commented on controllers/vlan.js
> +        } else if (config.vlans_profiles[i].profile_name === req.body.profile_name) {
Bem observado. Não cheguei a escrever um caso de teste que envolva isso.

2021-04-07 23:23 UTC, guissenges approved these changes

2021-04-08 00:03 UTC, GThurler commented on controllers/vlan.js
> +      }
Última besteirinha, prometo. Essa etapa da validação não faz sentido estar dentro do if, independe do que você está iterando. Como isso aqui vai ser executado só de vez em nunca é meio whatever, mas já que já vai ter o commit pra ajeitar os outros dois awaits que ficaram faltando no outro arquivo lá... :)

2021-04-11 23:04 UTC, merged