Feature/coleta da intensidade do sinal da fibra
anlix-io/flashman pull request #117
Opened 2021-05-05 19:25 UTC by JotaPe

2021-05-06 18:46 UTC, JotaPe commented
Preparado para dar merge.

2021-05-07 17:39 UTC, GThurler reviewed
Além dos comentários feitos, era bom ter a permissão de usuário separada da permissão de bytes trafegados na WAN

2021-05-07 17:39 UTC, GThurler commented on controllers/acs_device_info.js
> +  let isAC1 = convertWifiMode(mode) === '11ac';
Typo?

2021-05-07 17:39 UTC, GThurler commented on controllers/acs_device_info.js
> +  if (Object.keys(dbms).length >= 100) {
Vamos deixar só 100 amostras mesmo? Não dá nem 2 horas de dados com os parâmetros default de intervalo de inform

2021-05-07 17:39 UTC, GThurler commented on controllers/acs_device_info.js
> +
Whitespace

2021-05-07 17:39 UTC, GThurler commented on controllers/device_list.js
> -        } else {
Algum motivo pra apagar esse else?

2021-05-07 17:39 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +      pon_status: 'InternetGatewayDevice.WANDevice.1.WANGponInterfaceConfig.Status',
Eu tiraria isso aqui do default - todo mundo usa um campo proprietário e se deixar ele aqui os roteadores vão tentar coletar uma informação que não existe

2021-05-07 17:39 UTC, GThurler commented on package-lock.json
> -  "packages": {
@guissenges A gente chegou a resolver essa história do package-lock.json? Esse negócio da versão do npm tá gerando uns diffs muito loucos

2021-05-07 17:39 UTC, GThurler commented on public/javascripts/table_anim.js
> +          .replace('$REPLACE_ICON', 'fa-chart-line')
Vamos usar o mesmo ícone que usamos pros bytes da WAN mesmo? Até faz sentido por abrir um gráfico igualzinho, mas sei lá @guissenges

2021-05-07 17:39 UTC, GThurler commented on public/javascripts/table_anim.js
> +                  '<label class="active">Intesidade do sinal optico (RXPower/Recebido)</label>'+
óptico

2021-05-07 17:50 UTC, guissenges commented on public/javascripts/table_anim.js
> +          .replace('$REPLACE_ICON', 'fa-chart-line')
É legal tentar diferenciar sempre. Acho que fica legal esse aqui: fa-wave-square

2021-05-07 17:55 UTC, guissenges commented on views/includes/showponsignalmeasure.pug
> +          strong &nbsp; Sinal ONU de&nbsp;
Intensidade de Sinal Óptico . Podemos padronizar assim... Assim tem sempre uma mesma redação nos outros trechos

2021-05-07 18:02 UTC, JotaPe commented on controllers/acs_device_info.js
> +  let isAC1 = convertWifiMode(mode) === '11ac';
Tambem não sei pq está assim, já que eu não mexi nisso.

2021-05-07 18:03 UTC, JotaPe commented on controllers/acs_device_info.js
> +  if (Object.keys(dbms).length >= 100) {
Poderia aumentar, só que eu não sei se consumiria muito espaço.

2021-05-07 18:04 UTC, JotaPe commented on controllers/device_list.js
> -        } else {
Não, foi erro meso.

2021-05-07 18:04 UTC, JotaPe commented on controllers/external-genieacs/devices-api.js
> +      pon_status: 'InternetGatewayDevice.WANDevice.1.WANGponInterfaceConfig.Status',
Blz, irei retirar.

2021-05-07 21:44 UTC, GThurler requested changes

2021-05-07 21:44 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +      pon_txpower: 'InternetGatewayDevice.WANDevice.1.WANGponInterfaceConfig.TXPower'
Eu devo ter esquecido de dar highlight de várias linhas no outro review, mas a ideia era tirar o rx e tx do getDefaultFields - nem todo dispositivo TR-069 vai coletar isso, e bem ou mal quem coleta não usa esse valor default

2021-05-07 22:31 UTC, merged