Feature/port forward onu
anlix-io/flashman pull request #123
Opened 2021-05-25 15:53 UTC by W1N3

📋 Lista de modificações: ✔️
- Abertura de portas para dispositivos TR-069
- Nova interface de Abertura de Portas que poderá futuramente ser portada para dispositivos não TR-069
- Sincronização das regras salvas no Flashman para o dispositivo via Genie

📋 Lista de dispositivos e suas compatibilidades 💻 

Marca | Modelo | Implementado
------------ | ------------- | -------------
Multilaser ZTE | RE914 H198A | ✔️ 
Multilaser ZTE | RE907 F670L | ✔️ 
Nokia | G-140W-C | ❌ 
Greatek (Stavix) |  G421RQ | ❌
Huawei | HG8245Q2 | ❌
Fiberhome | HG6245D | ❌

2021-05-25 18:45 UTC, GThurler requested changes

2021-05-25 18:45 UTC, GThurler commented on controllers/device_list.js
> +deviceListController.checkCompatibility = function(rules, compatibility) {
Achei esse nome meio genérico pro que a função faz. `validatePortForward` não faz mais sentido não? Outra, pelo que entendi essa função está verificando se alguma regra NÃO é compatível, por exemplo se existe uma abertura de range assimétrico e o device não é compatível com esse tipo. Seria mais intuitivo colocar como nome então `checkIncompatiblity`, e também dar uma documentada no que a função faz, que de cara assim não parece óbvio.

2021-05-25 18:45 UTC, GThurler commented on controllers/device_list.js
> +    }
Esse `compatibility[i]` sem um coomentário do que está sendo validado deixa o código meio críptico... Eu preferiria que esse compatibility fosse um objeto, não um array, que daí deixaria mais claro o que cada coisa tá validando. Ex:
`compatibility.singleSymmetric` ou `compatibility.rangeAsymmetric` ao invés de `compatiblity[0]` e derivados
A alternativa é deixar um comentário explicando o que cada if tá fazendo. Outra alternativa é trocar essas variáveis por algo mais legível, como já comentei anteriormente.

2021-05-25 18:45 UTC, GThurler commented on controllers/device_list.js
> +    if (matchedDevice.use_tr069) {
Essa função dobrou de tamanho com a inserção da lógica do TR-069, acho que ficaria muito mais organizado se separasse o conteúdo desse if aqui numa outra função - `setPortForwardRange` ou algo assim. Quando/Se colocarmos isso para os roteadores Flashbox também, seria só redirecionar pra essa outra função.

2021-05-25 18:45 UTC, GThurler commented on controllers/device_list.js
> +             r.internal_port_end != undefined;
Recomendo trocar a comparação com undefined por uma validação mais completa, nem que seja só usar `!r.ip`, que já cobre os casos `false`, `0`, `null`, `undefined`, e `""`.

2021-05-25 18:45 UTC, GThurler commented on controllers/device_list.js
> +          portsValues[3] = rules[i].internal_port_end;
Mesmo lance que já comentei de *readability*, usar um nome mais descritivo ao invés de tacar num array

2021-05-25 18:45 UTC, GThurler commented on controllers/device_list.js
> +            }
Dúvida pro @ggbruno , não sei se a gente já leva isso em conta pro Flashbox: não dá problema redirecionar a 22 por conta do SSH? Ou a porta do MQTT, também?

2021-05-25 18:45 UTC, GThurler commented on controllers/device_list.js
> +          }
Esses checks não deveriam vir depois do `if (!isPortsNumber)` ? Não faz sentido comparar isso se alguma porta não é um número.

2021-05-25 18:45 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +      fields.port_mapping.external_port_end = 'ExternalPortEndRange';
Como é o mesmo do H198A, você pode colocar fora da switch ao invés de colocar nos dois cases

2021-05-25 18:45 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +    case 'ZXHN%20H198A%20V3%2E0':
Importante incluir o `case 'ZXHN H198A V3.0'` também, ele pode vir tanto dessa forma quanto URI encoded

2021-05-25 18:45 UTC, GThurler commented on public/javascripts/port_forward_onu.js
> +let showCompatibilityMessage = function(compatibility) {
`showIncompatibilityMessage` ficaria melhor? Mesmo lance que comentei no backend

2021-05-25 18:45 UTC, GThurler commented on public/javascripts/port_forward_onu.js
> +let checkAddressSubnetRange = function(deviceIp, ipAddressGiven, maskBits) {
Esse código é exatamente o mesmo do backend, certo? Mais um motivo pra colocar num utils e possivelmente aproveitar o código no backend. Nós já fazemos algo parecido com a validação do cadastro do roteador, aproveitamos o mesmo código no frontend e no backend

2021-05-25 18:45 UTC, GThurler commented on public/javascripts/port_forward_onu.js
> +        isPortsOnRange = false;
Mesmo comentário que fiz antes sobre talvez abrir a 22 ou a porta do MQTT

2021-05-25 18:45 UTC, GThurler commented on public/javascripts/port_forward_onu.js
> +  }
Mesmo comentário que fiz sobre isso aqui não fazer sentido se alguma porta for NaN

2021-05-25 18:45 UTC, GThurler commented on public/javascripts/port_forward_onu.js
> +      triggerRedAlert('Algo muito errado aconteceu...');
Isso aqui vai assustar o usuário, hehehe. Recomendo colocar "Um erro inesperado aconteceu" ou similar

2021-05-25 19:08 UTC, W1N3 commented on controllers/acs_device_info.js
> +  }) !== undefined) ? true : false;
Tinha feito com every e ficou meio confuso. Não sabia do some, vou usar ele no lugar.

2021-05-25 22:40 UTC, W1N3 commented on controllers/acs_device_info.js
> +    replace('*', '1').replace('*', '2');
Vou deixar desse jeito por conta do ambiente de teste. Essa parte só pega informações do genie. É tratado qual dos índices, 1 ou 2, na hora de iterar a árvore.

2021-05-25 22:42 UTC, W1N3 commented on controllers/device_list.js
> +          portsValues[3] = rules[i].internal_port_end;
Aqui faz sentido ser um array pois logo em seguida esse array iterado para validação

2021-05-25 22:53 UTC, GThurler commented on controllers/device_list.js
> +          portsValues[3] = rules[i].internal_port_end;
Nada impede de fazer algo tipo `[foo, bar, qwe, asd].forEach((port)=>{});` na validação, mas nesse trecho é mais tranquilo de acompanhar mesmo

2021-05-31 17:01 UTC, GThurler approved these changes

2021-06-01 04:24 UTC, guissenges reviewed
Aprovado. Um pequeno comentário extra: Renomear alguns arquivos para evitar o termo ONU e passar para TR-069

2021-06-01 04:24 UTC, merged