Feature/ssid prefix by provider
anlix-io/flashman pull request #130
Opened 2021-06-18 21:23 UTC by W1N3

2021-06-21 17:39 UTC, guissenges commented on controllers/device_info.js
> +          genericValidate(ssidPrefix+util.
Essa validação extra é para verificar o tamanho do SSID junto ao prefixo?

2021-06-21 17:39 UTC, guissenges commented on controllers/device_list.js
> +              'isSsidPrefixEnabled': true, // for new devices, default is true
Creio que aqui seja necessário verificar o que está configurado em Config. Senão há condicionais que vão avaliar como 'true' mesmo se em Config o prefixo estiver desativado.

2021-06-21 17:39 UTC, guissenges commented on controllers/update_flashman.js
> +    config.ssidPrefix = req.body['ssid-prefix']; // validate!
Comentário 'validate' é um To Do?

2021-06-21 17:39 UTC, guissenges commented on models/device.js
> +  isSsidPrefixEnabled: {type: Boolean, default: false},
Revisar: O valor default não será incluído em registros pré-existentes e nem quando a função lean() for usada junto com um 'find' na base. Repassar para ter certeza que não há nenhum caso sobrando

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/edit_device.js
> +      sessionStorage.getItem('isSsidPrefixEnabled') == 'true' &&
Devemos nos preocupar com o cache do session storage ser diferente de valores salvos no backend?

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/new_device.js
> +      sessionStorage.getItem('isSsidPrefixEnabled') == 'true') {
Mesmo comentário sobre session storage em relação ao edit_device

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/settings_actions.js
> +import Validator from './device_validator.js';
Isso foi usado?

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/settings_actions.js
> +window.checkSsidPrefixValidity = function() {
Acho que vale a pena concetrar esse tipo de validação no Validator e aproveitar as mesmas validações de caracteres do SSID. O que acha? A idéia é evitar diferentes regras de validação para campos muito similares

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/table_anim.js
> +                              '<option value="11" $REPLACE_SELECTED_CHANNEL_11$>11</option>'+
Problema no auto merge aqui: Não inclui a lógica dos canais 12 e 13 extendidos e recentemente adicionados. Revisar esse merge

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/table_anim.js
> +            wifiTab = wifiTab.replace('$AUTO_CHANNEL_SELECTED_VISIBILITY5',
Farei testes práticos para validar essa parte

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/table_anim.js
> +          /*
Não deixar código comentado se for obsoleto

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/table_anim.js
> +                      // '$REPLACE_WIFI5GHZ_EDIT'+
Não deixar código comentado se for obsoleto

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/table_anim.js
> +                    // wifi5Tab+
Código comentado

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/table_anim.js
> +            /*
Código comentado

2021-06-21 17:39 UTC, guissenges commented on public/javascripts/table_anim.js
> +            // formRow = formRow.replace('$REPLACE_WIFI5GHZ_EDIT', '');
Código comentado

2021-06-22 16:44 UTC, GThurler requested changes

2021-06-22 16:44 UTC, GThurler commented on controllers/device_list.js
> +                    device.isSsidPrefixEnabled == true);
Deixa um comentário aqui com o que você tá validando - vai ajudar imensamente quem tiver que ler esse código no futuro. Se fosse uma cadeia de AND ou OR beleza, mas quando começa a misturar a lógica assim eu particularmente acho mais fácil de entender se tiver um textinho explicando o que e como tá sendo validado

2021-06-22 16:44 UTC, GThurler commented on controllers/device_list.js
> +                  config: matchedConfig,
MUITO CUIDADO ao expor o matchedConfig inteiro na resposta de uma request - tem muitas informações sensíveis nessa estrutura, que serão expostas para TODOS que fizerem QUALQUER busca no Flashman.

2021-06-22 16:44 UTC, GThurler commented on controllers/device_list.js
> +            validator.validateSSID, 'ssid');
Não era pra você levar em consideração o isSsidPrefixEnabled também? Do jeito que está a única coisa que importa é o valor global

2021-06-22 16:44 UTC, GThurler commented on controllers/device_list.js
> +            validator.validateSSID, 'ssid5ghz');
Mesmo comentário acima só que pro 5GHz

2021-06-22 16:44 UTC, GThurler commented on controllers/device_list.js
> +                ssidPrefix+ssid !== ssidPrefix+matchedDevice.wifi_ssid) {
Não entendi a necessidade de adicionar o prefixo nessa validação - você adiciona ele dos dois lados comparados, o resultado não vai se alterar se você adicionar/remover o prefixo do if

2021-06-22 16:44 UTC, GThurler commented on controllers/device_list.js
> +                ssidPrefix+ssid5ghz !== ssidPrefix+matchedDevice.wifi_ssid_5ghz) {
Mesmo comentário acima só que pro 5GHz

2021-06-22 16:44 UTC, GThurler commented on controllers/device_list.js
> +                await acsDeviceInfo.updateInfo(matchedDevice, changes);
Importante tirar esse await daqui - já mencionei o porquê em outros trechos do código

2021-06-22 16:44 UTC, GThurler commented on controllers/update_flashman.js
> +    if (isDeviceSsidPrefixEnabled == true) {
É besteira nesse caso, mas só pra alertar: (variável == true) é um código muito traiçoeiro em JavaScript. Depois dá uma olhada no resultado desses comandos em qualquer interpretador JS:
```
1 == true
2 == true
"1" == true
[] == true
[1] == true
[true] == true
"true" == true
```

2021-06-22 16:44 UTC, GThurler commented on public/javascripts/edit_device.js
> +      isDeviceSsidPrefixEnabled == 1) {
Nesse caso aqui eu já não sei se pode cair em pegadinha ou não, mas cuidado com (variável == 'true')!

2021-06-22 16:44 UTC, GThurler commented on public/javascripts/new_device.js
> +    ssidPrefix = sessionStorage.getItem('ssidPrefix');
Mesmo comentário da pegadinha de usar == ao invés de ===

2021-06-22 20:21 UTC, W1N3 commented on controllers/device_info.js
> +          genericValidate(ssidPrefix+util.
Sim @guissenges. Essa função é chamada pela rota do deviceinfo/syn, assim ela só envia o que está no cadastro como se já estivesse validado. Acredito eu que por isso não tinha validação para o 2.4G.

2021-06-22 21:21 UTC, W1N3 commented on models/device.js
> +  isSsidPrefixEnabled: {type: Boolean, default: false},
Fiz a migration no app.js

2021-06-22 21:36 UTC, W1N3 commented on public/javascripts/edit_device.js
> +      sessionStorage.getItem('isSsidPrefixEnabled') == 'true' &&
Sim. Session storage é melhor de ser utilizado em contextos de apresentar informações. Usei ai por equívoco de conceito.

2021-06-22 21:49 UTC, W1N3 commented on controllers/acs_device_info.js
>      hasChanges = true;
- Isso já foi resolvido na função getSsidPrefix oriunda da controllers/update_flashman.js.
- Na linha 970, dentro de updateInfo, é validado novamente para assim anexar e enviar a task para o genie. Fiz isso pois em controllers/app_diagnostic_api.js e controllers/device_list.js também é chamado a função updateInfo.

2021-06-22 21:55 UTC, W1N3 commented on controllers/device_list.js
> +            validator.validateSSID, 'ssid');
Não tem mais valor global

2021-06-22 23:24 UTC, W1N3 commented on controllers/update_flashman.js
> +    if (isDeviceSsidPrefixEnabled == true) {
Isso é um poema dadaísta. Coloquei um typeof na verificação.

2021-06-23 00:56 UTC, W1N3 commented on controllers/device_list.js
> +                ssidPrefix+ssid !== ssidPrefix+matchedDevice.wifi_ssid) {
Se for comparado apenas os ssid sem terem o prefixo anexado, não é modificado a variável updateParameters para true.

2021-06-24 20:21 UTC, W1N3 commented on controllers/device_info.js
> +                wifi_ssid_5ghz),
Está errado mesmo. Vou corrigir

2021-06-28 17:45 UTC, W1N3 commented on controllers/device_list.js
> +                ssidPrefix+ssid !== ssidPrefix+matchedDevice.wifi_ssid) {
De fato isso é um problema quando o ssid vem em branco. Vou voltar pra como era e colocar outra lógica pra validar o caso em que o prefixo mudou.
A linha abaixo (matchedDevice.wifi_ssid = ssid;) não deveria ter o prefixo anexado, pois só quando se envia para a CPE que envia o prefixo anexado.
No caso dos que não possuem 5GHz, eles não possuirão a propriedade _wifi_ssid_5ghz_, logo não marca para atualizar  e cria a propriedade do model do dispositivo, nesse caso.

2021-06-29 18:20 UTC, GThurler requested changes
Uma dúvida mais geral pro @ggbruno e @guissenges :
- Quando um novo roteador se cadastrar, ele deveria trocar o SSID da rede automaticamente?

2021-06-29 18:20 UTC, GThurler commented on views/settings.pug
> +                | Habilitar prefixo SSID no WiFi dos CPEs
Wi-Fi, vou comentar logo antes que o Senges comente rsrsrs

2021-06-29 22:34 UTC, W1N3 commented on controllers/device_list.js
> +                ssidPrefix+ssid !== ssidPrefix+matchedDevice.wifi_ssid) {
Delírio da minha parte

2021-06-29 23:19 UTC, W1N3 commented on app.js
> +        }
Não tinha testado isso, bem lembrado. É bem esse comportamento como mencionou. Optei por tirar o default no mongoose.

2021-06-29 23:46 UTC, GThurler commented
> Uma dúvida mais geral pro @ggbruno e @guissenges :
> 
>     * Quando um novo roteador se cadastrar, ele deveria trocar o SSID da rede automaticamente?

Conversei depois da daily com Senges e Gaspare, o roteador após se cadastrar no Flashman deve alterar seu SSID para o valor com prefixo, caso a configuração global de prefixo esteja em "true". Na função createRegistry do controllers/device_info é criado um novo cadastro com o valor isSsidPrefixEnabled em "true", até aí tudo certo do lado do Flashman. A resposta entregue ao roteador é um json com alguns campos a serem setados no script do flashman_update.sh, e nesta resposta deve(m) estar o(s) novo(s) SSIDs já com prefixos, para serem alterados já após o contato com o Flashman. Uma referência é a resposta entregue na função updateDevicesInfo no mesmo arquivo, montada na linha 778. Nessa função todas as configs são entregues pro roteador - no caso do createRegistry precisaria passar só o(s) SSID(s) mesmo.

Do jeito que está hoje, o roteador somente sincronizaria o Wi-Fi com prefixo na próxima vez que executar o flashman_update.sh, seja num reboot ou em alguma outra alteração no Flashman.

2021-06-30 21:20 UTC, GThurler commented
Fiz alguns testes na branch aqui com meu roteador, achei alguns bugs:

1) Caso um roteador tenha o prefixo setado, quando a personalizationHash vira vazia (ie: provedor parou de pagar o app personalizado) a tabela ainda mostra o checkbox para desabilitar o prefixo, porém o prefixo em si não é mostrado no campo de SSID. Pra replicar:
- Criar uma personalizationHash na base de dados
- Habilitar o prefixo na página de configurações
- Alterar o cadastro de um roteador para utilizar o prefixo
- Remover a personalizationHash da base de dados
- Recarregar a tabela no Flashman
- Prefixo não aparece mais no campo SSID do roteador

2) O mesmo bug descrito acima também ocorre se a configuração global de prefixo for desabilitada, com uma personalizationHash válida ainda

3) No caso em que ou a personalizationHash é vazia ou a config. global de prefixo estiver desabilitada, o checkbox de manter o prefixo continua lá no form. Até aí beleza, mas se eu desabilitar o prefixo nesse roteador e depois enviar as alterações pro backend, eu consigo reativar o prefixo se eu não recarregar a página/tabela. Ou tem que rolar os checks globais no backend pra ver se pode reabilitar esse cara, ou o front end tem que sumir com o checkbox depois do backend confirmar que esse cara agora tá sem prefixo. Ou ambos, hue. Pra replicar:
- Seguir os passos do bug 1
- Desativar o prefixo no roteador e enviar o form para o backend
- Reativar o prefixo no roteador e enviar o form para o backend (deveria rejeitar / ser impossível)

4) Caso a personalizationHash esteja vazia e a config. global de prefixo esteja habilitada (ie: provedor parou de pagar o app), um novo roteador Flashbox se cadastrando no Flashman ainda recebe o prefixo configurado. Era esperado que recebesse sem prefixo, pois o app personalizado não está mais válido. Pra replicar:
- Criar uma personalizationHash na base de dados
- Habilitar o prefixo na página de configurações
- Remover a personalizationHash da base de dados
- Cadastrar novo roteador no Flashman via api do firmware
  - A resposta dessa request vai vir com os ssids com prefixo

2021-07-05 19:42 UTC, GThurler approved these changes

2021-07-05 19:43 UTC, merged