Feature/removendo features cpe
anlix-io/flashman pull request #134
Opened 2021-06-29 07:04 UTC by JotaPe

2021-06-29 17:00 UTC, GThurler requested changes
Comentário adicional sobre o package-lock.json: precisamos padronizar a versão do npm que a galera usa, vou levantar essa bola na daily pra pararmos de ter esses conflitos de 30k linhas no lock

2021-06-29 21:06 UTC, JotaPe commented on models/device_version.js
> +    },
então eu deveria  adicionar os port_forward_support e o pon_signal_support no feature_support?

2021-06-29 21:09 UTC, JotaPe commented on models/device_version.js
> +    },
Eu acho que seria melhor, só ajustar para ficar do jeito legado, já que eu não pensei dessa forma na hora de implementar, acho que fica mais enxuto e evita reescrever codigo.

2021-06-30 17:34 UTC, GThurler commented on models/device_version.js
> +    },
A ideia é ou incluir o port_forward e o pon_signal pra dentro do que você fez, ou desfazer o feature_support inteiro. Na minha opinião fica melhor colocando tudo dentro do feature_support, mas aí vai ter que tratar todos os pontos legado do código que usam esses campos.

2021-06-30 19:05 UTC, GThurler requested changes

2021-06-30 19:05 UTC, GThurler commented on test/unit/device_version.unit.test.js
> +  });
Só uma sugestão de organização, no final vai dar na mesma: ao invés de ter um teste pra cada feature de cada modelo, por que não ter um teste pra cada modelo com todas as features? Agora que todas as permissões já vem certinho do findByVersion, você pode usar o que o próprio código do Flashman usa quando dá um include do model/device_version. Algo como:
```
test('check features for ZTE F670L', () => {
  let permissions = DeviceVersion.findByVersion('V1.1.20P1T4', true, 'F670L');
  expect(permissions.grantSpeedTest).toBe(false);
  // outros expects aqui
});
```
Isso também faz com que você não precise expor o DeviceVersion.checkFeature no exports, o único ponto que ainda o usaria seria o grantBlockDevices no código da api do app do cliente, que na minha opinião deveria estar dentro do findByVersion de qualquer jeito.

2021-06-30 19:05 UTC, GThurler commented on controllers/app_device_api.js
> +    } else if (!matchedDevice.use_tr069) {
Lembrei agora também, senti falta de um else if aqui caso o dispositivo seja TR-069 pra incluir as opções do Port Forward pra passar pro que o Giovanni tá fazendo, chamando a DeviceVersion.getPortForwardTr069Compatibility

2021-06-30 19:05 UTC, GThurler commented on test/unit/device_version.unit.test.js
> +  });
Ja comentamos na daily, mas só pra relembrar que concordo que esse trecho dos testes aqui foge um pouco da tua feature, não precisaria resolver não

2021-07-02 08:48 UTC, JotaPe commented on models/device_version.js
> +    },
Foi incluido para dentro do feature_support

2021-07-03 09:26 UTC, JotaPe commented
Pronto para ser mergeado

2021-07-07 18:45 UTC, GThurler requested changes
Um adendo só: o teu package-lock.json ainda tá com o lockfileVersion 1, a development tá usando a 2, qual a versão do npm que você tá usando? Era bom colocar em alguma versão que já use a versão 2 e gerar o lock de novo pra ficar um diff correto com a development. O diff hoje tá com 17800 linhas por causa do formato diferente

2021-07-07 18:45 UTC, GThurler commented on controllers/app_device_api.js
> +  }
Caso seja um modelo Flashbox ele vai retornar sempre false. Seria bom condicionar esse checkFeature no device.use_tr069 ou algo assim

2021-07-07 18:45 UTC, GThurler commented on controllers/app_device_api.js
> +  }
Mesmo caso do processBlacklist

2021-07-07 18:45 UTC, GThurler commented on controllers/app_device_api.js
> +  }
Mesmo caso do processBlacklist

2021-07-07 18:45 UTC, GThurler commented on controllers/app_device_api.js
> +    }
Mesmo caso do processBlacklist

2021-07-07 18:45 UTC, GThurler commented on controllers/app_device_api.js
> +        );
Não era pra isso estar em outro else if aqui? Ele só deveria processar isso se for um dispositivo TR-069, mas o if verifica se __não__ é TR-069

2021-07-07 18:45 UTC, GThurler commented on models/device_version.js
> +  }
Se for um modelo Flashbox vai sempre retornar false aqui - importante adicionar uma condição nesse if pra só verificar o checkFeature se for TR-069

2021-07-07 18:45 UTC, GThurler commented on models/device_version.js
> +  }
Mesmo caso do grantupnp, mas pro speedtest nem precisaria disso aqui, não? Logo abaixo você verifica se é TR-069 e força ele pra false

2021-07-07 18:45 UTC, GThurler commented on models/device_version.js
> +  }
Mesmo problema do grantupnp. E outra - caso a feature exista, ele vai acabar retornando 0, por falta de um else da vida aqui pra retornar o valor.

2021-07-07 18:45 UTC, GThurler commented on models/device_version.js
> +  }
Mesmo problema do grantupnp

2021-07-07 18:45 UTC, GThurler commented on models/device_version.js
>    ) {
Comentando aqui só pra dar a dica - por que não usar esse formato em todos os outros "grant" da vida?

2021-07-07 18:45 UTC, GThurler commented on models/device_version.js
> +  }
Mesmo problema do grantupnp

2021-07-08 07:55 UTC, JotaPe commented on models/device_version.js
>    ) {
Teria que mudar coisas alem da task, mas seria melhor usar esse formato. Só uma pergunta, a versão da firmware (ate para Flashbox) seria nescessário para pegar exatamente as features?

2021-07-08 07:56 UTC, JotaPe commented
> Um adendo só: o teu package-lock.json ainda tá com o lockfileVersion 1, a development tá usando a 2, qual a versão do npm que você tá usando? Era bom colocar em alguma versão que já use a versão 2 e gerar o lock de novo pra ficar um diff correto com a development. O diff hoje tá com 17800 linhas por causa do formato diferente

Eu to usando 6.14 que eu acho que é a versão da LTS v14 que vem com o nodejs (eu uso nvm).

2021-07-08 07:59 UTC, JotaPe commented on models/device_version.js
> +  }
Pior que isso tinha numa outra versão da função, eu vou adicionar devolta.

2021-07-08 08:18 UTC, JotaPe commented on models/device_version.js
> +  }
Eu não sei o pq isso acontece, era para retornar true e isso ia ser falseado e continuar o processo, mas pelo jeito o includes usado na função checkFeature deve ta dando true. E isso não era para acontecer.

2021-07-12 19:34 UTC, GThurler approved these changes

2021-07-12 19:34 UTC, merged