Feature/table pon search
anlix-io/flashman pull request #136
Opened 2021-07-10 06:57 UTC by JotaPe

Os commits estão estranhos por conta do workflow que eu to tendo que usar.

2021-07-12 21:27 UTC, GThurler requested changes

2021-07-12 21:27 UTC, GThurler commented on controllers/device_list.js
> +        }
O estado "perigoso" não faz muito sentido, poderia usar o acima do pon_signal_threshold_critical_high pois pode danificar o equipamento, mas a ideia é refletir a mesma lógica do app do técnico: uma tag para ok, uma para warning e uma para erro. Talvez renomear para bom/ruim/erro ou bom/baixo/ruim?
Alguns casos que vão gerar bugs:
- "Bom" inclui quem está acima do pon_signal_threshold_critical_high
- "Ruim" deveria incluir quem está acima do pon_signal_threshold_critical_high OU abaixo do pon_signal_threshold_critical, não?

2021-07-12 21:27 UTC, GThurler commented on controllers/device_list.js
> +      query.pon_rxpower = undefined
O jeito certo de fazer essa query no mongo é usando $exists:
query.pon_rxpower = {$exists: false};

2021-07-12 21:27 UTC, GThurler commented on public/javascripts/table_anim.js
> +    }
Se estiver acima de 3 ele vai sempre cair no >= -18, tem que ser a primeira condição lá.
O estado amarelo (warning) deve ser no intervalo -18 a -23, não? E aí sim abaixo de -23 deve ser o vermelho (erro).

Outra coisa: esses valores são os defaults, o certo não seria comparar com o que está no config?

2021-07-12 21:27 UTC, GThurler commented on public/javascripts/table_anim.js
> +    let ponSignalStatusColumn = (isTR069) ? `
Ao invés de isTR069, não é melhor se guiar pelo grantPonSignalMeasure do permissions? Lembra que nem todo device TR-069 é uma ONU, ou pode não medir o sinal da fibra.

2021-07-12 21:27 UTC, GThurler commented on public/javascripts/table_anim.js
> +      '$REPLACE_PONSIGNAL'+
Isso aqui é pra ficar dentro do buildUpgradeCol mesmo?

2021-07-12 21:27 UTC, GThurler commented on public/javascripts/table_anim.js
> +            }
Não entendi porque precisa dar o replace de novo

2021-07-13 18:13 UTC, JotaPe commented on controllers/device_list.js
> +        }
Então o pon_signal_threshold_critical é quando o sinal da PON ta baixo demais, e o critical_high é quando esta acima que poderia danificar a pon. O threshold apenas é quando o sinal está baixo apenas, não baixo demais a ponto de perder o sinal.

2021-07-13 18:54 UTC, JotaPe commented on public/javascripts/table_anim.js
> +      '$REPLACE_PONSIGNAL'+
Isso ta no buildTableRowInfo

2021-07-13 18:55 UTC, JotaPe commented on public/javascripts/table_anim.js
> +            }
Eu esqueci de tirar, já que o certo seria estar dentro desse if, eu tava testando por isso tava fora.

2021-07-13 19:42 UTC, GThurler commented on controllers/device_list.js
> +        }
O fato dele estar baixo demais não necessariamente quer dizer que vai parar de funcionar - só que vai afetar o funcionamento normal do equipamento. É o equivalente a usar o Wi-Fi bem longe do ponto de acesso, pode ser que funcione mais ou menos, pode ser que seja impossível de usar. De qualquer forma, a ideia é o provedor poder consultar justamente quem está com esse sinal muito fraco, pra poder analisar o problema da rede dele. Por isso é importante poder buscar especificamente quem está com problemas (abaixo do critical ou acima do critical_high)

2021-07-15 21:31 UTC, GThurler requested changes
Lembra sempre de testar bem o código antes de mandar o PR ou algum fix pro PR, não adianta editar meia dúzia de linhas de acordo com os comentários sem testar de novo se as novas alterações consertaram o problema e não quebraram nada

2021-07-15 21:31 UTC, GThurler commented on controllers/device_list.js
> +        }
Continua com problema aqui, os mesmos que apontei no outro review e mais alguns novos:
- "Bom" (o equivalente ao verde no app) deveria ser exclusivamente quem está no intervalo [pon_signal_threshold, pon_signal_threshold_critical_high]
  - A tua query é <= pon_signal_threshold, ou seja, você tá procurando quem está com sinal PIOR que pon_signal_threshold, pelos números serem negativos
- "Ruim" (o equivalente ao amarelo no app) deveria ser exclusivamente quem está no intervalo [pon_signal_threshold_critical, pon_signal_threshold]
  - O teu segundo caso que dá o .includes('ruim') é ignorado por ser um else if com o outro .includes('ruim')
  - Nenhum dos dois casos faz a query correta, um vê se está acima do critical_high e o outro se está abaixo do critical
- "Erro" (o equivalente ao vermelho no app) deveria ser exclusivamente quem está abaixo do critical OU acima do critical_high
  - Ficou faltando um caso aqui pra verificar as condições de erro

2021-07-15 21:31 UTC, GThurler commented on public/javascripts/table_anim.js
> +  }
Você chegou a testar essa função? Se ela está renderizando as coisas certas de acordo com o que você passa? Vamos lá:
- let ponSignalStatusColumn = (isTR069) ?
  - isTR069 não está mais definido, você trocou o nome do argumento mas não o código que o usava
- Quem está abaixo de -23, pela lógica do próprio backend, deveria estar no estado de erro, aqui ele vai aparecer com a badge amarela, que deveria ser pro intervalo [-23, -18]
- Não tem um caso de badge vermelha pro sinal abaixo de -23, provavelmente porque você já o colocou no caso da badge amarela
- Já havia comentado isso anteriormente, os valores usados aqui são os defaults. Se o provedor trocar esses valores, o que você tá usando pra comparar aqui não vai bater com o que tá na base, e consequentemente com o que o provedor espera. Tem que usar os valores que vêm do config, passando eles pro front end
- O teu último else if está sem um } equivalente, ele tá fechando só lá onde a função fecha, depois do return. Eu sinceramente nem sei como isso não crashou o table_anim inteiro, o browser deve fazer alguma magia pra consertar isso

2021-07-15 21:31 UTC, GThurler commented on public/javascripts/table_anim.js
> +            if (isSuperuser || grantPonSignalSupport) {
O fato de ser superuser não tem nada a ver com mostrar essa coluna ou não - grantPonSignalSupport informa se este dispositivo tem essa informação ou não. O correto seria verificar se é tr069 E se tem suporte a essa informação. Similar a como fazemos na linha 1329 do table_anim:
if (isTR069 && grantPonSignalSupport)

2021-07-16 00:42 UTC, JotaPe commented on public/javascripts/table_anim.js
> +  }
Isso foi real um erro, eu pensei que tinha testado da ultima vez que eu pushei o codigo na maquina com as CPEs, e sobre a parte dos valores defaults, e que no front não pega o config e eu queria saber se esta certo pegar as configs do flashman no table_anim ou se já tem em outro lugar.

2021-07-16 01:41 UTC, GThurler commented on public/javascripts/table_anim.js
> +  }
As coisas do config nós pegamos no backend, e mandamos como parâmetros no indexContent pro front na hora de renderizar a página. Como você só vai precisar desses valores na tabela, poderia ao invés disso incluir na resposta da requisição que pega os resultados da busca, o table_anim chama faz uma request no /devicelist/search que retorna tudo que vai precisar pra montar a tabela. Lá no controllers/device_list se não me engano a searchDeviceReg que vai retornar as coisas pro table_anim - em algum lugar lá a gente já deve ler o config pra algo, seria só incluir os valores na resposta da requisição. Se não me engano já fazemos isso pro prefixo SSID, inclusive.

2021-07-19 20:11 UTC, GThurler requested changes
Só tirar esses códigos de outra feature mesmo. Vou só fazer uns testes a mais na minha máquina aqui e talvez revisar algumas strings pra dar o approve. Se for trocar coisas simples tipo um typo ou troca de alguma string eu já faço o commit direto antes do approve.

2021-07-19 23:29 UTC, JotaPe commented on controllers/acs_device_info.js
> +  }
Eu posso ter mergeado algo sem querer

2021-07-21 19:41 UTC, GThurler approved these changes

2021-07-21 20:02 UTC, merged