Feature/tr069 firmware update
anlix-io/flashman pull request #148
Opened 2021-07-22 14:03 UTC by W1N3

- Upload de firmware no Flashman para dispositivos TR-069
- Atualização de firmware para dispositivos TR-069

2021-07-22 16:50 UTC, guissenges requested changes

2021-07-22 16:50 UTC, guissenges commented on controllers/device_list.js
> +    matchedDevice.save(async function(err) {
Essa função changeUpdate é pequena. Faz um commit dela separado passando tudo pra async/await. Vamos tentar evitar essas callbacks com async pra não piorar muito o código

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +        reject(new Error('Timeout on '+firmware.filename+' http put'));
retorne uma mensagem em português e um pouco mais amigável

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +        reject(e);
Use um console.error para o erro "cru" e retorne uma mensagem amigável

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +  return new Promise(function(resolve, reject) {
Que tal usar o fs assíncrono e usar o async/await aqui? Estou tentando evitar o uso de novas Promises e aos poucos limpar as que já existem para o formato async/await.

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +  return new Promise(function(resolve, reject) {
Mesmo comentário sobre Promises

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +      // hostname: '207.246.65.243',
remover essa linha

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +      reject(e);
console.error e mensagem amigável aqui.

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +  return new Promise(function(resolve, reject) {
Mesmo comentário sobre Promises do anterior

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +      // hostname: '207.246.65.243',
Remover

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +      reject(e);
console.error e mensagem amigável faltando

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +    throw e;
Cuidado com esses throws aqui. device_list.js faz o catch correto, mas esse tipo de comportamento não é padrão ao longo do código. Se no futuro alguém usar a função sem muito cuidado, isso pode crashar a aplicação. Tente fazer com que a função retorne uma estrutura única de sucesso/erro e altere no device_list.js

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +    throw e;
Prefiro que esse sistem de catch/throw fique limitado dentro de uma mesma função para evitar acidentes =)

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +  return new Promise(function(resolve, reject) {
É possível usar async/await? Vamos evitar Promises...

2021-07-22 16:50 UTC, guissenges commented on controllers/acs_device_info.js
> +      // hostname: '207.246.65.243',
Remover essa linha

2021-07-22 17:07 UTC, W1N3 commented on public/javascripts/firmware_actions.js
> +    if ($(this)[0].checkValidity()) {
Ok

2021-07-22 17:07 UTC, W1N3 commented on controllers/firmware.js
> +    return res.json({success: true, type: 'danger',
Ok

2021-07-22 17:07 UTC, W1N3 commented on models/device_version.js
> +      'V1.1.20P1T18': ['V1.1.20P1T4', 'V1.1.20P3N3', 'V1.1.20P3N4D'],
Sim

2021-07-22 17:07 UTC, W1N3 commented on controllers/firmware.js
> +let getVendorByModel = function(model) {
Ok

2021-07-22 17:08 UTC, W1N3 commented on controllers/firmware.js
> +    throw new Error('Arquivo md5 não encontrado');
Ok

2021-07-22 17:11 UTC, W1N3 commented on controllers/firmware.js
> +      throw e;
Para o front é transmitido pelo cadeia de try/catch. Na linha 236 essa função delFirmware é chamada. Caso seja lançado um erro em uma das promises o catch da Promises.all responde com a mensagem de erro referente lançada.

2021-07-22 17:23 UTC, W1N3 commented on controllers/firmware.js
> +    Promise.all(promises).
Achei que ia ficar mais organizado se o then e o catch estivessem na mesma altura.
Pelo que entendi, é para adicionar a regra /* eslint dot-location: ["error", "property"] */  que garante o "." junto a propriedade/função ao invés de ser junto ao objeto. (https://eslint.org/docs/rules/dot-location)

2021-07-22 17:24 UTC, W1N3 commented on controllers/firmware.js
> +    return res.json({type: 'danger', message: 'Erro buscar na base de dados'});
Ok

2021-07-22 17:34 UTC, W1N3 commented on controllers/firmware.js
> +    if (isTR069) {
De versão da firmware.
Irei utilizar o campo release então.

2021-07-22 18:42 UTC, W1N3 commented on controllers/acs_device_info.js
> +        reject(new Error('Timeout on '+firmware.filename+' http put'));
Ok

2021-07-22 18:43 UTC, W1N3 commented on controllers/acs_device_info.js
> +        reject(e);
Ok

2021-07-22 18:59 UTC, W1N3 commented on controllers/acs_device_info.js
> +  return new Promise(function(resolve, reject) {
Vou esperar a avaliação do @GThurler.

2021-07-22 18:59 UTC, W1N3 commented on controllers/acs_device_info.js
> +      // hostname: '207.246.65.243',
Ok

2021-07-22 18:59 UTC, W1N3 commented on controllers/acs_device_info.js
> +      reject(e);
Ok

2021-07-22 19:00 UTC, W1N3 commented on controllers/acs_device_info.js
> +      // hostname: '207.246.65.243',
Ok

2021-07-22 19:00 UTC, W1N3 commented on controllers/acs_device_info.js
> +      reject(e);
Ok

2021-07-22 19:00 UTC, W1N3 commented on controllers/acs_device_info.js
> +    throw e;
Ok

2021-07-22 19:01 UTC, W1N3 commented on controllers/acs_device_info.js
> +      // hostname: '207.246.65.243',
Ok

2021-07-22 19:01 UTC, W1N3 commented on controllers/acs_device_info.js
> +  return new Promise(function(resolve, reject) {
Vou esperar a avaliação do @GThurler.

2021-07-22 19:01 UTC, W1N3 commented on controllers/acs_device_info.js
> +  return new Promise(function(resolve, reject) {
Vou esperar a avaliação do @GThurler.

2021-07-22 19:02 UTC, W1N3 commented on controllers/acs_device_info.js
> +  return new Promise(function(resolve, reject) {
Vou esperar a avaliação do @GThurler.

2021-07-22 19:23 UTC, W1N3 commented on controllers/device_list.js
> +    matchedDevice.save(async function(err) {
Ok

2021-07-22 20:13 UTC, guissenges commented on controllers/acs_device_info.js
>        throw new Error('Não existe firmware com essa versão');
Faltou resolver esse throw

2021-07-22 20:15 UTC, guissenges commented on controllers/acs_device_info.js
> +      eject(new Error('Erro ao deletar firmware no genie'));
typo aqui. o correto é reject

2021-07-22 20:15 UTC, guissenges commented on controllers/acs_device_info.js
> +      eject(new Error('Erro ao buscar firmware no genie'));
typo

2021-07-23 00:15 UTC, W1N3 commented on controllers/acs_device_info.js
>        throw new Error('Não existe firmware com essa versão');
Ok

2021-07-23 19:43 UTC, GThurler commented on controllers/firmware.js
> +  }
Achei que ficou meio repetido o código aqui, com esses dois catches fazendo quase que a mesma coisa. Não daria pra colocar todo mundo no mesmo try não? Você precisa de um segundo try dentro do try?

2021-07-23 19:43 UTC, GThurler commented on models/device_version.js
> +      'V1.1.20P1T4': ['V1.1.20P3N3', 'V1.1.20P3N4D'],
Detalhe só que a T4 é mais velha que a T18, até onde sei. Tem que inverter essa ordem só. Outra coisa - o P3N4D não está homologado ainda - temos que testar se as integrações com o flashman e com o app do técnico / cliente estão ok pra liberar esse upgrade. Isso entraria em outra feature, imo

2021-07-23 19:43 UTC, GThurler commented on models/device_version.js
> +      },
Aquilo que já comentei desse modelo ser homologado em outra feature. De curiosidade: você chegou a testar isso aqui?

2021-07-23 19:43 UTC, GThurler commented on models/device_version.js
> +      'V3.0.0C6_MUL': ['V3.0.0C5_MUL'],
Não vamos liberar o downgrade, vai que dá problema :)

2021-07-23 19:43 UTC, GThurler commented on models/device_version.js
> +    vendor: 'Nokia',
"""Nokia""" rsrsrs. Precisa alterar não, só achei engraçado mesmo hue

2021-07-23 19:43 UTC, GThurler commented on models/device_version.js
> +      firmware_upgrade: true,
Melhor jogar pra false até ter um upgrade pra ser feito, não? Meio que tanto faz

2021-07-23 19:43 UTC, GThurler commented on models/device_version.js
> +};
Isso aqui é pra retornar o que exatamente? As chaves do versions_upgrade? Tem o Object.keys pra isso

2021-07-23 19:43 UTC, GThurler commented on public/javascripts/firmware_actions.js
> +      for (let v of res.versions) {
Não precisa alterar não, mas só pra referência que um .forEach ao inves de um for talvez fique mais claro. No final das contas é preferência

2021-07-23 19:45 UTC, GThurler commented
Esqueci de deixar um comentário geral no review, mas a parte do frontend eu não olhei muito a fundo no review não. Queria primeiro usar a interface e ver como isso está se comportando antes de ir ver o código, pra mim é meio complicado compilar o JS mental pra frontend.

2021-07-26 12:52 UTC, W1N3 commented on controllers/firmware.js
> +  }
- Eu interpreto que se não tiver o segundo try, se tiver lançado um erro em addFirmwareInGenie é enviado o json de success.
- Isso eu digo pois tinha esse erro na medida que fui implementando e testando o puxadinho de aceitar firmware tr069.
- Também a property do objeto de erro lançado pelo firmware.save() é diferente da addFirmwareInGenie.

2021-07-26 12:52 UTC, W1N3 commented on models/device_version.js
> +      'V1.1.20P1T4': ['V1.1.20P3N3', 'V1.1.20P3N4D'],
Ok

2021-07-26 12:54 UTC, W1N3 commented on models/device_version.js
> +      },
Não, vou retirar

2021-07-26 12:55 UTC, W1N3 commented on models/device_version.js
> +      'V3.0.0C6_MUL': ['V3.0.0C5_MUL'],
Ok

2021-07-26 12:56 UTC, W1N3 commented on models/device_version.js
> +      firmware_upgrade: true,
Ok

2021-07-26 13:18 UTC, W1N3 commented on models/device_version.js
> +};
Sim. Vou alterar.

2021-07-26 13:27 UTC, W1N3 commented on public/javascripts/firmware_actions.js
> +      for (let v of res.versions) {
Ok

2021-08-03 21:21 UTC, GThurler reviewed
Lembrando que não é pra commitar as alterações nos arquivos dentro de /public/dist, quando dermos o merge na development vamos fazer um commit só atualizando esses caras. Isso é só pra reduzir o número de alterações nesses arquivos que são sempre modificados, deixando o histórico de commits mais leve. Como já foi feito é melhor deixar do que remover, mas vale a atenção aí pra features futuras.

Fiz um review bem mais cauteloso do frontend dessa vez, mas não fiz vários testes pra verificar o comportamento certinho, foquei mais no backend e na estrutura do código. Eu e Senges ainda vamos testar bem essa interface e esses upgrades.

2021-08-03 21:21 UTC, GThurler commented on public/javascripts/firmware_actions.js
> +  }, 'json');
Não acha ruim fazer um request desses no onChange não? Esse tipo de informação não vai ser alterada toda hora, não tem porque buscar essa informação toda hora na base - basta buscar uma vez quando a página abrir e manter o resultado pra cada modelo em memória no front mesmo, isso usa muito pouca memória.

2021-08-04 00:08 UTC, W1N3 commented on controllers/acs_device_info.js
> +  await FirmwaresAPI.uploadToGenie(binData, firmware);
Ok.
Fiz a addFirmwareInACS retornar um booleano. Ficou feio, mas foi o que deu pra fazer dado a diferença de contexto nos dois locais onde ela é chamada.

2021-08-04 00:16 UTC, W1N3 commented on controllers/external-genieacs/firmwares-api.js
> +    true, 3000, [5000, 10000]);
Ok

2021-08-04 00:33 UTC, W1N3 commented on public/javascripts/firmware_actions.js
> +  }, 'json');
Também acho. Está horrível. Vou extender as funções encapsuladas de uso do sessionStorage (public/javascripts/session_storage.js)

2021-08-04 00:35 UTC, W1N3 commented on controllers/device_list.js
> +              versions_upgrade[device.installed_release];
Bem alertado. Quando fiz essa parte eu pensei em chamar o mínimo o possível a DeviceVersion, o que acaba não sendo uma boa ideia.

2021-08-12 03:36 UTC, guissenges approved these changes

2021-08-12 03:36 UTC, merged