adding new endpoint for slave association via technician app
anlix-io/flashman pull request #167
Opened 2021-09-01 17:48 UTC by danielatk

2021-09-08 23:16 UTC, guissenges requested changes

2021-09-08 23:16 UTC, guissenges commented on controllers/app_diagnostic_api.js
> +  if (!isMasterOn) {
O mestre precisa estar online para realizar esse procedimento? Eu vejo um possível problema quando uma eventual desconexão do MQTT acontece por alguma variação na rede e então esse procedimento retornará falha. Não é incomum as conexões MQTT reconectarem... limpeza de conexões TCP em tabelas NAT são bem comuns

2021-09-08 23:16 UTC, guissenges commented on controllers/app_diagnostic_api.js
> +      return res.status(403).json({message:
Acho que ajuda retornar na mensagem de erro aqui em qual MAC de master ele está registrado pois isso á está no valor da variável, certo?

2021-09-08 23:16 UTC, guissenges commented on controllers/app_diagnostic_api.js
> +    if (matchedSlave.mesh_mode != '0' && !matchedSlave.mesh_master) {
mesh_mode é um Number e não uma String. Consertar. Use !== para que haja comparação de Number com Number

2021-09-08 23:16 UTC, guissenges commented on controllers/app_diagnostic_api.js
> +  if (isRegistered === 1 || isBridge === 1 || isSwitchEnabled === 1) {
Se isBridge e isSwitchEnabled forem igual a 2 também será preciso mandar o comando de update, não? Há dados relativos ao mesh que o slave precisa sincronizar mesmo quando já em bridge

2021-09-08 23:16 UTC, guissenges commented on controllers/app_diagnostic_api.js
> +  if (isRegistered === 1 || isBridge === 1 || isSwitchEnabled === 1) {
O isRegistered === 1 já seria suficiente.

2021-09-08 23:16 UTC, guissenges commented on controllers/app_diagnostic_api.js
> +diagAppAPIController.addSlave = async function(req, res) {
Dica: Comente brevemente o que os códigos de retorno para o app do técnico indicarão. Isso vai facilitar quem for fazer o lado do app

2021-09-09 13:47 UTC, danielatk commented on controllers/app_diagnostic_api.js
> +  if (isRegistered === 1 || isBridge === 1 || isSwitchEnabled === 1) {
Os casos onde qualquer uma dessas variáveis está igual a 1 significa que o secundário precisa fazer um update. Se o roteador já estava como secundário (ou seja, isRegistered === 2) porém não estava em modo bridge (ou seja, isBridge === 1), ele precisa fazer esse update.

2021-09-09 14:31 UTC, guissenges commented on controllers/app_diagnostic_api.js
> +  if (isRegistered === 1 || isBridge === 1 || isSwitchEnabled === 1) {
Ah sim, é um OU lógico. É verdade. Qualquer uma das 3 mudanças feitas devem refletir num update. Correto.

2021-09-11 14:44 UTC, GThurler requested changes
Comentário geral: variáveis de controle 0/1/2 são, na minha opinião, horríveis de dar manutenção e não deveriam ser usadas. No contexto do firmware que você fica limitado a retornar um errcode inteiro faz todo o sentido, mas não tem necessidade de complicar a leitura do código dessa forma em Javascript.
Sugestão: use campos booleanos ou strings de controle. Você realmente precisa encodar "mac já estava cadastrado como slave" (isRegistered 1) e "mac registrado como novo slave" (isRegistered 2) na mesma variável? Essa distinção vai ajudar o app em alguma coisa?
- Duas variáveis booleanas (registerSuccess e alreadyRegistered) resolveriam o problema
- Uma variável string (registerStatus - valores "error", "newRegister", "alreadyRegistered") também resolveria
A mesma reflexão vale para os outros dois campos.

2021-09-11 14:44 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +      ' falhou: JSON recebido não é válido',
Isso vale pra todas as respostas: eu acho meio redundante essa verbosidade da mensagem...
* Status diferente de 200 já informa pra quem mandou o request que houve uma falha
* Quem enviou a request sabe o que enviou no body, não precisa responder com o body.master e body.slave

Um simples "JSON recebido não é válido" já resolve

2021-09-11 14:44 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +  });
Sugestão: mover essa query pra depois de você validar o matchedMaster. Se a validação dele falhar você fez a query do slave à toa

2021-09-11 14:44 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +  if (pos >= 0) {
`matchedMaster.mesh_slaves.includes()` já retorna um valor booleano pra usar direto no if, acho que fica mais legível. O que você fez vai funcionar, só sugestão mesmo caso não conheça ou não tenha se lembrado do `includes()`

2021-09-11 14:44 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +    }
Isso aqui tem alguma chance de acontecer? Se tem, não faria sentido verificar se existe alguma divergência em **todas** as configs Wi-Fi ao invés de só o mesh_mode? Porque em todos os endpoints a gente já sincroniza isso, acho

2021-09-11 14:44 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +403: generic error (look at message)
403 NÃO é generic error, é (action) forbidden, geralmente por falta de permissão do usuário ou do roteador ou dados errados

2021-09-12 14:19 UTC, danielatk commented on controllers/app_diagnostic_api.js
> +    }
Então, eu discuti isso com o Guilherme ontem, se não valia a pena checar todas as configs Wi-Fi. Ele disse que era melhor fazer a sincronização do slave de qualquer jeito, ao invés de fazer o check pra todas as configs.

2021-09-20 23:11 UTC, guissenges approved these changes

2021-09-21 04:05 UTC, merged