Feature/generic programmed reboot
anlix-io/flashman pull request #187
Opened 2021-10-20 04:09 UTC by guissenges

2021-10-21 03:31 UTC, guissenges commented on app.js
> +      if (typeof schedule.is_active === 'undefined') {
Por que essa necessidade de verificar se há um scheduled com esses campos em undefined? Foi algum bug nao solucionado? Eu pensei que aqui era criado um schedule base para sanar o problema de bootstrapping da base de dados @JotaPe

2021-10-21 03:58 UTC, guissenges commented on controllers/device_info.js
> +            successReboot(matchedDevice.mesh_master);
É preciso generalizar essa função successReboot @JotaPe . Pela maquina de estados desenhada no passado, qualquer comando terá essa etapa de sucesso

2021-10-21 04:01 UTC, guissenges commented on controllers/commander/reboot.js
> +          'slave_reboots_remaining': 0,
Em models/schedule.ts, esse campo slave_reboots_remaining nao deveria ser slave_remaining? @JotaPe

2021-10-21 04:41 UTC, JotaPe commented on app.js
> +      if (typeof schedule.is_active === 'undefined') {
Minha experiencia com esse findOne não foi boa, por isso eu do essas verificadas igual o Config.findOne que tem encima.

2021-10-21 04:41 UTC, JotaPe commented on app.js
> +      if (typeof schedule.is_active === 'undefined') {
Eu deveria usar o createSchedule que eu fiz, ele é mais estavel. Eu pensei em usar, mas iria adicionar mais uma dependencia.

2021-10-21 04:52 UTC, JotaPe commented on controllers/commander/reboot.js
> +          'slave_reboots_remaining': 0,
Sim

2021-10-21 05:14 UTC, JotaPe commented on controllers/device_info.js
> +            successReboot(matchedDevice.mesh_master);
Sim, da para generalizar o rebootScheduleStatus tambem.

2021-10-21 22:15 UTC, JotaPe commented on controllers/device_info.js
> +            successReboot(matchedDevice.mesh_master);
agora ta correto

2021-11-08 19:54 UTC, GThurler requested changes
Review preliminar, ainda tô analisando as coisas que estão dentro do /controllers/commander... Vou revisar com mais comentários só desses 3 arquivos naquele diretório em breve

2021-11-08 19:54 UTC, GThurler commented on controllers/tools.ts
> +    return 'Atualização abortada - atualizando CPE secundário';
Isso aqui nunca vai ser executado por conta da ordem dos ifs, o if de cima sempre vai passar no caso desses aqui com o beforeAbort

2021-11-08 19:54 UTC, GThurler commented on controllers/commander/common.js
> +    .toString();
NÃO retornar erro / exception se a função que vai chamar isso não vai aceitar e tratar isso. Caso caia nesse caso aqui o Flashman vai crashar e reiniciar, sendo que era só ignorar e retornar algo vazio

2021-11-08 19:54 UTC, GThurler commented on controllers/commander/common.js
> +  // Change from status updating to ok
Não tá faltando o mesmo check que você corrigiu pro firmware? O de ver se o agendamento está abortado antes de mexer na base

2021-11-08 19:54 UTC, GThurler commented on controllers/commander/common.js
> +      });
Quando um comando de reboot é disparado para uma rede mesh há alguma garantia de que o slave sempre vai receber esse comando? Eu não lembro como fizemos a parte de reboot na rede mesh, mas é algo a se pensar aqui - tem que mandar o comando de reboot pro principal, e só quando ele voltar disparar pro secundário, e então quando este voltar, pro secundário seguinte, etc.

2021-11-09 19:01 UTC, GThurler requested changes
No geral, senti falta de generalizar mais as coisas que ficaram dentro do reboot.js... Do jeito que tá vamos acabar criando 600+ linhas pra cada novo agendamento, sendo 2/3 disso copiado e colado entre os arquivos.

2021-11-16 18:19 UTC, JotaPe commented on controllers/commander/reboot.js
> +export const recoverFromOffline = async (schedule) => {
Não da por conta de ser global dentro da instancia do reboot

2021-11-16 18:56 UTC, JotaPe commented on controllers/commander/reboot.js
> +export const startSchedule = async ({ request }) => {
Não da por conta da função que chama o comando especifico que você quer. markNextForReboot

2021-11-16 18:56 UTC, JotaPe commented on controllers/commander/reboot.js
> +export const abort = async () => {
Por conta de casos especiais na hora do abort tambem não da para generalizar totalmente.

2021-11-17 17:40 UTC, JotaPe commented on controllers/commander/reboot.js
> +const markSeveral = async () => {
Não, precisa da função especifica do reboot

2021-11-17 17:41 UTC, JotaPe commented on controllers/commander/reboot.js
> +const markNextToReboot = async () => {
exatamente por isso que ela não está no common, eu teria que passa uma função para ele, o que conhecendo JavaScript pode dar mais problema do que resolver algo.

2021-11-17 20:14 UTC, GThurler requested changes
* Alguns pontos levantados no review anterior não foram endereçados, deixei eles como não resolvidos
* Conforme falado na daily, acho que dá pra dar uma melhorada ainda na generalização do código que está no reboot.js, muita coisa pode ir pro common.js
* O package-lock.json foi removido do repositório, depois da um git rm e um rm normal aí. 
* Não consigo mais abrir o modal no front end, provavelmente porque você apagou o único lugar do código que dava um .modal('show') no teu modal.

Uma observação geral: toda vez que você altera algum trecho do código após um review inicial, é sempre bom dar uma repassada nas tuas alterações pra ver se nada foi quebrado ao tentar consertar o que foi apontado em um comentário do PR. Não adianta nada fazer um fix rápido pra ajeitar um comentário sem no mínimo rodar a aplicação de novo e dar uma passada nos testes básicos (abrir o modal, testar um agendamento básico, no mínimo o caminho feliz). Ainda mais num PR enorme desses com 308 arquivos inseridos/modificados, em que o review é consideravelmente mais delicado.

2021-11-17 20:14 UTC, GThurler commented on controllers/commander/common.js
> +    scheduleOfflineWatchdog();
markSeveral e scheduleOfflineWatchdog ficaram lá no reboot, não vieram pro common - você testou essa função?

2021-11-17 20:14 UTC, GThurler commented on controllers/commander/common.js
> +  let csvTmpFile = path.join(__dirname, '../../../tmp', 'massSchedule.csv');
`path` não está definido no common. Você testou essa função? Isso aqui qualquer linter ia te avisar na hora

2021-11-17 20:14 UTC, GThurler commented on controllers/commander/common.js
> +    if (!line.field1.match(macRegex)) return 0;
`macRegex` não está definido no common. Você testou essa função? Isso aqui qualquer linter ia te avisar na hora

2021-11-17 20:14 UTC, GThurler commented on controllers/commander/common.js
> +    const checkedTimeRange = allowedTimeRangeCheck(
`allowedTimeRangeCheck` não está definido no common. Você testou essa função? Isso aqui qualquer linter ia te avisar na hora

2021-11-17 20:14 UTC, GThurler commented on controllers/commander/reboot.js
> +  (parseJSON(process.env.FLM_CONCURRENT_REBOOTS_LIMIT ?? '100'));
Cuidado com essas quebras de linha entre parênteses: pode ser que pra esse getOrElse não dê problema, mas pro javascript isso fica ambíguo. O `;` é opcional na linguagem, então o interpretador poderia enfiar um `;` no final da linha 34 ali e assumir que a linha 35 é outra coisa. O correto nesse caso é abrir o `(`na linha 34 e então quebrar a linha, pra tirar qualquer ambiguidade ali.
Quem me apitou isso aqui foi o linter: https://eslint.org/docs/rules/no-unexpected-multiline

Isso aqui acontece em vários trechos do código, recomendo usar um linter

2022-01-08 22:46 UTC, guissenges commented
Essa pull request será minimamente segura apenas quando o Flashman tiver o deploy 100% em container conforme já foi falado.

2022-01-08 22:46 UTC, closed without merging