Feature/speedtest tr69
anlix-io/flashman pull request #214
Opened 2021-12-06 20:05 UTC by juliopaiva16

- Working latency diagnostics for TR-069
- Diagnostic's Provision and Preset automatically added when Flashman restarts
- Speed diagnostics are committed

2021-12-07 22:30 UTC, GThurler requested changes
Instala os pacotes SublimeLinter e SublimeLinter-eslint no sublime pra dar uma revisada nas formatações e detalhes bobos. Não apontei todos os problemas no review porque ia poluir os comentários.
Senti falta de chamar o sendPingToTraps no código que é usado pela recepção desse dado nos roteadores. Acabou que você separou no handler pra conseguir aproveitar o mesmo código em dois pontos e deixou o código duplicado.

2021-12-07 22:30 UTC, GThurler commented on controllers/acs_device_info.js
> +}
Eu achei bem confuso isso aqui... A ideia é traduzir e então pegar todos os objetos de um pedaço da árvore do genie? Se sim acho que podia pelo menos renomear essa função aqui pra algo mais descritivo, do jeito que tá a impressão que dá é que eu vou passar uma lista de campos arbitrários pra pegar do Genie. Quando na verdade não é arbitrário, é os campos de uma subárvore do TR-069

2021-12-07 22:30 UTC, GThurler commented on controllers/acs_device_info.js
> +  }
Cuidado que isso aqui só está funcionando por acaso hein - tem um `await` ali com uma callback definida... Sendo que a callback não serve pra nada. O return da callback NÃO é propagado pra fora da callback, e o fato de dar o await significa que o output do findById vai direto pra variável device ao invés da callback.
Repara que findById sempre retorna um elemento só, não é um array. O find normal ou o findByMacOrSerial que pode retornar um array.

2021-12-07 22:30 UTC, GThurler commented on controllers/device_info.js
> +
Pode tirar esse TODO aqui?

2021-12-07 22:30 UTC, GThurler commented on controllers/device_list.js
> +          }
Cuidado que se device for null/undefined ele vai cair nesse else aqui e vai mandar coisa que não deve pro deviceList

2021-12-07 22:30 UTC, GThurler commented on controllers/device_list.js
> +          } else {
Mesmo comentário acima só que nesse else aqui

2021-12-07 22:30 UTC, GThurler commented on controllers/update_flashman.js
> +      updateDiagnostics();
Faltou um await aqui, não?

2021-12-07 22:30 UTC, GThurler commented on models/device_version.js
> +      speed_test: true,
O WS5200 não tem speed_test, não?

2021-12-07 22:30 UTC, GThurler commented on models/device_version.js
> +      speed_test: true,
Cuidado que ao colocar isso aqui em true você vai liberar isso na interface. Como vamos liberar só o ping por enquanto, tem que deixar isso aqui em false

2021-12-07 22:30 UTC, GThurler commented on models/device_version.js
> +      speed_test: true,
Mesmo comentário acima

2021-12-07 22:35 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +  if (error || !device || !device.use_tr069 || !device.acs_id) {
O catch (e) jogava o resultado pro error. Devo ter feito evolução no código e esqueci de mudar ajustar isso.
Corriji aqui.

2021-12-07 22:40 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +        projection += from_genie_diagn[field] + ',';
Realmente, muito mais inteligente essa solução. Ajustado.

2021-12-07 22:41 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +  if (success) {
Ajsutado.

2021-12-07 22:42 UTC, juliopaiva16 commented on controllers/update_flashman.js
> +      updateDiagnostics();
Ajustado

2021-12-07 22:49 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +                                                      fields.diagnostics.ping);
Ok. Vou me atentar e ajustar todas as ocorrências.

2021-12-07 22:54 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +}
É. Essa função foi feita pra pegar todos os objetos de uma subárvore do genie que estejam listados em wanted_fields.
Eu pensei em fazer isso aqui pra não ter um trecho de código enorme de if checkForNestedKey.... getFromNestedKey pra uma penca de campos que eu teria que pegar. Posso renomear ela pra getObjectsFromGenie ou sei lá. O que acha? Tem uma sujestão de nome?
(Inclusive ajustar o nome dessas variáveis também. Vou dar uma boa olhada usando o Linter)

2021-12-08 15:25 UTC, juliopaiva16 commented on models/device_version.js
> +      speed_test: true,
Não. Isso aqui eu tava testando a renderização do botão, eu acho. Esqueci de tirar.

2021-12-08 16:40 UTC, closed without merging