Feature/tr069 pingtest
anlix-io/flashman pull request #216
Opened 2021-12-08 16:50 UTC by juliopaiva16

- Working latency diagnostics for TR-069
- Diagnostic's Provision and Preset automatically added when Flashman restarts
- Speed diagnostics removed
- Post PR corrections

2021-12-08 17:11 UTC, juliopaiva16 reviewed
Deixei umas perguntas aqui.

2021-12-08 17:11 UTC, juliopaiva16 commented on controllers/device_list.js
> -          return deviceListController.doSpeedTest(req, res);
A gente precisa desse return aqui?

2021-12-08 17:11 UTC, juliopaiva16 commented on controllers/external-genieacs/tasks-api.js
> +    path: '/provisions/diagnostic',
Aqui acho que cabe aquele comentário na daily sobre generalizar um putProvision e passar o nome pro path como argumento. O que acha?

2021-12-08 17:11 UTC, juliopaiva16 commented on public/javascripts/table_anim.js
> -          if (!isTR069 && (isSuperuser || grantSpeedMeasure >= 1) && grantDeviceSpeedTest) {
Aqui talvez caiba voltar com o "!isTR069 &&" antes da gente implementar o speedtest

2021-12-08 17:21 UTC, GThurler commented on controllers/device_list.js
> -          return deviceListController.doSpeedTest(req, res);
Sim, pra interromper a execução do código dessa função. Se você for ver lá embaixo tem um outro res.status(200) no final da função. Como a doSpeedTest vai responder a requisição, sem esse return aqui você teria 2 trechos de código querendo responder à mesma requisição

2021-12-08 17:21 UTC, GThurler commented on controllers/external-genieacs/tasks-api.js
> +    path: '/provisions/diagnostic',
Acho bom, evita replicar o código

2021-12-08 17:21 UTC, GThurler commented on public/javascripts/table_anim.js
> -          if (!isTR069 && (isSuperuser || grantSpeedMeasure >= 1) && grantDeviceSpeedTest) {
Pode ser também, deixa pra alterar isso na branch de speedtest

2021-12-08 17:25 UTC, juliopaiva16 commented on controllers/device_list.js
> -          return deviceListController.doSpeedTest(req, res);
Justo. Alterado.

2021-12-08 17:27 UTC, juliopaiva16 commented on controllers/external-genieacs/tasks-api.js
> +    path: '/provisions/diagnostic',
Feito.

2021-12-08 17:28 UTC, juliopaiva16 commented on public/javascripts/table_anim.js
> -          if (!isTR069 && (isSuperuser || grantSpeedMeasure >= 1) && grantDeviceSpeedTest) {
Feito.

2021-12-08 19:35 UTC, GThurler requested changes

2021-12-08 19:35 UTC, GThurler commented on controllers/update_flashman.js
> +        return reject();
Cuidado! Reject vai gerar uma exception no teu await lá embaixo e causar o um crash no Flashman. Como vai crashar entre o stop e o tart do genieacs-cwmp, o genie vai ficar offline, gerando todo tipo de problema. Troca isso aqui por um resolve() e vida que segue. Se isso aqui não rodar direito não impede o funcionamento do Flashman, só de um pedaço dele, então pegando pelo log com a mensagem acima já é suficiente

2021-12-08 19:35 UTC, GThurler commented on controllers/update_flashman.js
> +          return reject();
Mesmo comentário do reject

2021-12-08 21:00 UTC, juliopaiva16 commented on controllers/update_flashman.js
> +        return reject();
Entendi. Resolvido.

2021-12-08 21:00 UTC, juliopaiva16 commented on controllers/update_flashman.js
> +          return reject();
Corrigido.

2021-12-08 22:02 UTC, GThurler reviewed
Tudo certo, vou esperar testarmos a feature com todos os modelos na sexta para dar o approve.

2021-12-14 21:43 UTC, GThurler approved these changes

2021-12-14 21:47 UTC, merged