Feature/tr 069 speedtest
anlix-io/flashman pull request #225
Opened 2022-01-03 19:58 UTC by juliopaiva16

2022-01-04 21:49 UTC, GThurler requested changes
Comentário geral pra evitar a mesma situação que surgiu com o teste de latência: você testou o teste de velocidade do firmware após as alterações? Como mexeu em alguns trechos compartilhados ali era bom só fazer uns testes de sanidade pra ver se nada quebrou.

No mais só falta as apis dos apps mesmo e os ajustes pequenos que comentei

2022-01-04 21:49 UTC, GThurler commented on controllers/acs_device_info.js
> +  let timeout = 100;
Vai mudar o timeout mesmo? 100ms é pouco, vai acabar não medindo os casos de latência alta, não?

2022-01-04 21:49 UTC, GThurler commented on controllers/acs_device_info.js
> +            message: 'Error: Could not fire TR-069 ping measure'};
speedtest measure, não?

2022-01-04 21:49 UTC, GThurler commented on controllers/acs_device_info.js
> +    const result = await TasksAPI.addTask(acsID, task, true, 3000, []);
Aumenta isso aqui pra 10000 ao invés de 3000, vai por mim. Tivemos problemas de timeout em provedores já. Isso aqui vale pra todos os addTasks do teste de latência e do teste de velocidade

2022-01-04 21:49 UTC, GThurler commented on controllers/device_info.js
> +  console.log(req, res);
Tem que tirar isso aqui pra não poluir o log em produção

2022-01-04 21:49 UTC, GThurler commented on controllers/external-genieacs/diagnostic-provision.js
> +log('Success: Diagnostics completed.');
Não acha que vale a pena especificar o ID que terminou o diagnóstico, pra facilitar a leitura do log?

2022-01-04 21:49 UTC, GThurler commented on controllers/handlers/devices.js
> +module.exports = deviceHandlers;
Newline ao final do arquivo

2022-01-04 21:49 UTC, GThurler commented on public/javascripts/show_speed_test_actions.js
> +  console.log('Test');
Importante tirar isso aqui antes de mandar pra produção

2022-01-04 21:49 UTC, GThurler commented on public/javascripts/show_speed_test_actions.js
> +    console.log('Estimative');
Mesma coisa que acima

2022-01-05 19:29 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +  let timeout = 100;
Troquei pra agilizar os teste e esqueci de voltar pra 1000. Obrigado por lembrar!

2022-01-05 19:30 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +            message: 'Error: Could not fire TR-069 ping measure'};
Copy-paste genérico do ping ahahaha.
Ajsutei aqui.

2022-01-05 19:32 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +    const result = await TasksAPI.addTask(acsID, task, true, 3000, []);
Show. Ajsutado

2022-01-05 19:34 UTC, juliopaiva16 commented on controllers/external-genieacs/diagnostic-provision.js
> +log('Success: Diagnostics completed.');
Sim. Mudei bastante os logs dessa provision já. No próximo commit ela já sai bonitinha

2022-01-05 19:34 UTC, juliopaiva16 commented on controllers/handlers/devices.js
> +module.exports = deviceHandlers;
O Linter me obrigou a fazer isso. Que bizarro. kkkkkkkkk

2022-01-05 19:35 UTC, juliopaiva16 commented on public/javascripts/show_speed_test_actions.js
> +  console.log('Test');
Essa aí se fosse dar um blame mental seria culpa do Sengès. kkkkkkkk
Ajustado!

2022-01-05 19:36 UTC, juliopaiva16 commented on public/javascripts/show_speed_test_actions.js
> +    console.log('Estimative');
E esse blame mental seria meu kkkkkkkkkk
Resolvido!

2022-01-05 19:37 UTC, juliopaiva16 commented on controllers/handlers/devices.js
> +module.exports = deviceHandlers;
Pior que tem um monte de ocorrência agora. Vou olhar no diff antes de dar push

2022-01-08 20:44 UTC, GThurler requested changes
Só ajeitar essas besteirinhas e tá aprovado

2022-01-08 20:44 UTC, GThurler commented on controllers/acs_device_info.js
> +  console.log(req.body);
Tem que tirar esse console.log aqui

2022-01-08 20:44 UTC, GThurler commented on controllers/acs_device_info.js
> +module.exports = acsDeviceInfoController;
Newline no fim do arquivo

2022-01-08 20:44 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +module.exports = diagAppAPIController;
Newline

2022-01-08 20:44 UTC, GThurler commented on controllers/device_info.js
> +module.exports = deviceInfoController;
Newline

2022-01-08 20:44 UTC, GThurler commented on controllers/handlers/devices.js
> +module.exports = deviceHandlers;
Ainda tá sem newline :p

2022-01-08 20:59 UTC, GThurler approved these changes

2022-01-08 20:59 UTC, merged