Feature/ac10
anlix-io/flashman pull request #246
Opened 2022-02-11 17:57 UTC by W1N3

Modelo Tenda AC10

2022-02-15 23:24 UTC, GThurler requested changes

2022-02-15 23:24 UTC, GThurler commented on controllers/acs_device_info.js
> +    assocField = assocField.split('.').slice(0, -4).join('.');
Bom deixar um comentário aqui, só pra informar mesmo porque é diferente

2022-02-15 23:24 UTC, GThurler commented on controllers/device_list.js
> +            }
Isso aqui deveria entrar como um erro de validação lá em cima, já que a premissa é que esses campos todos só podem ser alterados se o wifi correspondente estiver habilitado. Essa mensagem especial tem que ser passada pro front-end também

2022-02-15 23:24 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +      }
Só pra garantir: esse cara trabalha com os canais todos em string mesmo? Porque o que você alterou vai valer pro channel dos wifis e pro stun port

2022-02-15 23:24 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +      }
Mesma dúvida para todos esses campos aqui: enable, auto, advertise é tudo string?

2022-02-15 23:24 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +  }
Precisa de um ifzão repetindo tudo? Não dá pra fazer a "bagunçinha" que fazemos pro mode/standard não?

2022-02-16 15:24 UTC, W1N3 commented on controllers/external-genieacs/devices-api.js
> +      }
Todos os campos desse modelo são tratados como string.

2022-02-16 15:24 UTC, W1N3 commented on controllers/external-genieacs/devices-api.js
> +      }
Todos os campos desse modelo são tratados como string.

2022-02-16 15:35 UTC, W1N3 commented on controllers/external-genieacs/devices-api.js
> +  }
Vou melhorar.

2022-02-16 15:36 UTC, W1N3 commented on controllers/acs_device_info.js
> +    assocField = assocField.split('.').slice(0, -4).join('.');
Vou comentar.

2022-02-16 15:36 UTC, W1N3 commented on controllers/acs_device_info.js
> +  }
Vou comentar.

2022-02-16 15:36 UTC, W1N3 commented on controllers/acs_device_info.js
> +  }
Vou melhorar.

2022-02-16 15:39 UTC, W1N3 commented on controllers/acs_device_info.js
> +  }
Aqui no create registry sim. Mas no syncDevice é possível ser eliminada essa configuração.

2022-02-16 15:40 UTC, W1N3 commented on controllers/acs_device_info.js
> +                  data.wan.pppoe_user.value !== 'none');
Vou melhorar. Só verificar se é diferente de '0', pois esse modelo trata tudo como string.

2022-02-21 17:13 UTC, GThurler requested changes

2022-02-21 17:13 UTC, GThurler commented on controllers/acs_device_info.js
> +    data.wan.pppoe_enable.value !== '0');
Cuidado que isso aqui vai quebrar para os outros modelos, a comparação com String só vale pra esse modelo (`false` é diferente de `'0'`). Talvez seja uma de fazer um OR entre a comparação com o booleado e com a string

2022-02-21 17:13 UTC, GThurler commented on controllers/acs_device_info.js
> +      matchedConfig.tr069.stun_enable.toString()) {
O AC10 manda '1' ou 'true'? Porque `true.toString()` vai resultar em `'true'`

2022-02-21 17:13 UTC, GThurler commented on controllers/acs_device_info.js
> +      data.common.stun_udp_conn_req_addr &&
Mesmos comentários do createRegistry

2022-02-21 17:13 UTC, GThurler commented on controllers/acs_device_info.js
> +      config.tr069.stun_enable.toString()) {
Mesmo comentário do createRegistry

2022-02-22 17:33 UTC, W1N3 commented on controllers/acs_device_info.js
> +      matchedConfig.tr069.stun_enable.toString()) {
Manda 'true'.

2022-03-04 21:34 UTC, merged