Feature/tr 069 block devices
anlix-io/flashman pull request #256
Opened 2022-02-23 00:53 UTC by juliopaiva16

2022-03-07 15:50 UTC, GThurler requested changes
Por último mas não menos importante - tem 1 teste falhando, provavelmente porque você mexeu lá no device_version

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +            wlanTreeRules.slice(wlanNumOfRules+diff, wlanNumOfRules);
Você em algum momento garante a ordem nesses arrays? Porque a ordenação feita pelo Mongo é de ordenação de strings. Se tiverem 11 regras, a ordem vai ser:
```
1, 10, 11, 2, 3, 4, 5, 6, 7, 8, 9
```

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +        10000, [5000, 10000]);
Eu tiraria esse [5000, 10000], se levar mais de 10 segundos nessa task é porque algo tá estranho

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +    let deleteObjTask = {
Faz sentido chamar de deleteObjTask se ele faz qualquer tipo genérico de task? Outra: faz sentido essa função existir se ela só envelopa a addTask num retorno booleano? Talvez seja uma de mover isso aqui para um handler da vida ou até mesmo pro próprio tasks-api.

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +      );
A mensagem não deveria ser mais genérica, dado que a função é usada pra todo tipo de task?

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +const newAddAcRules = async function(
Não achei muito bom esse nome aqui - o que o `new` significa ali? Acho que algo como `addACObjects` faria mais sentido

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +  let id = Number(maxId);
Isso aqui é pra converter de string pra inteiro? Esse id vai ser usado pra indicar qual o id máximo atual conforme for adicionando objetos, certo? Um nome tipo `currentMaxId` ficaria melhor, se for o caso

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +        await newDeleteAcRules(device, acRulesAdded['wifi2'].slice(-1));
Acho que vale um comentário aqui para explicar que isso aqui é pra dar rollback e não deixar a árvore desbalanceada

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +        throw new Error('newAddAcRules error');
Evite ao máximo dar `throw` assim pra outras funções pegarem - quem for usar sua função pra algo no futuro pode não perceber esse `throw` e gerar um ponto de `UncaughtException` que vai crashar o Flashman. Mais fácil ou ter um try/catch aqui dentro ou já retornar algo pra função que chama essa indicando erro

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +const newDeleteAcRules = async function(device, rulesToDelete) {
Mesmo comentário de nome que fiz acima - talvez `deleteACObjects`?

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +    if (!result) throw new Error('newDeleteAcRules error');
Mesmo comentário sobre throws

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +const newUpdateAcRules = async function (
Mesmo comentário de nomes

2022-03-07 15:50 UTC, GThurler commented on controllers/acs_device_info.js
> +        ruleName = (ruleName.length > 10) ? ruleName.slice(-10) : ruleName;
Mas precisa disso tudo? Não basta algo como `<ID>-<4 ultimos digitos do MAC>` ex.: `1-AABB` ou `30-12FA`

2022-03-07 15:50 UTC, GThurler commented on controllers/app_device_api.js
> +    let blackMacDevice = content.blacklist_device.mac.toUpperCase();
Cuidado que isso aqui vai quebrar o firmware - a padronização pro firmware é lowercase, e pra TR-069 é uppercase.

2022-03-07 15:50 UTC, GThurler commented on controllers/app_device_api.js
> +    let blackMacDevice = content.device_configs.mac.toUpperCase();
Mesmo comentário acima sobre lowercase e firmware

2022-03-07 15:50 UTC, GThurler commented on controllers/app_device_api.js
> +    let whiteMacDevice = content.whitelist_device.mac.toUpperCase();
Mesmo comentário acima sobre lowercase e firmware

2022-03-07 15:50 UTC, GThurler commented on controllers/app_device_api.js
> +      macDevice = configs.mac.toUpperCase();
Mesmo comentário acima sobre lowercase e firmware

2022-03-07 15:50 UTC, GThurler commented on controllers/device_list.js
> +            break;
Não é mais fácil chanceAcRules já retornar a mensagem pronta e um booleano de sucesso/erro?

2022-03-07 15:50 UTC, GThurler commented on views/includes/showlandevices.pug
> +        #reach-num-of-blocked-devices-limits-tr069-spam.row
Esse ID ficou meio bruto, não? Até porque, o erro que pode ser mostrado aqui é genérico, não necessariamente é sobre o limite de dispositivos, não?

2022-03-07 15:50 UTC, GThurler commented on public/javascripts/show_lan_devices_actions.js
> +                           isBridge || !(isSuperuser || grantLanDevicesBlock))
Não ficaria mais organizado calcular isso aqui separado?

2022-03-07 18:39 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +    // if this is an external bug or is specifically caused by changeAcRules
Foi resolvido sim. Depois vou remover esse comentário

2022-03-07 18:40 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +    // error.
Ué, não removi esse check não?
Remover esse check.
São 64 regras na árvore, 32 dispositivos (2 regras para cada dispositivo)

2022-03-07 18:42 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +          'error': 429,
Que tal enviar 500 e tratar a mensagem de erro individualmente? Acho que renderia economia de linhas de código e ficaria mais condizente com a situação

2022-03-07 18:42 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +      'success': false, 'error': 502,
Idem acima

2022-03-07 18:42 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +          'success': false, 'error': 502,
Idem

2022-03-07 18:43 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +  let getRulesPromise = new Promise(function(resolve, reject) {
Ok.

2022-03-07 18:43 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +        )) || maxId >= 64) {
Ok.

2022-03-08 14:28 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +    let deleteObjTask = {
Generalizei pra addOrDeleteObject, corrigi o nome do objeto de task e joguei isso pra task-api

2022-03-08 14:31 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +const newAddAcRules = async function(
Esqueci de trocar esse nome. Foi durante o processo de refactor. Eu tinha uma add, uma delete e uma updateAcRules... Daí quis refatorar as três, mas não queria trocar tudo sem que o funcionamento estivesse ok.
Então criei uma 'new' pra cada, e aí deletei as antigas depois de tudo funcionando, mas acabei esquecendo de mudar o nome

2022-03-08 14:34 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +  let id = Number(maxId);
Sim, é pra converter pra inteiro. Melhor um parseInt né?
Tem razão sobre o nome, algo mais instrutivo cairima melhor nesse caso.

2022-03-08 14:53 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +        ruleName = (ruleName.length > 10) ? ruleName.slice(-10) : ruleName;
Justíssimo

2022-03-08 15:23 UTC, juliopaiva16 commented on views/includes/showlandevices.pug
> +        #reach-num-of-blocked-devices-limits-tr069-spam.row
Ajustado

2022-03-08 18:29 UTC, juliopaiva16 commented on controllers/acs_device_info.js
> +            wlanTreeRules.slice(wlanNumOfRules+diff, wlanNumOfRules);
Eu adiciono as regras manualmente, então provavelmente essa garantia existe sim. Mas dá pra fazer uma ordenação do array pelo id da regra. Acha jogo?

2022-03-21 23:21 UTC, guissenges approved these changes

2022-03-21 23:21 UTC, merged