Feature/i18next frontend
anlix-io/flashman pull request #274
Opened 2022-03-15 21:03 UTC by cassiohg

2022-03-17 17:36 UTC, W1N3 approved these changes

2022-03-18 06:53 UTC, JotaPe approved these changes

2022-03-19 04:09 UTC, guissenges requested changes

2022-03-19 04:09 UTC, guissenges commented on public/javascripts/device_validator.js
> +  const nodeRequire = hasI18NextGlobal ? __non_webpack_require__ : require;
Essa linha está dando erro na definição de require. Reproduzido após executar 'npm run dev':
![image](https://user-images.githubusercontent.com/35816487/159106088-0aeceafe-4cd0-419b-8619-fdf1699303d6.png)

2022-03-19 08:01 UTC, cassiohg commented on public/javascripts/device_validator.js
> +  const nodeRequire = hasI18NextGlobal ? __non_webpack_require__ : require;
Resolvido

2022-03-21 03:14 UTC, guissenges approved these changes

2022-03-21 04:08 UTC, merged