Integrar GenieACS em ambiente Docker com o compose do Flashman
anlix-io/flashman pull request #327
Opened 2022-05-11 21:06 UTC by W1N3

O Flashman hoje assume que o GenieACS está junto dele num ambiente bare metal, é necessário adaptar essa integração para que seja possível ser feita num ambiente Docker.

2022-05-19 21:34 UTC, GThurler requested changes

2022-05-19 21:34 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +    process.env.FLM_IS_A_DOCKER_RUN.toString() !== 'true') {
Repara que essa função vai ser executada pelo Genie, então process.env.FLM_IS_A_DOCKER_RUN vai estar sempre undefined, a menos que passe pro env do GenieACS

Porém não importa muito, pois para o caso do Flashman Courier e ambiente docker, INSTANCES_COUNT será sempre 1

2022-05-19 21:34 UTC, GThurler commented on migrations.js
> +      config.save();
Faltou o await

2022-05-19 21:34 UTC, GThurler commented on migrations.js
> +    updater.updateDiagnostics();
Se não me engano isso aqui já é chamado em algum momento pelo app.js

2022-05-19 21:34 UTC, GThurler commented on migrations.js
> +    updater.updateDiagnostics();
Talvez por questão de organização seria bom deixar os dois juntos mesmo, só ou deletar o que está no app.js ou mover o de cá pra lá

2022-05-20 17:51 UTC, W1N3 commented on migrations.js
> +    updater.updateDiagnostics();
Essa função é chamada no stack da chamada ao updater.rebootGenie(process.env.instances) na linha 294 do app.js. Ou seja, não é executado caso seja uma execução em Docker. Nesse caso sempre é executado, pela instância principal.

Desse modo avalio retirar essa rotina da função rebootGenie.

2022-09-27 15:25 UTC, guissenges approved these changes

2022-09-27 17:41 UTC, GThurler approved these changes

2022-09-27 17:56 UTC, merged