Feature/multihosts pingtest
anlix-io/flashman pull request #332
Opened 2022-05-19 17:48 UTC by naccaratocarolina

Branch that implements the ping test for multiple hosts. A structure was created in the devices model where the partial results of the host tests are stored - the variable is initialized with empty latency and loss properties for each host. With each new test completed, this variable is populated.

To implement the loop that allows multiple tests to be run, logic similar to speed tests was implemented. The information that is sent to the flashboard through the device trap is the partial results of the tests (the structure is the same).

2022-05-19 22:36 UTC, GThurler requested changes
Comentários gerais:

- Não consegui realizar um teste de latência para um dispositivo. Cadastrei um novo CPE e ao disparar um teste ele printa no log: `No valid pingtest URL found for 00E0FC-Huawei-VMXQU21919006883`. O motivo é que na função `getNextPingTest` você olha somente o campo `device.pingtest_results`, que para um dispositivo que nunca fez um teste é todo vazio. Desse jeito também o Flashman sempre vai medir para os mesmos hosts do teste anterior, nunca consultando os hosts em `device.ping_hosts`.
- Tentei resolver o probema acima forçando um teste anterior na base com todos os completed em false, mas daí depois de fazer um teste e tentar fazer um segundo, ele nunca responde
- Não consegui testar porque da maneira como está eu não consigo ver o loading, mas o botão de "Iniciar Teste" só pode ser liberado quando o último teste acabar, não quando você receber o resultado do primeiro teste - como não vi nada no código pra controlar isso imagino que não esteja sendo feito

2022-05-19 22:36 UTC, GThurler commented on controllers/handlers/acs/diagnostics.js
> +    console.log('No valid pingtest URL found for ' + acsID);
Se a ideia é sempre cair nesse if aqui pra quebrar a recursão dos múltiplos testes, eu trocaria essa mensagem pela mensagem de teste concluído com sucesso, e tiraria o console.log de sucesso após cada teste individual, pra despoluir um pouco o log, vide print em anexo
![image](https://user-images.githubusercontent.com/37554452/169413413-12161702-ee73-4116-9e5c-8e1f7295b253.png)

2022-05-19 22:36 UTC, GThurler commented on controllers/handlers/acs/diagnostics.js
> +          model === 'EG8145X6' || model === 'HG9') {
Cuidado que isso aqui foi alterado lá na development, tá faltando 1 modelo na sua versão - lembrou de dar o merge da development pra dentro da sua feature? Se sim pode ter sido algum problema com o merge mesmo

2022-05-19 22:36 UTC, GThurler commented on models/device.js
> +            }
Não é que não funcione, mas a ideia é ver se o attr contém `pingtest_results` mesmo? Pra mim o que faz sentido é verificar uma igualdade mesmo, pois o nome do campo na base tem que bater exatamente e nunca vai ser alterado

2022-05-19 22:36 UTC, GThurler commented on public/javascripts/show_ping_test_actions.js
> +        if (hostLatency.includes('---') && hostLoss.includes('---')) {
@juliopaiva16 deve lembrar, mas em caso de erro durante o teste, ele vai mandar a latência e a perda como `---`, certo? Porque se sim vai quebrar o propósito desse if aqui

2022-05-19 22:44 UTC, GThurler commented on public/javascripts/show_ping_test_actions.js
> +        if (hostLatency.includes('---') && hostLoss.includes('---')) {
Consegui confirmar aqui na development que é isso mesmo, porém por algum motivo nessa feature o evento de erro não está sendo tratado direito... Se eu fizer 3 medições e a segunda der erro ele trava geral e nem começa o 3o

2022-05-20 17:47 UTC, naccaratocarolina commented on controllers/handlers/acs/diagnostics.js
> +      acsDiagnosticsHandler.firePingDiagnose(device._id);
A única forma de usar a função `startPingDiagnose` para permitir a recursão seria chamar o `getParameterValues` e o `addTask`. Assim, acredito que seja melhor manter a chamada para o `firePingDiagnose`.

2022-05-23 23:34 UTC, GThurler requested changes
Comentário geral:

- Nos casos em que o teste de latência apresenta algum erro a recursão não está sendo feita. Toda a lógica está encapsulada dentro de um `if` que verifica se o estado é `Complete`, ignorando os casos de erro

2022-05-23 23:34 UTC, GThurler commented on controllers/device_list.js
> +            }
Cuidado que listas vazias sempre passam em `ifs` - o que faz mais sentido é verificar se o comprimento da lista é maior do que zero, nesses casos. Aproveitando pra reforçar que esse trecho é equivalente a um `map`:
```
device.pingtest_results = device.ping_hosts.map((h)=>({host: h}));
```

2022-05-23 23:34 UTC, GThurler commented on controllers/handlers/acs/diagnostics.js
> +      );
Ficou um pouco confuso usar o nome da variável no `let` e como variável de iteração no `find`, não? Às vezes sou só eu que estou acostumado com abreviações dentro desses closures de find, map, etc., sei lá

2022-05-23 23:34 UTC, GThurler commented on controllers/handlers/acs/diagnostics.js
> +      acsDiagnosticsHandler.firePingDiagnose(device._id);
Mas aí que está, o `getParameterValues` é desnecessário, porque você já executou um pra ler o resultado do teste anterior. Hoje a sequência de tasks está da seguinte forma, fazendo 2 testes:

- getParameterValues inicial no firePingDiagnose
- setParameterValues com o host 1 no startPingDiagnose
- getParameterValues para buscar o resultado do host 1 
- getParameterValues inicial no firePingDiagnose
- setParameterValues com o host 2 no startPingDiagnose
- getParameterValues para buscar o resultado do host 2

Repara que tem 2 `getParameterValues` adjacentes fazendo a mesma coisa, e um deles poderia ser pulado justamente chamando o `startPingDiagnose` na recursão

2022-05-23 23:34 UTC, GThurler commented on public/javascripts/edit_device.js
> +  if (validateWifi && password.length !== 0) {
Essas alterações aqui são da outra feature, certo? Depois só tira elas dessa branch aqui

2022-05-23 23:34 UTC, GThurler commented on public/javascripts/show_ping_test_actions.js
> +        if (isCompleted === false) {
Acho que fica mais claro explicitar no `if` um check da existência de `completed` em `value` pra deixar mais legível caso alguém tenha que dar manutenção no código

2022-05-27 22:40 UTC, GThurler approved these changes

2022-05-27 22:40 UTC, merged