Adding backup of VoIP and IPv6 fields to flashman
anlix-io/flashman pull request #334
Opened 2022-05-25 20:17 UTC by juliopaiva16

Added IPv6 and VoIP settings to Flashman in order to run the reconfigureFromBackup funcion from the apps

2022-05-30 17:56 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +            (ipv6Enabled) ? ipv6Mode : null;
Faz sentido armazenar isso aqui como `null` ao invés de `''`? Minha única preocupação é se alguém tiver que ler esse campo em algum lugar ter de lembrar que pode ser null

2022-05-30 17:56 UTC, GThurler commented on models/device.js
> +    ipv6_mode: {type: String, default: null},
Seguindo o comentário acima, o default não faz sentido ser `''`?

2022-05-31 02:02 UTC, juliopaiva16 commented on controllers/app_diagnostic_api.js
> +            (ipv6Enabled) ? ipv6Mode : null;
![image](https://user-images.githubusercontent.com/92058228/171078214-337f6fa6-0880-46a3-a307-28818d87bacf.png)

2022-05-31 02:03 UTC, juliopaiva16 commented on controllers/app_diagnostic_api.js
> +            (ipv6Enabled) ? ipv6Mode : null;
Acho que é preferível se aproveitar dos defaults do mongo, só setando o valor no banco quando ele realmente é algo que nos importa. Ajustei o valor default do ipv6_mode pra uma String vazia, conforme recomendado

2022-05-31 02:04 UTC, juliopaiva16 commented on models/device.js
> +    ipv6_mode: {type: String, default: null},
`custom_tr069_fields: {
    intelbras_omci_mode: String, // used by WiFiber to specifiy OLT OMCI mode
    voip_enabled: {type: Boolean, default: false},
    ipv6_enabled: {type: Boolean, default: false},
    ipv6_mode: {type: String, default: ''},
  },`

2022-05-31 02:04 UTC, juliopaiva16 commented on models/device.js
> +    ipv6_mode: {type: String, default: null},
Ajustado

2022-05-31 14:45 UTC, GThurler requested changes

2022-05-31 14:45 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +            device.custom_tr069_fields.ipv6_enabled = ipv6Enabled;
Se `ipv6Enabled` for falso aqui você não vai salvar as alterações na base de dados

2022-05-31 14:45 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +          }
Mesma coisa pro `voipEnabled` aqui

2022-05-31 14:45 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +              }
Falta um `else` aqui para aplicar o default de string vazia, não? Senão ao passar essa informação para o app do cliente, a condição `'ipv6_enabled' in deviceCustomFields && 'ipv6_mode' in deviceCustomFields` não será satisfeita

2022-05-31 19:48 UTC, GThurler approved these changes

2022-05-31 19:53 UTC, merged