Feature/external reference fields validation
anlix-io/flashman pull request #375
Opened 2022-07-28 14:32 UTC by juliopaiva16

2022-07-28 17:23 UTC, GThurler requested changes
- Caso legado em que o CPF/CNPJ já está fora do formato fica acusando erro ao tentar salvar alguma outra alteração, precisa validar _somente_ se o usuário alterar o kind ou data
- O regex está impedindo o cadastro de CPF/CNPJ só com números pela API (e pelo front por causa do bug da máscara não carregar imediatamente na linha da tabela)

2022-08-01 19:57 UTC, GThurler requested changes

2022-08-01 19:57 UTC, GThurler commented on controllers/handlers/util.js
> +      .toUpperCase();
Não faz mais sentido esses regexes virem do json de tradução? Me preocupa isso aqui ficar uma sopa de regexes quando tivermos um monte de idiomas

2022-08-02 13:56 UTC, juliopaiva16 commented on controllers/handlers/util.js
> +      .toUpperCase();
Justo. Vou acertar isso

2022-08-03 18:55 UTC, guissenges commented
Peguei um problema. Do jeito que está, o frontend está obrigando a inserir algo para salvar os dados...
![image](https://user-images.githubusercontent.com/35816487/182687386-5ccf7e80-4a02-45e8-b42b-2b5559ff2a0d.png)
Esse campo não pdoe ser obrigatorio

2022-08-04 03:12 UTC, merged