Feature/auto lock license
anlix-io/flashman pull request #384
Opened 2022-08-10 15:33 UTC by juliopaiva16

2022-08-12 20:16 UTC, W1N3 requested changes
Falta review da parte mais complexa.
 - controllers/app_diagnostic_api.js
 - controllers/device_list.js
 - controllers/handlers/devices.js

2022-08-15 18:59 UTC, W1N3 requested changes

2022-08-15 18:59 UTC, W1N3 commented on controllers/device_list.js
> +      if (device.mesh_slaves && device.mesh_slaves.length > 0) {
Existe uma inconsistência prática nesse fluxo de execução.
Apenas o primeiro dispositivo da lista de dispositivos é de fato deletado ou avaliado que não foi possível ser deletado.
Os outros dispositivos nem chegam a ser availados ou deletados.
Esse comportamento é devido ao return dentro do loop.

2022-08-15 18:59 UTC, W1N3 commented on controllers/device_list.js
> +      if (device.mesh_slaves && device.mesh_slaves.length > 0) {
Seria mais consistente fazer essa validação de se existe alguma CPE como MESH principal na lista de dispositivos a serem deletados de forma separada da tentativa de remoção dos dispositivos.
Pois caso exista alguma CPE como MESH principal nao meio da lista, todo o fluxo é interrompido, podendo ter deletado algumas CPEs e não ter bloqueado a licença dessas mesmas.

2022-08-15 18:59 UTC, W1N3 commented on controllers/device_list.js
> +        return res.status(500).json({success: false, type: 'danger',
Tal como o comentário acima. Além de separar a validação da remoção, ter um controle de quais dispositivos de fato foram deletados, bloquear apenas os que foram deletados e informar como mensagem de erro quais falharam ao serem removidos se houver algum que falhou a ser removido.

Como avalia essa situação @guissenges? É mais consistente esse comportamento que proponho?

2022-08-16 02:53 UTC, guissenges commented on controllers/device_list.js
> +        return res.status(500).json({success: false, type: 'danger',
Concordo que o erro de alguns CPEs não deveria impedir a remoção dos demais selecionados (exceto os CPEs em mesh, claro)

2022-08-17 18:54 UTC, W1N3 approved these changes

2022-08-22 17:26 UTC, GThurler approved these changes

2022-08-22 17:27 UTC, merged