Adding Raisecom REV N to flashman
anlix-io/flashman pull request #399
Opened 2022-08-25 20:48 UTC by juliopaiva16

2022-08-25 22:01 UTC, juliopaiva16 commented
Ainda precisa adicionar o validator pra não permitir espaços nos SSID

2022-09-05 22:31 UTC, GThurler requested changes
Pendente os testes com o modelo em si, só revisei o código por enquanto

2022-09-05 22:31 UTC, GThurler commented on controllers/acs_device_info.js
> +  }
Typo `hm_version` -> `hw_version`
O `installed_release` é a versão de **firmware** sempre! Tem que tirar esse `if`do meio aí

2022-09-05 22:31 UTC, GThurler commented on models/device_version.js
> +    grantSpaces: cpePermissions.wifi.allowSpaces,
Eu talvez trocasse pra `grantSsidSpaces`, só pra deixar future-proof mesmo

2022-09-06 21:24 UTC, GThurler approved these changes

2022-09-06 21:25 UTC, merged