Feature/160 bandwidth
anlix-io/flashman pull request #454
Opened 2022-10-31 18:47 UTC by naccaratocarolina

2022-11-25 20:54 UTC, GThurler requested changes
- App do cliente e app do técnico não foram modificados para receber a nova largura de banda

2022-11-25 20:54 UTC, GThurler commented on controllers/app_diagnostic_api.js
> +          content.wifi_band_5ghz !== 'auto160' || permissions.grantWifiBandAuto5_160
Essa lógica aqui está errada, vai passar sempre porque "auto" é diferente de "auto160"

2022-11-25 20:54 UTC, GThurler commented on controllers/app_device_api.js
> +      content.wifi_band_5ghz !== 'auto160' || permissions.grantWifiBandAuto5_160
Essa lógica aqui está errada, vai passar sempre porque "auto" é diferente de "auto160"

2022-11-25 20:54 UTC, GThurler commented on controllers/device_list.js
> +                    band != 'auto160' || permissions.grantWifiBandAuto5_160) {
Essa lógica aqui está errada, vai passar sempre porque "auto" é diferente de "auto160"

2022-11-25 20:54 UTC, GThurler commented on public/javascripts/table_anim.js
> +                              t(autoText)+
Cuidado que "Auto 20/40/80 MHz" não é uma chave i18n

2022-11-25 20:54 UTC, GThurler commented on public/javascripts/table_anim.js
> +                              t('Auto 20/40/80/160 MHz')+
Cuidado que "Auto 20/40/80/160 MHz" não é uma chave i18n

2023-07-06 16:50 UTC, ggbruno commented
Passou muito tempo... A branch precisa ser reimplementada...

2023-07-06 16:50 UTC, closed without merging