Feature/tr069 mass upgrade
anlix-io/flashman pull request #478
Opened 2022-12-27 12:56 UTC by lucasperovani

- Added TR-069 mass upgrade
- Added test cases for mass upgrade
- Fixed errors with mass upgrade

2022-12-27 20:59 UTC, GThurler requested changes

2022-12-27 20:59 UTC, GThurler commented on controllers/update_scheduler.js
> +      return {success: true, marked: false};
Ao invés de `marked:false`, usar `marked:true` e uma nova flag para evitar o não preenchimento de slots que ainda estavam disponíveis

2022-12-27 20:59 UTC, GThurler commented on controllers/update_scheduler.js
> +          if (device.use_tr069 === false) {
CPEs que estão na base desde antes da existência de TR-069 no Flashman terão `user_tr069` como `undefined`

2022-12-27 20:59 UTC, GThurler commented on controllers/update_scheduler.js
> +          if (!firmwares) return false;
Não vai pegar lista vazia - momento Javascript número 1203987182
`!firmwares || !firmwares.length` resolve

2022-12-27 20:59 UTC, GThurler commented on controllers/update_scheduler.js
> +        if (device.use_tr069 === false) {
Mesma coisa de alguns comentários acima - use_tr069 pode ser undefined

2022-12-27 20:59 UTC, GThurler commented on controllers/update_scheduler.js
> +        })();
Dá pra desfazer essa declaração/chamada inline

2023-01-09 20:42 UTC, GThurler requested changes
Comentários gerais:
- Acho que dá pra reduzir o padding entre o "Tipo do Upgrade" o aviso acima dele
- Acho que dá pra reduzir o padding entre o botão com o dropdown de firmwares e o warnings abaixo dele
- O warning de modelos pra TR-069 não faz sentido, talvez trocar por algo tipo "X CPEs tem firmware Anlix e Y não são do modelo correspondente ao firmware selecionado"
- O warning para Firmware não possui informação de "X CPEs são TR-069, por isso não atuaizarão" ou algo assim

2023-01-09 20:42 UTC, GThurler commented on controllers/update_scheduler.js
> +          if (device.use_tr069 === false || device.use_tr069 === undefined) {
Pode ser simplificado com !device.use_tr069

2023-01-10 13:27 UTC, lucasperovani commented on controllers/acs_device_info.js
> +  }
O await é resolvido imediatamente porque a config está sendo passada. Passo o isUpdating para o successUpdate mesmo?

2023-01-16 21:24 UTC, merged