Deletar CPE da base de dados do GenieACS quando deletado da base do Flashman
anlix-io/flashman pull request #499
Opened 2023-01-19 20:22 UTC by W1N3

2023-01-23 23:30 UTC, GThurler requested changes
Testes não passam:

 FAIL  test/unit/device_list.test.js
  ● Test suite failed to run

    Returning a Promise from "describe" is not supported. Tests must be defined synchronously.

2023-01-23 23:30 UTC, GThurler commented on controllers/device_list.js
> +        }
`removalOK` vai ser sempre """true""" aqui, por causa da falta de um await
Faz sentido jogar um `operationUnsuccessful` assim? Acho que a mensagem de erro tem que ser mais específica

2023-01-23 23:30 UTC, GThurler commented on controllers/external-genieacs/tasks-api.js
> +};
Tem algum motivo pra essas função não ser um inline lá na `deleteDeviceFromGenie`? Achei meio desnecessário isolar isso aqui numa função própria

2023-01-23 23:30 UTC, GThurler commented on controllers/external-genieacs/tasks-api.js
> +      // remove from genieacs database if env var is set
Comentário ainda referencia variável de ambinte que não existe mais

2023-01-24 17:03 UTC, W1N3 commented on controllers/device_list.js
> +        }
Troquei para genieacsCommunicationError

2023-01-26 17:23 UTC, GThurler requested changes

2023-01-26 17:23 UTC, GThurler commented on controllers/device_list.js
> +        removalOK = await TasksAPI.deleteDeviceFromGenie(device);
Isso aqui só pode ser feito se o roteador for TR-069, se for nosso firmware vai gerar erro

2023-01-26 18:24 UTC, GThurler requested changes

2023-01-26 18:24 UTC, GThurler commented on controllers/device_list.js
> +        }
Cuidado que agora ele só vai adicionar no removedDevIds se for TR-069

2023-01-26 19:47 UTC, GThurler approved these changes

2023-01-26 19:52 UTC, merged