Feature/no-return-from-update
anlix-io/flashman pull request #500
Opened 2023-01-23 19:41 UTC by lucasperovani

Added support for cpes that will not return to flashman in order to continue the upgrade instead of getting stuck waiting for the never returning cpe.

2023-01-24 00:01 UTC, GThurler requested changes
Só uma consideração de design do front:

Achei que faltou um destaque de alerta ao checkbox, com alguma explicação do porquê ele seria útil. Similar ao que fazemos com o botão de "Forçar conexão de CPEs offline" na página de configurações, acho que ficaria bom colocar ele dentro de uma `div` vermelha daquela, com um ícone de alerta e explicando um pouco mais sobre o checkbox

Sugestões de texto para essa div:
- (Checkbox) Esses CPEs não retornarão ao Flashman após a atualização de firmware
- (Texto normal) Cuidado! Esta opção só deve ser marcada se os CPEs estão retornando para a firmware de fábrica, ou se a release selecionada migrará os CPEs para outro Flashman

2023-01-24 17:40 UTC, lucasperovani commented on controllers/update_scheduler_common.js
> +    );
Removi ele, mas pensei que seria legal ter uma mensagem de log aqui caso fosse necessário debugar.

2023-01-26 18:03 UTC, GThurler requested changes
Realizar as alterações de design que comversamos na Anlix

2023-01-26 21:47 UTC, GThurler approved these changes

2023-01-26 21:47 UTC, merged