Allow modify port forward in blocked cpe
anlix-io/flashman pull request #547
Opened 2023-02-23 20:43 UTC by W1N3

2023-02-27 15:28 UTC, ggbruno requested changes

2023-02-27 15:28 UTC, ggbruno commented on controllers/handlers/acs/port_forward.js
> +  let changeEntriesSizeTask = {name: '', objectName: ''};
Não tem necessidade de alterar o default. O comportamento default é deixar o addObject e apenas alterar o name da task quando for algo diferente... Já tem pontos do código assim (linha 422).

2023-02-27 15:28 UTC, ggbruno commented on controllers/handlers/acs/port_forward.js
> +      console.log('[!] -> '+e.message+' in '+acsID);
Se der algum erro no catch, o código continua sua execução. Esse é o comportamento esperado? Se for, o return na linha 413 não deveria existir... Se não for, deveria ter algum return de erro aqui...

2023-02-27 16:53 UTC, W1N3 commented on controllers/handlers/acs/port_forward.js
> +      console.log('[!] -> '+e.message+' in '+acsID);
Os outros catches estariam errados também

2023-03-06 17:44 UTC, ggbruno approved these changes

2023-03-06 17:44 UTC, merged