Feature/fix-web-password
anlix-io/flashman pull request #564
Opened 2023-03-06 14:20 UTC by lucasperovani

- Changed logic to update web admin login and password after a firmware upgrade.
- Moved tests.
- Added tests.

2023-03-09 22:23 UTC, ggbruno requested changes

2023-03-09 22:23 UTC, ggbruno commented on controllers/external-genieacs/devices-api.js
> +const DeviceModel = require('../../models/device');
Remover isso.... Acho que é coisa antiga de alguma branch antiga....

2023-03-10 15:23 UTC, lucasperovani commented on controllers/external-genieacs/devices-api.js
> +const DeviceModel = require('../../models/device');
Remover o que especificamente? Os requires são necessários em outros pontos do arquivos.

2023-03-20 18:57 UTC, ggbruno approved these changes

2023-03-20 18:58 UTC, merged