Feature/configuration of web login attempt in app
anlix-io/flashman pull request #599
Opened 2023-03-30 18:01 UTC by W1N3

2023-03-31 20:01 UTC, ggbruno requested changes
Remover os arquivos public/dist

2023-03-31 20:42 UTC, W1N3 commented on public/locales/pt/translation.json
> +	"enableSpecificAppTechnicianWebLogin": "Ativar tentativa específica de login na interface web no aplicativo do técnico",
Eu acho que dessa forma pode deixar a entender que o técnico vai poder alterar o login e a senha da interface web da CPE pelo app do técnico.
Avalio que assim fica melhor: "Permitir que o técnico possa tentar configurar uma CPE pelo aplicativo com login e senha específica da interface web"

2023-04-03 15:17 UTC, GThurler commented on public/locales/pt/translation.json
> +	"enableSpecificAppTechnicianWebLogin": "Ativar tentativa específica de login na interface web no aplicativo do técnico",
"Login e senha específica" não significa nada pro provedor, o que você quer comunicar é a ação de ele poder especificar qual o login que será usado, pra mim algo assim faz mais sentido:
`"Permitir que o técnico especifique as credenciais usadas para login no CPE durante o uso do app"`
Ou alguma variação dessa frase

2023-04-11 19:15 UTC, ggbruno approved these changes

2023-04-11 19:18 UTC, merged