Feature/wifi cripto
anlix-io/flashman pull request #682
Opened 2023-06-29 20:51 UTC by naccaratocarolina

2023-07-05 03:26 UTC, ggbruno requested changes

2023-07-05 03:26 UTC, ggbruno commented on controllers/external-genieacs/cpe-models/base-model.js
> +  device, wpaMode, security, fields, masterKey, cpe,
Rever essa função... As tasks não devem ser definidas aqui... se a funcao para gerar as tasks for complexa, definir flags no permission.wifi para mudar o padrão da função

2023-07-05 03:26 UTC, ggbruno commented on controllers/external-genieacs/cpe-models/base-model.js
> +    beaconType = cpe.convertBeaconType(wpaMode);
Não é necessário... cpe já é uma copia do basicCPEmodel.

2023-07-05 03:26 UTC, ggbruno commented on controllers/device_info.js
> +      'wifi_wpa_mode': wpaMode,
CUIDADO... esse é o processo de criação do firmware... o firmware não possui essa funcionalidade...
Realizar teste com um firmware...

2023-07-05 03:26 UTC, ggbruno commented on controllers/external-genieacs/cpe-models/base-model.js
> +  wpaMode, security, fields, masterKey, permissions,
O mesmo aqui... é necessária uma função na CPE? Converter para flags da CPE (permission.wifi)

2023-07-05 03:26 UTC, ggbruno commented on controllers/external-genieacs/cpe-models/zyxel-ex3220-t0.js
> +  switch (wpaMode) {
O Zyxel já retorna o getBeaconType como WPA3!!! verificar os beacontypes!

2023-07-05 03:26 UTC, ggbruno commented on controllers/external-genieacs/cpe-models/zyxel-ex3220-t0.js
> +  permissions.wifi.listSecurityModes = ['AES'];
O Zyxel possui WPA3 quando o beacontype for 11iandWPA3

2023-07-05 03:26 UTC, ggbruno commented on models/device.js
> +  wifi_wpa_mode: String,
modos não são apenas strings... melhor converter para enuns... A gente tem um suporte finito de valores!

2023-07-05 03:26 UTC, ggbruno commented on public/javascripts/table_anim.js
> +      securityElement.value = 'TKIP';
O mesmo deve ocorrer em WPA3 (AES)... Verificar!

2023-07-05 21:33 UTC, ggbruno requested changes

2023-07-05 21:33 UTC, ggbruno commented on controllers/acs_device_info.js
> -      }
O getBeaconType ainda é necessário nos roteadores que não foram homologados para segurança em WIFI.
Ele só morre nos que a gente já homologou a segurança. Tem que verificar aqui se precisa ou não ainda usar...

2023-07-06 17:43 UTC, naccaratocarolina commented on controllers/external-genieacs/cpe-models/base-model.js
> +    beaconType = cpe.convertBeaconType(wpaMode);
Esse trecho é necessário porque eu quero que as implementações definidas nos arquivos de cada cpe prevaleçam na hora de tranduzir o beaconType para o formato correto de cada CPE. Para as CPEs que possuem uma tradução do formato flashman para o seu formato diferente da implementação do basicCPEmodel, esta versão deve ser usada.

2023-07-06 20:21 UTC, naccaratocarolina commented on controllers/external-genieacs/cpe-models/zyxel-ex3220-t0.js
> +  switch (wpaMode) {
Na verdade, acredito que o WPA3 que o Zyxel possui é o algoritmo WPA3-SAE/WPA2-PSK. Pensei que só daríamos suporte para PSK.

2023-07-06 20:22 UTC, naccaratocarolina commented on controllers/external-genieacs/cpe-models/zyxel-ex3220-t0.js
> +  permissions.wifi.listSecurityModes = ['AES'];
Posso considerar WPA3-SAE/WPA2-PSK como WPA3-PSK/WPA2-PSK?

2023-07-06 20:22 UTC, naccaratocarolina commented on public/javascripts/table_anim.js
> +      securityElement.value = 'TKIP';
Feito

2023-07-06 20:23 UTC, naccaratocarolina commented on controllers/acs_device_info.js
> -      }
Corrigido. Agora depende da permissão de leitoda do beacon, que por default é falsa.

2023-07-11 18:43 UTC, ggbruno approved these changes

2023-07-11 18:43 UTC, merged