Feature/ipv6 multiwan
anlix-io/flashman pull request #690
Opened 2023-07-10 17:12 UTC by lucasperovani

- Added multi WAN support for IPv6 features and WAN and LAN information.
- Fixed tests

2023-07-10 22:35 UTC, ggbruno requested changes

2023-07-10 22:35 UTC, ggbruno commented on controllers/external-genieacs/cpe-models/huawei-hs8145v5.js
> +    'X_HW_IPv6Interface.*.IPv6Prefix.*.Prefix';
Verifica esse roteador para ver se não quebra o multiwan. Como a arvore não esta no WANDevice, não sei como ele vai reagir.

2023-07-11 19:39 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/huawei-hs8145v5.js
> +    'X_HW_IPv6Interface.*.IPv6Prefix.*.Prefix';
Está funcionando!

2023-07-12 01:16 UTC, ggbruno approved these changes

2023-07-12 01:17 UTC, merged