Feature/search v3
anlix-io/flashman pull request #703
Opened 2023-07-18 20:00 UTC by naccaratocarolina

2023-07-19 17:39 UTC, naccaratocarolina commented
Analisando essa estrutura:
```
wan: [{
    name: String,
    mac: String,
    uptime: {type: Number, default: 0}, // seconds
    connection_type: {type: String, enum: ['pppoe', 'dhcp', 'static']},
    ppp: {
      user: String,
      password: String,
      concentrator_ip: String,
      concentrator_mac: String,
    },
    vlan: Number,
    mtu: Number,
    ipv4_external: String, // external ipv4 (as seen by the ISP)
    ipv4_internal: String, // internal ipv4 (as seen by the CPE)
    ipv4_gateway: String,
    ipv6: [String], // Array of all ipv6 addresses
    ipv6_gateway: String,
    dns_servers: String, // String which is a comma separated list of servers
    ipv6_pd: String,
    bytes: [{
      epoch: Number,
      down: Number,
      up: Number,
    }],
  }],
  ```
  
  Acredito que tem alguns problemas:
  - O atributo ```ipv6``` corresponde a uma lista de strings. Porém, o atributo atual de device que este corresponde, que é ```prefix_delegation_addr``` é uma string. O atributo ```ipv6``` deve ser um array da forma ```[prefix_delegation_addr]```?
  - Outro problema é em relação à estrutura ```bytes```. Essa estrutura corresponde ao atributo ```wan_bytes``` que possui a seguinte estrutura: ```{epoch: [down bytes, up bytes]}```.  Não tem como ```epoch``` ser um Number.
  
  Acho que seria bom dar um confere nessa estrutura de referencia antes de lançar esse PR. 
  
  @lucasperovani

2023-07-20 02:15 UTC, lucasperovani requested changes

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +        concentrator_mac: device.pppoe_mac,
Poderia ter usado o `newFields` e `deleteProjection` para fazer as mesmas operações, mas sem problemas.

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +      delete wanData.bytes;
Pode deixar um array vazio para o `wanData.bytes`, para o caso de alguém usar esse campo sem validação

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +    if (!isEmpty) {
Caso todo o `wanData` seja undefined, seria bom setar o `device.wan` como um array vazio.

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +      value === undefined || (Array.isArray(value) && value.length === 0)
Seria legal comparar o value com os outros casos também, poderia fazer: `!value`

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +      return wifi2[key] === undefined;
Mesmo caso da wan de usar undefined apenas

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +    if (wifiData.length > 0) {
Não precisa dessa validação, pode deixar como um array vazio mesmo.

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +  return devices.map((device) => {
Usa o `map` lá no `search` e remove aqui, porque aí a gente consegue usar quando tiver que fazer a troca para um device só sem precisar transformar para array e depois remover do array.

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +  return devices.map((device) => {
Mesmo do `map` de cima

2023-07-20 02:15 UTC, lucasperovani commented on controllers/api/v3.js
> +  devices.docs = convertMultiWan(devices.docs);
Podia ter usado `map` ao invés de lá de cima

2023-07-20 17:51 UTC, naccaratocarolina commented on controllers/api/v3.js
> +    if (wifiData.length > 0) {
Feito! Agora quando está vazio retorna a estrutura {"_id":"00:04:16:40:C8:84","wan":[],"wifi":[]}

2023-07-21 21:04 UTC, lucasperovani approved these changes

2023-07-21 21:12 UTC, lucasperovani commented
O código ficou bem legal! Parabéns! 😁️
Obs: Só adicionei uns comentários para eu conseguir entender depois xD

2023-07-21 21:15 UTC, merged