Feature/show add new cpe
anlix-io/flashman pull request #737
Opened 2023-08-09 19:10 UTC by naccaratocarolina

2023-08-10 03:23 UTC, ggbruno requested changes

2023-08-10 03:23 UTC, ggbruno commented on public/javascripts/table_anim.js
> +    type: 'GET',
usa o setConfigStorage e getConfigStorage para evitar um GET sempre que o table anim carregar....

2023-08-17 15:59 UTC, lucasperovani approved these changes

2023-08-17 16:00 UTC, lucasperovani approved these changes

2023-08-17 16:01 UTC, merged