Feature/port foward multiwan
anlix-io/flashman pull request #752
Opened 2023-08-22 21:34 UTC by naccaratocarolina

2023-08-25 14:52 UTC, lucasperovani requested changes
Talvez tenha que adicionar os campos do port mapping para esses roteadores TR181 que usam o `getModels()` e depois o `convertIGDtoDevice()` ou subsituir eles pelo `getTR181ModelFields` mas teria que verificar a homologação se permanece correta.

Uma dica é usar o genieacs-ui para ver o que está sendo setado na cpe e junto com as faults. Se precisar, me fala que eu te passo.

2023-08-25 14:52 UTC, lucasperovani commented on controllers/handlers/acs/port_forward.js
> +    return result.join('.').replace(/\.+$/, '');
Caso retorne uma string vazia acima, essa linha retornará algo do tipo: `'Device..Interface..40'`. Talvez seja legal remover todas as strings vazias antes do join

2023-08-25 14:52 UTC, lucasperovani commented on controllers/handlers/acs/port_forward.js
> +const acsDeviceInfo = require('../../acs_device_info');
Esses imports (debug e acsDeviceIndo) ainda são necessários?

2023-08-25 14:52 UTC, lucasperovani commented on controllers/handlers/acs/port_forward.js
>  };
Eu testei com o HC220 G5. Ele é um TR181 que usa o `getModels()` e depois converte esses itens para os campos do TR181. A seleção da interface estava errado, precisava ser `'Device.IP.Interface.40.'`, o que gerava um erro na task. Além disso, para esse modelo, como ele não possui o `fields.port_mapping_values.lease` e `fields.port_mapping_values.remote_host`, isso também gerava problema na task. E como ele é convertido do modelo antigo para o novo (e não usando o `getTR181ModelFields()`) vinha um campo faltando que crashava nessa função, acredito ter corrigido com o `&& interf`.

2023-08-28 17:53 UTC, naccaratocarolina commented on controllers/handlers/acs/port_forward.js
>  };
Percebi que esse erro aconteceu porque o arquivo js do HC220 estava incorreto. 

As linhas
```
let fields = basicCPEModel.getModelFields();
fields = basicCPEModel.convertIGDtoDevice(fields);
```

Deveriam ter sido substituidas por
`let fields = basicCPEModel.getTR181ModelFields();`

2023-08-28 20:26 UTC, lucasperovani approved these changes

2023-08-28 20:26 UTC, merged