Feature/device search and status in parallel
anlix-io/flashman pull request #759
Opened 2023-08-28 19:23 UTC by cassiohg

2023-08-31 15:42 UTC, lucasperovani requested changes

2023-08-31 15:42 UTC, lucasperovani commented on controllers/device_list.js
>      });
Os roteadores não estão mostrando as firmwares para fazer o upgrade na tabela (falta o campo releases dentro do matchedDevice)

2023-08-31 18:40 UTC, cassiohg commented on controllers/device_list.js
>      });
Resolvido.

2023-08-31 18:40 UTC, cassiohg commented on controllers/firmware.js
> +}
Resolvido

2023-08-31 18:41 UTC, cassiohg commented on controllers/firmware.js
> +// that argument is passed as true.
Essa função nao é exposta. Não faz parte de nenhuma api.

2023-09-04 17:37 UTC, lucasperovani commented on controllers/firmware.js
> +// that argument is passed as true.
Sim, mas o JSDoc não é para nenhuma API, mas para referência nossa do código. A gente consegue gerar uma documentação dos parâmetros da função, o que ela retorna e pra que serve. Se rodar `npm run gen-doc`, ele cria arquivos de documentação na pasta docs. Além disso a gente consegue só colocar o mouse sobre a função para ver o que ela faz.

2023-09-04 18:04 UTC, lucasperovani approved these changes

2023-09-04 18:58 UTC, merged