Feature/voip get api v3
anlix-io/flashman pull request #761
Opened 2023-08-29 00:06 UTC by GThurler

2 tests are being ignored until we have the proper `grant` permission structure AND a VOIP-compatible simulator

2023-08-31 20:51 UTC, lucasperovani requested changes

2023-08-31 20:51 UTC, lucasperovani commented on test/black-box/v3.test.js
> +          );
Faltou passar o model do cpe

2023-08-31 20:51 UTC, lucasperovani commented on docs/api/v3/get_device_responses_schemas.yaml
> +          example: {}
Seria legal se isso fosse genérico :)

2023-08-31 21:34 UTC, GThurler commented on test/black-box/v3.test.js
> +          );
O model tá ali, é o cpe.id. O que pode ser é aquilo que a gente falou do serial vir 0/1/2 e conflitar. Quando tiver os modelos lá no simulador eu atualizo isso

2023-08-31 21:35 UTC, GThurler commented on docs/api/v3/get_device_responses_schemas.yaml
> +          example: {}
Vou transformar, só vai ter que mudar algumas strings pra trocar "voip" por "feature"

2023-09-13 23:51 UTC, GThurler commented
@ggbruno Preciso de um approve lá no https://github.com/anlix-io/genieacs-sim/pull/17 pros testes aqui passarem. Na real preciso do version bump lá pra poder alterar o package.json aqui, e aí sim poder rodar os testes. Todos os testes passaram na minha máquina, com o simulador local

2023-09-18 14:15 UTC, lucasperovani reviewed
Só algumas sugestões...

2023-09-18 14:15 UTC, lucasperovani commented on docs/api/v3/get_device_responses_schemas.yaml
> +    'Get Device - 200 Response - Success - VOIP Config':
As outras rotas vão incluir as informações de VoIP? Porque teríamos que adicionar esses campos para o `success` das outras rotas. Caso contrário, teria que adicionar o `voice_services` no `reducedDeviceFields`.
Acredito que seria `VoIP` ao invés de `VOIP` em alguns pontos aqui.

2023-09-18 14:35 UTC, GThurler commented on docs/api/v3/get_device_responses_schemas.yaml
> +    'Get Device - 200 Response - Success - VOIP Config':
Eu acho que não, justamente pra separar as funcionalidades da API e não cair no caso que caímos na v2 de ter que se preocupar com o retorno de N endpoints ao mudar um detalhe no voip, por exemplo

2023-09-18 15:06 UTC, lucasperovani commented on docs/api/v3/get_device_responses_schemas.yaml
> +    'Get Device - 200 Response - Success - VOIP Config':
A ideia era que quando um campo novo saísse ele entraria na resposta, mas fica a vontade para mudar. Acho que só tem que tomar cuidado para ver se a query no mongo não vai ter um `false` e um `true` ao mesmo tempo

2023-09-18 15:08 UTC, lucasperovani approved these changes

2023-09-18 15:10 UTC, GThurler commented on docs/api/v3/get_device_responses_schemas.yaml
> +    'Get Device - 200 Response - Success - VOIP Config':
Se for mudar seria outro PR, é mais pra gente gerenciar o caso de esquecimento melhor:
- Se esquecermos de incluir, basta um hotfix pra incluir
- Se esquecermos de tirar, alguém pode já estar dependendo desse campo pra algo

A ideia seria realmente pegar o oposto, pra não misturar `true` e `false` pra ficar ainda mais confuso, rsrs

2023-09-18 15:16 UTC, lucasperovani commented on docs/api/v3/get_device_responses_schemas.yaml
> +    'Get Device - 200 Response - Success - VOIP Config':
Sim, eu concordo. Eu só não lembro se na época eu tive problema com isso do `true` e `false` ou se foi porque vinha algum campo adicional que é calculado no `deviceModel` mas não estava na base.

2023-09-18 17:10 UTC, merged