Feature/integrated flashify models
anlix-io/flashman pull request #764
Opened 2023-08-29 22:33 UTC by rilpires

[O Fortuna](https://www.myinstants.com/en/instant/o-fortuna/)

2023-08-29 23:50 UTC, GThurler requested changes
Não olhei os arquivos novos do W4, EX220 ou o geralzão novo do Flashify, vou deixar o pepino pro Gaspare :)

2023-08-29 23:50 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +
Isso tudo aqui fica melhor resolvido com o card no backlog do Flashman de desacoplar o código do Flashman das extensions, pra não precisar ter essa conexão com o Redis aqui. No mínimo tem que ter um `if` aqui

2023-08-29 23:50 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +  modelSerial = decodeURI(modelSerial);
Mesmo comentário que fiz acima

2023-08-29 23:50 UTC, GThurler commented on controllers/external-genieacs/devices-api.js
> +        }
Isso aqui só não pode entrar na development, tem que tirar antes do merge. Entendo que é bom para os testes

2023-09-25 21:46 UTC, rilpires commented on controllers/external-genieacs/tasks-api.js
Trabalhando com mongo local em docker, existe a necessidade de se usar esse parâmetro de directConnection. Não sei pq isso é necessário, mas facilita nossa vida dev...

2023-09-25 22:02 UTC, rilpires commented on controllers/external-genieacs/devices-api.js
> +
O que essa lógica aqui está fazendo é:
Se o flashify estiver habilitado (FLM_USE_FLASHIFY), procura-se em um Map pela chave 'productClass@modelName'. Se esta chave existir, temos um segundo Map, onde cada chave é uma versão de firmware (caso tenhamos múltiplos jsons de um mesmo modelo em versões diferentes)

Tendo um mapa de versão de firmware, caso tenhamos apenas uma versão (uma chave), usaremos essa chave. Caso tenhamos mais de versão (múltiplas chaves), a versão que usaremos é a **mais recente que é mais antiga que a versão pedida** (comparação de versão é feita usando o versionCompare PADRÃO. Isso precisa ser revisitado em breve. Por enquanto não faz diferença pois não temos ainda múltiplas versões de um mesmo modelo)

2023-09-25 22:07 UTC, rilpires commented on controllers/external-genieacs/devices-api.js
> +
Essa função "fillFlashifyModels" itera sobre todos os jsons localizados na pasta "flashify" e atualiza o Map "flashifyModels" (o que aponta para outros maps onde as chaves são versões de firwmare e os valores são os modelos objetos)

OBS: As chaves são replicadas para as versões COM e SEM o url decoding do genie

2023-09-25 22:14 UTC, rilpires commented on controllers/external-genieacs/devices-api.js
> +
Mecanismo que só existe se a variável estiver habilitada...
Esse mecanismo tem uma lógica simples porém muito conveniente para nós devs que usamos genie em docker... que funciona da seguinte maneira:

- Quem carregar esse arquivos (devices-api.js) em memória (todas as instâncias do flashman, todas as instâncias do genie, todas as instâncias workers do genie cwmp) vai dar um SUB num canal do redis de nome "cpe_models_refresh".

- Quando qualquer um desses agentes receber uma mensagem nesse canal (que contém o pid do agente que disparou), chama a função `fillFlashifyModels()` que faz uma passada na pasta de jsons, atualizando o Map `flashifyModels`. Não precisamos reiniciar nenhum genie!

- Só quem dispara uma mensagem nesse canal é a primeira instância do flashman, no momento que ele sobe. Ou seja, sempre que o flashman for reiniciado, essa mensagem vai ser disparada uma vez.

Simples e efetivo!

2023-09-25 22:32 UTC, rilpires commented on controllers/external-genieacs/tasks-api.js
> +  mongoURI += '/?directConnection=true';
odeWrite: true

2023-09-25 22:32 UTC, rilpires commented on controllers/external-genieacs/tasks-api.js
> +  mongoURI += '/?directConnection=true';
Trabalhando com mongo local em docker, existe a necessidade de se usar esse parâmetro de directConnection. Não sei pq isso é necessário, mas facilita nossa vida dev...

2023-09-25 22:33 UTC, rilpires commented on locals.js
> +  return !!(process.env.GENIEACS_MONGODB_CONNECTION_URL);
O nome certo da variável é esse...

2023-09-25 22:48 UTC, rilpires commented on controllers/external-genieacs/cpe-models/tplink-ex220.js
> +  fields.wan.port_mapping = 'Device.NAT.PortMapping'; // This field exists??
Isso aqui pra mim é pra ser emoldurado

2023-09-25 22:50 UTC, rilpires commented on controllers/external-genieacs/cpe-models/tplink-ex220.js
> +  fields.wan.port_mapping = 'Device.NAT.PortMapping'; // This field exists??
Existe, fui ver depois

2023-09-26 14:59 UTC, lucasperovani commented on controllers/external-genieacs/tasks-api.js
> +  mongoURI += '/?directConnection=true';
Consegui usar o mongo local em docker sem problemas. Mas acho melhor fazer a mesma verificação de cima se precisar adicionar de fato isso: `process.env.FLM_MONGODB_USE_DIRECT_CONNECTION === true || process.env.FLM_MONGODB_USE_DIRECT_CONNECTION === 'true'`

2023-09-26 15:33 UTC, lucasperovani commented on controllers/external-genieacs/devices-api.js
> +
Acho que seria legal colocar essas informaçẽos como comentário no código, acima do primeiro `if`.

2023-09-26 15:50 UTC, lucasperovani commented on controllers/external-genieacs/devices-api.js
> +  });
O `then` e o `catch` poderiam ficar na linha de cima. Seria legal trocar o `catch` por um `try/catch`.

2023-09-26 17:30 UTC, lucasperovani commented on controllers/external-genieacs/devices-api.js
> +
Podia escrever essas informações no código como comentário para quando a gente for analisar o código depois.

2023-09-27 17:06 UTC, rilpires commented on controllers/external-genieacs/devices-api.js
> +  });
Pra eu trocar pra `try/catch`, eu deveria usar `await`. Não posso usar `await` nessa hora, pois essa chamada de rotina está sendo executada no carregamento do modulo (quando se é dado um `require`). Para esses tipos de problema, eu deveria usar o `pre-init.js` (rotinas assincronas de inicialização), mas não posso mover esse código pra lá pois ele precisa ser executado também pelo genie...

2023-09-27 17:12 UTC, rilpires commented on controllers/external-genieacs/devices-api.js
> +
OK, vou adicionar

2023-09-27 17:27 UTC, rilpires commented on controllers/external-genieacs/devices-api.js
> +
Vou colocar :+1:

2023-09-27 17:39 UTC, rilpires commented on controllers/external-genieacs/tasks-api.js
> +  mongoURI += '/?directConnection=true';
Po, mas `process.env` sempre é string, variável de ambiente que não é string não faz sentido...

https://nodejs.org/docs/latest-v12.x/api/process.html#process_process_env

No node12 sempre é string, se colocar um booleano ele passa pra string, nas versões futuras ele disse que pode até dar exception se não passar pra cá

2023-09-27 17:41 UTC, lucasperovani requested changes
Deu trabalho, ajeitei algumas identações ,`==` e `!=` para `===` e `!==`. Mas ainda tem outros casos que não resolvi. mas está revisado! (Obs: menos os js e json dentro da pasta flashify).
`user_description` nos json está vindo com caracteres inválidos.
Só existe o arquivo `tplink_xc220_g3.json` sem a sua versão js. Isto está correto?

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
`!==` ao invés de `!=`. Como o `if` é pequeno, você pode optar por colocar ela inline (só uma dica mesmo, não precisa alterar)

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  return Boolean(featureObject && (featureObject['status'] == 'FeatureStatus.success'));
Não precisa colocar `Boolean`, mas pode deixar assim que dá para entender que retornar um boolean. Trocar `==` por `===`

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Nada está sendo retornado para esse caso. Tudo bem que retornar nada é undefined. Mas é bom ter um valor safe no final da função pelo menos.

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +        }
Imagino que gostaria de verificar também se `overrided[k]` é um array vazio, não?

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      }
Por incrível que pareça, `null` é um objeto, como não foi validado acima, tentar acessar `null[k]` gera uma exception. O mesmo acontece em `Object.keys(null)`

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    } else if ((!onlyOnEmpty) || overrided[k]=='' || overrided[k] == undefined ) {
Você pode testar todos esses casos no priimeiro `if` com `!overrided[k]`, só tomando cuidado com o valor 0. O `null` também será sobrescrito.

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +) => {
Acho que os nomes ficaram um pouco complicados de entender o que é o que. Tive que ler a função para entender. Poderia colocar algo tipo `base` e `overwriteObject` ou algo do tipo que fique mais fácil entender. Seria legal colocar um JSDoc para essa função.

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    if (overrided[k] == undefined) {
`===` ao invés de `==`. Talvez queira analisar `null` também?

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  if (overwrite == undefined) {
`===` ao invés de `==`. Validar se `overrided` não é um objeto ou `null` para ter certeza que está fazendo a operação corretamente.

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      if (tr069type && (tr069type != 'xsd:string')) {
`!==` ao invés de `!=`

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Mesmo caso de acima, não seria legal retornar uma função default?

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Nesse caso, não deveria sempre retornar uma função que retorna 1 ou algo do tipo? E mais futuramente, caso haja algum cpe com `div24` diferente de `div50`, poderíamos fazer algo que depende de qual wifi selecionado para a conversão de `rate`, não?

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  return JSON.parse(data);
Colocar um `try/catch` aqui para evitar problemas caso `data` venha algo inválido (`undefined`, `null`, JSON mal formatado, arquivo em branco, binário...)

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // Shorting the function name and args to save up a lot of space 📈📈
Que o ascii se exploda! xD

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      if (typeof(fields.wan[k]) == 'string') {
Substituir `==` por `===`. Seria bom se a variável `k` recebesse um nome melhor

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +          .replace(/WANIPConnection\.[0-9]+/, 'WANIPConnection.*');
Alinhamento dos `.replace` está errado.

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      } else if (ss && !sa && !rs && !ra) {
Podia melhorar os nomes das variáveis para ficar mais fácil de entender.

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +        }
Seria bom ter um valor default para não quebrar o restante

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +        };
`undefined` foi checado embaixo, embora `firstConvert` já valide `undefined`, seria legal checar aqui também

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      divFactor = 1;
Podia fazer no mesmo formato que o `convertPingTestResult`.

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    );
Melhor fazer a mesma verificação que os outros, não? "`xxx || 1`"

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +
Talvez fosse interessante fazer essas funções separadamente e só anexar nesse objeto. Porque fica mais fácil de adicionar JSDoc e isso ser exportado para documentação, além de ter cada função separada e um objeto reduzido.

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      table50[rfa('wifi5BandEdit', 'band80_mapping')] = 'VHT80';
Imagino que 160MHz venha depois, certo?

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // TO-DO: This should return the CPE field value for WPA2 or WPA/WPA2
Modificar `TO-DO`s por `TODO:` ou `TODO(pessoa):`

2023-09-27 17:41 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Se não puder trocar o nome, ainda sim vai retornar uma função que retorna o nome?

2023-09-27 17:46 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +/* eslint-disable max-len */
😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

2023-09-27 17:47 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +
Você se refere à que funções? Às que buscam os campos do Json, as funções "builders", ou as funções do baseModel que est~ao faltando??

2023-09-27 17:48 UTC, lucasperovani commented on controllers/external-genieacs/tasks-api.js
> +  mongoURI += '/?directConnection=true';
Tranquilo então! Não sabia que vinha sempre como string porque no nosso environment a gente coloca booleanos e números. Mas entendo que isso é convertido para string. O problema é se por algum acaso converter `true` para 1 por exemplo como o javascript faz em alguns checks.

2023-09-27 17:48 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // TO-DO: This should return the CPE field value for WPA2 or WPA/WPA2
Belezura

2023-09-27 17:51 UTC, lucasperovani commented on controllers/external-genieacs/devices-api.js
> +  });
Tranquilo então. O problema que para fazer algum teste unitário para esse módulo a gente vai ter que mockar o then e depois o catch num objeto. Mas tranquilo, se é inviável fazer isso.

2023-09-27 17:53 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +
Sim! hahah
Por exemplo para as funções: `instantiateOverrideModel`, `buildIdentifierFromFlashifyModel`, `flashifyModelConstructor`, `getFeature`...

2023-09-27 17:55 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Se não puder trocar o nome, espero que essa função não seja chamada! Ou ela é chamada assim mesmo? O port mapping provavelmente estará desabilitado (ele, aliás, tá desabilitado por causa de flashify ainda melhorando esse teste)
Só coloquei esse else pra retornar alguma coisa e não crashar o flashman. O que o flashman faz quando não dá pra configurar o nome do port mapping?

2023-09-27 17:57 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      table50[rfa('wifi5BandEdit', 'band80_mapping')] = 'VHT80';
Realmente, vou adicionar aqui! Boa!

2023-09-27 18:03 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Está certo, se colocar alguma coisa diferente pode ser que dê problema no flashman. Coloca um comentário explicando esse caso, que precisa retornar alguma outra coisa para caso chegue nesse ponto.

2023-09-27 18:25 UTC, rilpires commented on controllers/external-genieacs/tasks-api.js
> +  mongoURI += '/?directConnection=true';
meu comentário foi duas vzs, foi mal (meu pc travou e achei q tinha q escrever de novo)

2023-09-28 15:52 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  let model = instantiateOverrideModel(filename.replace('.json', '.js'));
A função `instantiateOverrideModel` tem um tryCatch e, se não encontrar, ele retorna objeto vazio.
O ideal é que os arquivos `.js` dos modelos não existam mesmo, eles vão existir como uma espécie de 'correção manual'. Em vez de consertamos uma certa feature indo alterar o json, consertaremos usando o respectivo `.js` como já usamos nos models javascript antigos

2023-09-28 15:53 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +
Feito!

2023-09-28 15:53 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +let warned = false;
Apaguei essa variável

2023-09-28 16:57 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  warned = true;
Não sei seu entendi à que lógica você se refere, mas eu movi essa parte pra fora dessa função, pra passar a ser executada na "raíz" deste módulo

2023-09-28 17:07 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  return ret;
coisas frutos de debugger (queria ver resultado do recursive)

2023-09-28 17:10 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Realmente, botei o return na raíz da função

2023-09-28 17:14 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +) => {
Troquei o overrided pra `base` e coloquei jsdoc (como em todas as funções fora do builders)

2023-09-28 17:15 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  if (overwrite == undefined) {
Feito

2023-09-28 17:17 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    if (overrided[k] == undefined) {
`===` foi, já o `null`, não acho uma boa ideia. Alguma permission nossa pode querer trabalhar com valor `null`, isso me parece um valor válido que eu quero manter e não sobrescrever, diferente de `undefined`

2023-09-28 17:18 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +        }
Também não, array vazio é um campo válido. Modos de criptografia válidos... vazio. Não quero sobrescrever esse valor com o de um base-model

2023-09-28 17:19 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      }
`null` é um objeto !? Meu deus

2023-09-28 17:22 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    } else if ((!onlyOnEmpty) || overrided[k]=='' || overrided[k] == undefined ) {
Como falei em outro comentário do `null`, essa lógica de considerar apenas estes campos como "não preenchido" me faz mais sentido...

2023-09-28 17:32 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // Shorting the function name and args to save up a lot of space 📈📈
removi 😓😓😓😓😓😓

2023-09-28 17:38 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +
Hmmm... concordo... mas se eu mexer nessa função agora, vai bagunçar todos os comentários eu acho... pq não seria legal só colocar o jsdoc aqui??

2023-09-28 17:45 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      } else if (ss && !sa && !rs && !ra) {
Feito (e poluído) !

2023-09-28 18:02 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      divFactor = 1;
vc diz fazer
`divFactor = divFactor || 1`?
Pq isso vai deixar passar -1... quero evitar -1 também... que é o valor default no json (nada a ver)
Por causa disso queria na verdade deixar o `convertPingTestResult` igual esse

2023-09-28 18:03 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    );
Boa

2023-09-28 18:07 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Fallbackei pra 1. No futuro, se a assinatura da função mudar pra `convertWifiRate(is5ghz)`, sim, já teremos a informação

2023-09-28 18:10 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
retornar função default, vc diz, retornar um "div" default, né isso? se for, já o fiz

2023-09-28 18:31 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  return JSON.parse(data);
Vou colocar um @throws (jsdoc) apropriado no `flashifyModelConstructor` pra isso ficar mais claro

2023-09-28 18:38 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +const propertyBuilder = {
Vou mover a baleia em um commit então...

2023-09-28 18:48 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +const propertyBuilder = {
Cara, a ordem de declaração das funções, isso não deveria importar se eu usasse
`function foo(arg) {...}`
em vez de 
`const foo = (arg) => {...}`
Por causa disso, estou trocando todas as funções da raíz desse arquivo pro primeiro método

(uma discussao sobre o assunto: https://stackoverflow.com/questions/7609276/javascript-function-order-why-does-it-matter)

2023-09-28 18:53 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Feito

2023-09-29 17:29 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    }
Nesse caso, como é algo simples, acho que fica mais fácil de entender desse jeito

2023-09-29 17:37 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +
Tranquilo, serve também, a questão de separar é que iria de fato cada função separada e o objeto ficaria menor. Objetos e funções grandes dá medo kkkkk

2023-09-29 17:40 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      divFactor = 1;
Isso! É porque é interessante colocar as 2 verificações. Nesse ponto não está sendo validado `NaN`

2023-09-29 17:43 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  return JSON.parse(data);
Se for deixar assim, todas as função que usarem ela precisarão ter um `catch`. É fácil de esquecer que essa função pode dar um `throw`. Nesse caso, todo o Flashman iria crashar... Não acho legal fazer isso só para buscar um modelo, ainda que inválido

2023-09-29 17:59 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  let model = instantiateOverrideModel(filename.replace('.json', '.js'));
Eu acho isso de dar um `throw` muito ruim, tendo condição de tratar o erro sem gerar um `throw`... Sempre quando alguém for usar essa função, essa pessoa vai ter que tomar cuidado de usar um `try/catch`

2023-09-29 19:27 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      ]);
Bem, é verdade, só q hoje nenhum modelo se precaveu de não ter, e também não existe permission que desabilita passar auto pro canal...

2023-09-29 20:44 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    );
Podia fazer a validação do `xxx || 1` aqui também

2023-09-29 20:50 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      } else if (ss && !sa && !rs && !ra) {
Tá maravilhiWonderful!

2023-09-29 20:54 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // Shorting the function name and args to save up a lot of space 📈📈
Esse comentário era brincadeira. Emoji dá mais cor ao código, faz um commit adicionando aí de novo! hahah
Brincadeira, teria que ver se o @GThurler deixa 👀️

2023-09-29 21:02 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    );
Mas eu fiz um if ali em baixo colocando em 1 se for menor que zero

2023-09-29 21:12 UTC, rilpires commented on controllers/external-genieacs/devices-api.js
> +  modelSerial = decodeURI(modelSerial);
donado

2023-09-29 21:12 UTC, rilpires commented on controllers/acs_device_info.js
> +  model = decodeURI(model);
donado

2023-10-02 16:11 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    );
coloquei o `|| 1`

2023-10-02 16:14 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  let model = instantiateOverrideModel(filename.replace('.json', '.js'));
Coloquei um try/catch no JSON.parse, os `if null console.error return` nos 2 de cima, e não coloquei mais nenhum `try/catch` por não saber mesmo onde pode existir problema

2023-10-02 20:25 UTC, lucasperovani approved these changes

2023-10-02 20:28 UTC, GThurler approved these changes
#InLucasWeTrust

2023-10-02 20:34 UTC, merged