Campos VoIP
anlix-io/flashman pull request #772
Opened 2023-08-31 18:51 UTC by ggbruno

- Adicionadas permissions para VoIP
- Adicionados campos VoIP
- Adicionadas funções de conversão

2023-08-31 21:15 UTC, GThurler approved these changes
@lucasperovani Aguardo seu approve também

2023-09-01 14:56 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +};
Podia colocar no formato de JSDoc até pela conversa com Romeu...
As funções de conversão dos campos do CPE para o Flashman precisam de outra função de conversão do Flashman para o CPE.
phone_number e tr069_name podem precisar de conversão. O tr069_name porque podem haver roteadores que não implementam essa funcionalidade. phone_number pode ter diferença entre incluir ou não parêntesis, DDD, código do país... Os outros campos podem precisar de conversão também, mas por agora não há necessidade (Assim como aconteceu com a senha de um roteador precisar passar por um hash...)

2023-09-01 14:56 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +    },
Por causa desse .1 é bom a gente já deixar preparado para múltiplos voice services para não termos que reimplementar o multi voice service. Teríamos que mudar o device para o voip estar dentro de um array de voice services.

2023-09-01 14:56 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +    },
Para o base, não seria legal colocar 0 para o `pots`` e o `regions` como vazio ou apenas com `'BR'`

2023-09-01 16:53 UTC, ggbruno commented on controllers/external-genieacs/cpe-models/base-model.js
> +};
Os sets a gente vai fazer depois.
O name, pode vir vazio. A maioria dos roteadores retorna name vazio. É obrigatorio na especificação. Acredito não precisar de conversão por ser uma string sem formato no flashman.
Phone number, pela especificação, não é um numero de telefone mas sim uma string(32)

2023-09-01 17:48 UTC, GThurler requested changes

2023-09-01 17:48 UTC, GThurler commented on controllers/external-genieacs/cpe-models/base-model.js
> +};
Essa função deve validar se o region recebido está no array de regions permitidos, se não deve retornar "unknown", conforme o enum da base

2023-09-01 17:48 UTC, GThurler commented on controllers/external-genieacs/cpe-models/base-model.js
> +};
Essa função deve validar se o status recebido está no array de enum da base, se não deve retornar "unknown", conforme o enum da base

2023-09-01 20:45 UTC, GThurler approved these changes

2023-09-01 21:02 UTC, lucasperovani approved these changes

2023-09-01 21:02 UTC, merged