Feature/hide ssid
anlix-io/flashman pull request #773
Opened 2023-08-31 21:08 UTC by naccaratocarolina

2023-09-04 16:44 UTC, GThurler requested changes

2023-09-04 16:44 UTC, GThurler commented on controllers/device_list.js
> +                wifiHidden !== '' && wifiHidden !== matchedDevice.wifi_hidden) {
Qual a necessidade desse check de string vazia?

2023-09-04 18:04 UTC, GThurler requested changes
Ficou faltando também "migrar" o legado:
- CPEs que vão se cadastrar tem que entrar com a informação de Wi-Fi hidden já na base (hoje todos estão undefined)
- CPEs já cadastradas tem que atualizar o valor default da base
- CPEs com o valor alterado localmente devem trocar para o valor que está no Flashman durante o sync

2023-09-05 17:29 UTC, GThurler requested changes

2023-09-05 17:29 UTC, GThurler commented on controllers/acs_device_info.js
> +      if (device.has_synced_wifi_hidden === undefined) {
Melhor verificar se é `false` ou `undefined`, não? Pega o legado e qualquer caso em que o sync está falso
```suggestion
      if (!device.has_synced_wifi_hidden) {
```

2023-09-05 17:29 UTC, GThurler commented on controllers/acs_device_info.js
> +        }
Esse `if` não deveria existir, porque a gente não está alterando no CPE, a gente está lendo. A permissão correta a se checar é a `grantWifiHideSsidRead`, mas como pra entrar aqui a gente já tem que ter essa permissão E ter conseguido ler algo, o if fica redundante - basta só sempre executar o conteúdo dele

2023-09-05 17:29 UTC, GThurler commented on controllers/acs_device_info.js
> +          }
Não entendi a lógica de verificar o `dualBand` - esse código foi copiado e colado? Pra mim esse set para TRUE deve acontecer sempre
É porque as informações do 5GHz só são setadas lá embaixo? Se sim, esses 2 valores devem ser syncados juntos, de forma que esse set do `has_synced_wifi_hidden` seja atômico

2023-09-05 17:29 UTC, GThurler commented on controllers/acs_device_info.js
> +          device.wifi_hidden = hidden;
`wifi_hidden` não é um booleano na base, é 0 ou 1. Tem que converter aqui, senão vai dar crash na hora de salvar - você testou o sync?

2023-09-05 17:29 UTC, GThurler commented on controllers/acs_device_info.js
> +          changes.wifi2.hidden = device.wifi_hidden;
Cuidado que o que vem da base é 0 ou 1, e na CPE tem que ir true ou false. Tem que converter o valor

2023-09-05 17:29 UTC, GThurler commented on controllers/acs_device_info.js
> +          device.wifi_hidden = hidden;
Tem que converter aqui também

2023-09-05 17:29 UTC, GThurler commented on controllers/device_list.js
> +                changes.wifi2.hidden = wifiHidden;
Cuidado que pro GenieACS o valor é um booleano e na base é um inteiro - o `if` acima está correto? Se sim, tem que converter esse valor aqui. Mesmo comentário pro check de 5GHz abaixo

2023-09-05 17:29 UTC, GThurler commented on models/device.js
> +  has_synced_wifi_hidden: Boolean, // temp field to avoid creating a migration
Não é melhor ter um `default: false`? Pra evitar aumentar o nosso legado de `undefined`s
Outra coisa, você tem que setar esse valor durante o `createRegistry`, de forma que essa informação já esteja setada na base para novos cadastros. Se o dispositivo já foi criado após essa feature, na base já vai estar true ou false:
- True se ele tem permissão de leitura das infos de wi-fi escondido
- False se não tiver permissão de leitura ou o dado veio inválido

2023-09-05 17:29 UTC, GThurler commented on public/javascripts/table_anim.js
> +    let userNotAllowed = (!isSuperuser && grantWifiInfo <= 1);
Por que esse `userNotAllowed` ficou aqui em cima se ele só é usado lá embaixo? Talvez fosse bom no mínimo renomear isso aqui pra `userNotAllowedEditWifi`, pra deixar claro que isso aqui só valida a permissão de `grantWifiInfo`

2023-09-05 17:55 UTC, naccaratocarolina commented on controllers/acs_device_info.js
> +          }
Não é código copiado e colado - foi intencional. Isso foi necessário porque a variável `has_synced_wifi_hidden` é utilizada novamente para o wifi5. Se o CPE for dual band, e eu tiver setado device.has_synced_wifi_hidden como true no fluxo do 2.4, o fluxo do 5 vai ser prejudicado.

2023-09-05 17:58 UTC, naccaratocarolina commented on controllers/acs_device_info.js
> +          changes.wifi2.hidden = device.wifi_hidden;
Como assim? O valor já é convertido nessa linha: `let hidden = utilHandlers.convertToBoolean(data.wifi5.hidden.value);`

2023-09-05 18:22 UTC, naccaratocarolina commented on controllers/device_list.js
> +                changes.wifi2.hidden = wifiHidden;
Na base o valor é 0 e 1 mesmo, não bool

2023-09-06 19:01 UTC, GThurler requested changes
Não fiz review dos testes ainda

2023-09-07 14:11 UTC, naccaratocarolina commented on test/unit/update.test.js
> +      describe('Version tests', () => {
Nada mudou nesses códigos. Apenas organizei eles em describes para manter a organização desse arquivo de teste.

2023-09-11 21:02 UTC, GThurler approved these changes

2023-09-11 21:02 UTC, merged