Feature/voip front end
anlix-io/flashman pull request #777
Opened 2023-09-02 00:36 UTC by GThurler

2023-09-11 20:16 UTC, lucasperovani requested changes
Ainda não validei como ficou visualmente aqui na máquina, pelo que vi na sua apresentação parece estar como a gente combinou... Vou ter que mockar um dispositivo para fazer isso. Mas de resto parece estar certinho

2023-09-12 17:26 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +    if (voipProfiles) {
Não tem problema, eu quero filtrar só `undefined`. O código sabe lidar com array vazio - o `reduce` em cima de um array vazio é o próprio array vazio

2023-09-12 17:28 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +    if (voipServices) {
Não tem problema, eu quero filtrar só `undefined`. O código sabe lidar com array vazio - o `reduce` em cima de um array vazio é o próprio array vazio

2023-09-12 17:37 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +        ),
Eu posso colocar isso numa variável antes, mas aí perco o arrow function. A culpa é do Javascript não ter um `enumerate` da vida ou named arguments pra funções. Assim fica mais claro? A outra alternativa é um `for` normal ~~que vai ficar feião porque vou ter que fazer o `map` na mão~~
```suggestion
      // Enumerate array entries so we can iterate on both indexes and values
      this.profileForms = Array.from(voipProfiles.entries()).map(
        function (profileEntry) {
          let profile = profileEntry[1];
          let profileIndex = profileEntry[0];
          return new VoipForm(
            profile,
            devicePermissions.grantVoipPortCount,
            devicePermissions.grantVoipRegions,
            voipProfiles.length > 1,
            deviceIndex,
            profileIndex,
            editable,
            translationFunction,
          );
        }
```

2023-09-12 17:38 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +    if (voipProfiles) {
Não tem problema, eu quero filtrar só `undefined`. O código sabe lidar com array vazio - o `map` em cima de um array vazio é o próprio array vazio

2023-09-12 17:39 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +    );
Mesma sugestão que eu dei no outro comentário - vou marcar esse como resolved porque o ideal é padronizar tudo de acordo com o que resolvermos no outro

2023-09-12 17:42 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +          : `Profile - ${profile.tr069_index}`,
Poderia ser, eu achei desnecessário porque a gente sempre fala "o profile" ao invés de "o perfil", mas sei lá

2023-09-12 17:45 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +    let editable = userCanWrite && deviceCanEditVoip;
Eu vou alterar por padronização com outros trechos do código, mas eu acho que `let` e `const` pra variáveis locais não traz nenhum benefício pra gente - só faz alguém ter que mudar de volta pra `let` quando o caso de uso evoluir e a gente precisar deixar essa condição mais complexa.

Se fosse sei lá, um membro de uma classe que poderia ser manipulado externamente por um desavisado eu concordaria, mas só a gente vai mexer nisso.

2023-09-12 17:46 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +    let userCanWrite = userIsSuperuser || userPermissionLevel > 1;
Mesmo comentário acima, vou alterar

2023-09-12 17:46 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +    let paneId = `#voip-pane-${this.offset}`;
Mesmo comentário acima, vou alterar

2023-09-12 17:46 UTC, GThurler commented on public/javascripts/widgets/voip-tab.js
> +    );
Mesma sugestão que eu dei no outro comentário - vou marcar esse como resolved porque o ideal é padronizar tudo de acordo com o que resolvermos no outro

2023-09-12 17:47 UTC, GThurler commented on public/javascripts/widgets/text-form.js
> +/* eslint require-jsdoc: 0 */
Fui pela jurisprudência dos outros lugares, rsrs

2023-09-12 17:54 UTC, GThurler commented on public/javascripts/widgets/checkbox-row-form.js
> +    );
O problema do `for` é ter que buildar o array na mão, mais uma vez a culpa é do javascript não ter um syntax sugar pra buildar um array de 0 a N, e de um Iterator não ter a função `map`. Um comentário não pode esclarecer isso não?
```suggestion
    // Build an array of checkboxes, replacing the generic text with the appropriate index, and checking if such index is among the ones that start checked
    this.options = Array.from(Array(length).keys()).map(
      (i) => new Checkbox(
        `${baseId}-${i}`,
        optionText.replaceAll('$$', i+1),
        checkedIndexes.indexOf(i) >= 0,
        enabled,
      ),
    );
```

2023-09-12 17:54 UTC, GThurler commented on public/javascripts/table_anim.js
> +          '<i class="fas fa-check fa-lg"></i><span>&nbsp; '+t('Save')+'</span>'+
Senges que pediu

2023-09-12 17:55 UTC, GThurler commented on public/locales/pt/translation.json
> +  "voipProfileParams": "Parâmetros do profile VoIP",
Mesmo comentário que fiz no teu comentário perguntando se "Profile" não deveria estar traduzido lá. Tem que manter a coerência com o que estiver lá

2023-09-12 17:56 UTC, GThurler commented on public/locales/es/translation.json
> +  "associatePhoneLineToPort": "Asociar esta línea telefónica a los siguientes puertos"
No hablo inglés, confiei no google tradutor ¯\\_(ツ)\_/¯

2023-09-14 21:27 UTC, lucasperovani approved these changes

2023-09-15 11:47 UTC, merged