Feature/gx3000
anlix-io/flashman pull request #784
Opened 2023-09-08 18:52 UTC by lucasperovani

- Added WAN mobile status information to be visible to frontend 
- Added mobile status to gx3000.

2023-09-09 00:37 UTC, GThurler requested changes
Não olhei nada dos testes porque não estão passando, não sei o quanto vão ser alterados.

2023-09-09 00:37 UTC, GThurler commented on controllers/external-genieacs/cpe-models/base-model.md
> +| permissions.wan.mobile_status | ❌ | false | Só deve ser true se o CPE possui status da rede móvel na WAN |
Essa flag não existe no código

2023-09-09 00:37 UTC, GThurler commented on public/locales/pt/translation.json
> +  "wanFieldsMustBeInDatabase": "Os campos da WAN devem existir na base do ACS para realizar o cadastro na base do Flashman",
Essa mensagem tinha sido removida pelo Gaspare pois caiu em desuso (of if dela morreu), por que ela voltou?

2023-09-09 00:37 UTC, GThurler commented on public/locales/pt/translation.json
> +  "wanIsOn5GMobileNetwork": "O tráfego da WAN deste CPE está sendo feito por uma rede móvel 5G!"
```suggestion
  "wanIsOn5GMobileNetwork": "Este CPE está se comunicando com a internet através do chip 5G. Lembre-se que as configurações abaixo são da WAN normal dele, e não da conexão móvel."
```

2023-09-09 00:37 UTC, GThurler commented on public/javascripts/table_anim.js
> +          if (grantWanMobileStatusRead === true) {
Se fosse um `=== false` eu até entenderia, mas pra `true` não acha que é meio overkill?

2023-09-09 00:37 UTC, GThurler commented on controllers/acs_device_info.js
> +    data.wan.mobile_status.value
Pode deixar assim, mas pra referência futura acho que não precisa do `.value` no `if`, deixa a função retornar `'UNKNOWN'` se vier undefined ou algo assim. Penso isso só pro caso de algum modelo um dia enviar esse campo de forma booleana, alguém vai cair na pegadinha do `value` vir `false`

2023-09-11 11:48 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +          if (grantWanMobileStatusRead === true) {
Sim, é overkill haha. É para os casos `{}` e `[]`, mas como isso não deveria vir para o front 🤷‍♂️

2023-09-11 11:52 UTC, lucasperovani commented on public/locales/pt/translation.json
> +  "wanIsOn5GMobileNetwork": "O tráfego da WAN deste CPE está sendo feito por uma rede móvel 5G!"
As configurações da WAN permanecem as mesmas, tanto no 5G quanto por cabo. Só o que muda é a flag dizendo se está por cabo ou pela WAN

2023-09-11 15:36 UTC, GThurler approved these changes

2023-09-11 21:09 UTC, merged