Fixed 'wan' and 'wifi' fields no showing…
anlix-io/flashman pull request #797
Opened 2023-09-19 01:30 UTC by cassiohg

…when user restricts return to contain fields inside those fields when issuing an apiv3 device search.

2023-09-25 15:48 UTC, lucasperovani requested changes
Alguns problemas que eu encontrei:
- Quando coloca o `wifi.type` no `fields`, o campo `wan` vem vazio;
- Quando coloca o `wifi.bssid` no `fields`, o campo `wan` vem o `bssid` e o `type`;
- `wan.bytes` está vindo quando pede a `wan` especificamente. Não deveria vir para a rota de `search` porque pode ser um campo grande;
- `sort` não está funcionando para campos dentro de wan e wifi. Isso não é tão problemático, mas acredito que consiga corrigir subistituindo o `sort` pelo campo referente dentro do `wan` ou `wifi`.

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +      } else {
São testados 2 linhas a cima.

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +  }
Coloquei comentário e melhorei os que já tinha.

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +      modelFields = nf.from.constructor !== Array ? [nf.from] : nf.from;
São variáveis auxiliares usadas apenas localizadamente, nas poucas linhas subsequentes, para diminuir a quantidade de caracteres usados por linha. Esse estilo de código é muito comum em programação e serve pra não atrapalhar a legibilidade do código com muitos nomes de referências temporárias descartadas. Mesmo assim, aumentei os nomes das variáveis.

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +      // eslint-disable-next-line guard-for-in
O linter foi configurado, erroneamente, para pedir validação das chaves próprias em loops feitos em qualquer objeto. Como o objeto em questão é um objeto criado a partir de um objeto com prototype vazio, não há nenhuma chave enumerável na cadeia de prototypes dele e o loop passa somente pelas chaves criadas diretamente sobre ele. Portanto, a validação que o linter pede é uma validação inútil, que nunca vai invalidar nenhuma chave. Isso acontece porque usamos objetos no lugar de mapa para guardar dados endereçados por chave, graças a uma facilidade da linguagem.
Pra aprender mais sobre o `for in`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in
Pra aprender melhor sobre como funciona a cadeia de prototype: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +  // eslint-disable-next-line guard-for-in
Ver resposta anteriror sobre linter.

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +    let v = getValueIfNotEmpty(device[from]);
Mais um caso de não encher o código com lindos nomes em referências auxiliares temporárias. Mesmo assim, aumentei o nome dessa variável.

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +    // eslint-disable-next-line guard-for-in
Ver resposta anteriror sobre linter.

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +  // eslint-disable-next-line guard-for-in
Ver resposta anteriror sobre linter.

2023-09-26 19:39 UTC, cassiohg commented on controllers/api/v3.js
> +        // eslint-disable-next-line guard-for-in
Ver resposta anteriror sobre linter.

2023-09-26 19:39 UTC, cassiohg commented
> * Quando coloca o `wifi.type` no `fields`, o campo `wan` vem vazio;

É a melhor coisa a fazer porque o `wifi.type` não existe explicitamente. Ele só existe, quando algum campo do wifi está presente e é necessário que sempre exista nessa condição. Ele é a identificação de um conjunto de campos de wifi. Pela estratégia de busca adotada pelo código, pedindo apenas o `wifi.type` não tem como saber quais `wifi.type` o device tem para retornar. Talvez isso não tenha sido percebido antes porque a seleção de campos não funcionava pros campos de wifi. Se quiser alterar a estratégia de busca então é um outro problema que esse pull request não foi feito pra resolver.

> * Quando coloca o `wifi.bssid` no `fields`, o campo `wan` vem o `bssid` e o `type`;

É necessário retornar o campo `type` quando qualquer campo de wifi é retornado, caso contrário não terá como o usuário saber a qual rádio pertence cada campo de wifi. Isso é uma consequência de como esse novo modelo de wifi foi projetado. Talvez isso nao tenha sido percebido antes porque não a seleção de campos não funcionava pros campos de wifi. Percebe que o usuário não tem como escolher retornar o `bssid` de apenas um rádio pela api? Isso acontece porque a api não oferece uma forma de buscar por condições em elementos dentro de arrays e isso seria necessário perante o novo modelo de dados de wifi.

> * `wan.bytes` está vindo quando pede a `wan` especificamente. Não deveria vir para a rota de `search` porque pode ser um campo grande;

Essa funcionalidade não faz parte do código de `search` e não faz parte do pull request mas dá para mudar fácil.

> * `sort` não está funcionando para campos dentro de wan e wifi. Isso não é tão problemático, mas acredito que consiga corrigir subistituindo o `sort` pelo campo referente dentro do `wan` ou `wifi`.

Já não funcionava antes. Esse pull request não é para mexer no sort. Não é trivial de resolver pros campos do wifi, porque a api nao permite definir qual wifi o sort deve agir sobre.

2023-11-24 16:21 UTC, closed without merging