Feature/mesh vendor sync
anlix-io/flashman pull request #814
Opened 2023-09-27 00:31 UTC by GThurler

- CreateRegistry e agregados ok
- SyncDeviceData e agregados ok
- Ajustes de compatibilidade nas lógicas de mesh v1 e v2 (ignoram mesh vendor)
  - Tanto no front quanto no back
- Testes unitários quebraram por conta das transactions do mongoose
  - Tentei algumas coisas pra mockar as chamadas, sem sucesso
- Ainda sem documentação para acelerar o review
  - Tem que documentar as novas funções E o base-model que ficou faltando do PR de modelagem

2023-09-28 20:42 UTC, lucasperovani commented
Na função `buildTR069Changes`, após o `switch/case` ele ainda deve passar pelo `if` do `populateSSIDObjects`?

2023-09-28 20:43 UTC, lucasperovani commented
Validar os casos na função `validateMeshMode` do arquivoo `mesh.js`

2023-09-29 17:34 UTC, lucasperovani commented
Para mockar as funções adicionadas, deve precisar disso:
```
const mongoose = require('mongoose');

// Mock mongoose
mongoose.startSession = jest.fn().mockResolvedValue({
  startTransaction: () => true,
  endSession: () => true,
  commitTransaction: () => jest.fn().mockResolvedValue(true),
});
```
Isso serve para mockar as funções da sessão e da criação da sessão. Depois é só mockar o Repeater. Para isto, deve ser preciso adicionar entradas e funções nos arquivos: `test/common/models.js`, `test/common/fieldsAndPermissions.js` e `test/common/utils.js`

2023-09-29 17:34 UTC, lucasperovani requested changes
Para mockar as funções adicionadas, deve precisar disso:
```
const mongoose = require('mongoose');

// Mock mongoose
mongoose.startSession = jest.fn().mockResolvedValue({
  startTransaction: () => true,
  endSession: () => true,
  commitTransaction: () => jest.fn().mockResolvedValue(true),
});
```
Isso serve para mockar as funções da sessão e da criação da sessão. Depois é só mockar o Repeater. Para isto, deve ser preciso adicionar entradas e funções nos arquivos: `test/common/models.js`, `test/common/fieldsAndPermissions.js` e `test/common/utils.js`

2023-10-02 17:15 UTC, GThurler commented
> Na função `buildTR069Changes` do arquivoo `mesh.js`, após o `switch/case` ele ainda deve passar pelo `if` do `populateSSIDObjects`?

> Validar os casos na função `validateMeshMode` do arquivoo `mesh.js`

Essas funções nem tem como serem chamadas, mas eu posso adicionar um check lá só por segurança.

2023-10-02 17:22 UTC, GThurler commented on controllers/external-genieacs/cpe-models/huawei-eg8145x6.js
> +  fields.vendor_mesh_repeater.devices.root = meshStaRoot;
Não, vou dar um `slice(0, -1)` pra tirar o ponto

2023-10-02 17:25 UTC, GThurler commented on controllers/external-genieacs/provision.js
> +    }
A flag indica que o campo de IP estará na árvore de hosts, ou seja, `fields.vendor_mesh_repeater.ip` está apontando pra árvore de hosts. Nesse caso, pra relacionar o IP dessa árvore com o registro dos secundários, usamos o MAC como chave primária pra correlação.

Vou adicionar um comentário pra deixar claro que puxamos o MAC pra poder correlacionar o IP com o secundário

2023-10-02 17:27 UTC, GThurler commented on controllers/handlers/acs/mesh_vendor.js
> + * @return {Object} - The value associated with the given field, read from data
Sim, confundi porque em Dart `Object` é o "tipo genérico" que engloba int, string, null, etc

2023-10-02 17:35 UTC, GThurler commented on controllers/handlers/acs/mesh_vendor.js
> +const createMeshRepeater = async function(meshSlave, masterId, session = null) {
O `masterId` sempre vai ser um MAC válido, porque vem direto da collection de `devices`. Se não for, é problema de algum trecho anterior do código - não acho que faz sentido ter uma dupla validação aqui, o trecho anterior é que deveria validar esse tipo de informação. Pro contexto dessa função (não é algo exposto na API ou manipulável pelo front), fica meio redundante incluir isso aqui.

Sobre o `meshSlave`, é a estrutura que foi lida do TR-069 que já foi validada - se o MAC veio errado é um trabalho da `translateMeshData` ignorar o que veio inválido. Talvez a validação que você queira fazer deveria ficar lá, pra descartar secundários com MACs mal-formatados

2023-10-02 17:45 UTC, GThurler commented on controllers/handlers/util.js
> +  return {success: false};
Discordo fortemente, `continue` e `break` no baixo nível **são** gotos, isso é inevitável. Colocar uma sequência de `if/else if/else` enumerando os casos possíveis de combinações das condições fica mais confuso, pois você tem que voltar no `if` para ter o contexto inteiro do que o `else if` encoda.
No exemplo que você deu, a condição explícita do `else if` é `partialKey !== '*' && !current.hasOwnProperty(partialKey)`, só que omite-se a segunda parte por redundância, dificultando a interpretação do código.
Talvez a melhor solução que até facilite a leitura seja inverter a lógica:
```javascript
if (keyPart === '*') {
  return {
    success: true,
    values: utilHandlers.orderNumericGenieKeys(Object.keys(current)),
  };
}
if (!current.hasOwnProperty(keyPart)) {
  break;
}
current = current[keyPart];
```
Desse jeito fica explícito o caso de sucesso e o caso que deve encerrar o `for` imediatamente para acusar erro. Só discordo que `continue` deve ser evitado, é um controle de fluxo importante pra simplificar a lógica :p

2023-10-02 17:48 UTC, GThurler commented on controllers/handlers/acs/mesh_vendor.js
> +      );
Na real não seria necessário, o `success` é mais por preciosismo. O que está faltando é a função retornar um array vazio em `values` caso `success` esteja `false`, pra impedir justamente esse problema

2023-10-02 17:49 UTC, GThurler commented on controllers/handlers/mesh.js
> +      let isVendorMesh = (device.mesh_mode === 10);
Vou repassar os pontos no código onde isso pode acontecer pra adicionar nas projections

2023-10-02 17:51 UTC, GThurler commented on controllers/device_list.js
> +  if (!isVendorMesh && hasSlaves) {
Mas é pra cair no `else` mesmo... O CPE primário de um mesh vendor ainda pode receber updates de firmware

2023-10-02 17:54 UTC, GThurler commented on public/javascripts/table_anim.js
> +          if (!isVendorMesh && isAnlixMeshWifi && hasMeshPermission) {
Pra esse `if` aqui, realmente. Vou tirar

2023-10-02 17:57 UTC, GThurler commented on public/javascripts/table_anim.js
> +          if (grantOpmode && showModeTab) {
Eu quis colocar perto do contexto onde essas variáveis eram todas setadas pra concentrar a lógica. Posso trazer aqui pra baixo, dá no mesmo. A aba só pode aparecer se é firmware ou tem permissão de mesh mesmo, caso contrário você ou vai mostrar uma aba em branco ou mostrar uma opção que não serve para o CPE

2023-10-02 17:58 UTC, GThurler commented on controllers/handlers/acs/mesh_vendor.js
> + */
Repara só que isso aqui é um subconjunto dos campos do model, ele não possui, por exemplo, o `mesh_master`.

2023-10-02 17:59 UTC, GThurler commented on controllers/acs_device_info.js
> +    meshSlavesData = meshVendorHandlers.translateMeshData(cpe, data.meshVendor);
Não tem muito o que validar - é o que a gente recebe do TR-069. No máximo posso ver se é um Object, mas acho isso meio overkill. As funções que vão usar isso pra algo é que deveriam se preocupar com isso, não?

2023-10-02 18:01 UTC, GThurler commented on controllers/acs_device_info.js
> +  let hasSecondaries = false;
TR-069 nunca vai ter secundários Anlix durante o cadastro

2023-10-02 18:03 UTC, GThurler commented on controllers/acs_device_info.js
> +      mesh_slaves: [], // ALWAYS EMPTY - Can't be reliable, use repeaters
E quais linhas são essas? O código já andou com os outros fixes, me ajuda aí. Dificilmente tem que alterar essas linhas, porque o certo é validar se é um mesh vendor ou não antes de sair olhando os slaves (coisa que já está sendo feita ao longo do código)

2023-10-02 18:04 UTC, GThurler commented on controllers/acs_device_info.js
> +    }
Não, mesmo comentário da provision

2023-10-02 18:04 UTC, GThurler commented on controllers/acs_device_info.js
> +  if (!config) return;
Não tinha antes, não vai ter agora, outro PR :)

2023-10-02 18:05 UTC, GThurler commented on controllers/acs_device_info.js
> +    {lan_devices: 0, ap_survey: 0},
Não tinha antes, não vai ter agora. Inclusive antes só tirávamos o `ap_survey`, outro PR :)

2023-10-02 18:05 UTC, GThurler commented on controllers/acs_device_info.js
> +  }
Não tinha antes, não vai ter agora - outro PR :)

2023-10-02 19:26 UTC, GThurler commented on controllers/acs_device_info.js
> +      mesh_slaves: [], // ALWAYS EMPTY - Can't be reliable, use repeaters
Olhei no código, todas estão com um check no mesh_mode. #safe

2023-10-02 21:42 UTC, GThurler commented
A parada do mock do mongoose dos testes não funcionou :(

2023-10-03 17:35 UTC, lucasperovani commented on controllers/handlers/mesh.js
> +      let isVendorMesh = (device.mesh_mode === 10);
Acredito que ainda falte colocar na `deviceProjection` da função `startSchedule`.

2023-10-03 21:41 UTC, GThurler commented
#AgoraVai @lucasperovani

2023-10-04 12:19 UTC, lucasperovani commented on test/unit/acs_device_info.test.js
> +        );
O primeiro `_` poderia se chamar `device` ou algo do tipo. Evitaria de ter que passar um `_` dentro do `Promise.resolve` para algo mais intuitivo e o `__` poderia ficar apenas como `_` já que não está usando ele

2023-10-04 15:01 UTC, GThurler commented on test/unit/acs_device_info.test.js
> +        );
Discordo de leve, o propósito do mock é retornar o primeiro argumento, não importa o que seja passado pra ele - pode ser ou um device ou um array de devices, a depender do contexto. Pro `createRegistry` é sempre um array, mas isso pouco importa, porque a gente só está emulando o comportamento do `create` de sempre retornar o que foi criado na base.

Sobre omitir o segundo argumento, acho ruim porque o código depende de passar o segundo argumento, por mais que para o mock seja irrelevante e que o Javascript permita esse tipo de maracutaia. Até porque um teste mais completo deveria validar se o segundo argumento (não) veio com uma sessão válida.

O que pode fazer pra evitar repetir isso ao longo do código é criar uma função do tipo:
```javascript
const mockDeviceCreation = function() {
  jest.spyOn(DeviceModel, 'create').mockImplementationOnce(
    (_, __) => Promise.resolve(_),
  );
}
```
E então trocar o código acima por:
```suggestion
        mockDeviceCreation();
```

2023-10-04 15:20 UTC, GThurler commented on test/unit/acs_device_info.test.js
> +        );
Pode ser, a gente coloca `arg1` e `arg2`, rsrs

2023-10-04 15:23 UTC, lucasperovani commented on test/unit/acs_device_info.test.js
> +        );
show, vou tentar substituir todos os casos então kkkkk

2023-10-04 17:58 UTC, merged