Adding mesh fields for v5
anlix-io/flashman pull request #819
Opened 2023-10-02 17:33 UTC by naccaratocarolina

2023-10-03 18:18 UTC, lucasperovani requested changes
Acredito que queira adicionar também, ou pelo menos algum deles... (ver todas as `permissions` no `base-model.js`):
```
permissions.features.meshVendor
permissions.meshVendor.repeaterIpFromHosts
permissions.meshVendor.hasRepeaterFirmware
permissions.meshVendor.hasRepeaterHardware
permissions.meshVendor.hasRepeaterUptime
permissions.meshVendor.hasRepeaterBssid
permissions.meshVendor.hasRepeaterChannel
permissions.meshVendor.hasRepeaterWifiEnable
permissions.meshVendor.hasRepeaterStationRSSI
permissions.meshVendor.hasRepeaterStationSNR
permissions.meshVendor.hasRepeaterStationRate
permissions.meshVendor.hasRepeaterStationBand
```

2023-10-05 14:21 UTC, GThurler commented
@naccaratocarolina Lembrando só das alterações pedidas pelo Lucas

2023-10-05 18:38 UTC, GThurler approved these changes

2023-10-05 18:46 UTC, lucasperovani approved these changes

2023-10-05 18:53 UTC, merged