Use Redis for LastContact
anlix-io/flashman pull request #827
Opened 2023-10-04 15:27 UTC by ggbruno

Add Redis Service
Use publishing in redis for lastContact of TR-069

2023-10-04 16:12 UTC, rilpires approved these changes
showw

2023-10-05 15:06 UTC, GThurler requested changes

2023-10-05 15:06 UTC, GThurler commented on redis.js
> +};
https://redis.io/docs/clients/nodejs/
> To check if the client is connected and ready to send commands, use client.isReady, which returns a Boolean.

2023-10-05 15:06 UTC, GThurler commented on models/device.js
> +        redis.publish('last_contact', device._id);
Por que o `if` não dá um `return` pra evitar indentar tudo no `else` e atrapalhar o diff? :)

2023-10-05 20:17 UTC, GThurler approved these changes

2023-10-05 22:05 UTC, merged