Feature/include repeaters in device list result
anlix-io/flashman pull request #828
Opened 2023-10-04 17:28 UTC by cassiohg

2023-10-04 22:51 UTC, GThurler requested changes
Estou adiantando o review que estava com o Lucas por causa do prazo apertado que temos até sexta.

Dada a quantidade de alterações requisitadas, a criticidade desta branch e a pilha de cards que estão em TODO ainda, eu vou ajeitar / refazer essa branch pra dar vazão no que é essencial liberar até sexta, dado que já terminei o PR de ajustes no front.

Vou deixar o PR em aberto pra debater alguns pontos levantados no review, e pra transplantar os pedaços do código e dos testes que podem ser aproveitados, mas eventualmente será fechado para que a nova branch seja mergeada.

2023-10-04 22:51 UTC, GThurler commented on controllers/handlers/mesh.js
> +          .lean().exec();
Esse trecho aqui que deveria estar numa função isolada, de preferência no /handlers/acs/mesh_vendor. Ajudaria também a matar a necessidade do argumento `includeRepeaters` que foi criado.

2023-10-04 22:51 UTC, GThurler commented on controllers/device_list.js
> +          await meshHandlers.enhanceSearchResult(matchedDevices.docs, true));
Adicionar repeaters a essa altura do código _pode_ levar a alguns problemas mais abaixo:
- A ausência do `use_tr069` vai fazer com que o repeater caia no fluxo de Firmware Anlix, levando ele a comparar o model do repeater com o das releases de Flashbox, além de setar `isUpgradeEnabled` em `true`
- `device.status_color` usará a mesma conta que fazemos para Firmware/TR-069 ao invés de fazer uma conta própria
- `device.permissions` sairá com as permissões do Firmware Anlix, pois o modelo não será um dos homologados (não homologamos CPEs usadas somente como secundários do mesh do fabricante)

A própria função análoga à `enhanceSearchResult` poderia setar esses campos, que é o que estava mencionado de forma vaga no card ("Essa nova função deve incluir os dados de secundários do mesh do fabricante de forma análoga ao que era feito para o mesh v1 e v2") - poderia ter explicitado quais campos poderiam dar problema no card

Idealmente os repeaters seriam adicionados após todo esse processamento dos `devices` encontrados, para evitar um monte de `if`s em código legado que já está um pouco embolado.

2023-10-05 01:56 UTC, cassiohg commented on controllers/device_list.js
> +  .then((array) => array[0].concat(array[1]))
Posso remover.

2023-10-05 02:37 UTC, cassiohg commented on controllers/handlers/mesh.js
> +meshHandlers.enhanceSearchResult = async function(result, includeRepeaters) {
O search do front end retorna os mesh vendor slaves no mesmo resultado que contem devices em mesh slaves anlix. Esse função é o ponto ideal pra juntar os dois. O tratamento `device.mesh_mode === 10` está presente sim pra identificar quando o device faz parte de um mesh vendor. Não é necessário adicionar mais um tratametno pra devices que fazem aprte de um mesh anlix porque já existe um que não é atrapalhado por nada que foi adicionado.

2023-10-05 02:37 UTC, cassiohg commented on controllers/handlers/mesh.js
> +          .lean().exec();
É mais eficiente tratar nesse ponto do código, que é um momento em que o código já pega um mesh master. Criar outra função apenas pra fazer isso, mantendo essa como está, vai desperdiçar a oportunidade que essa função já cria. Não há a nada a ganhar criando mais um loop sobre os devices retornados da base: pedaço de lógica replicada, mais um O(n), o loop que rodar após o outro vai ter que passar por um n maior.
Mais ideal ainda seria tudo que vem após o `enhanceSearchResult()` ser feito num único loop junto ao que tem dentro do `enhanceSearchResult()`, ao inves de fazer um loop pra cada lógica.

2023-10-05 02:37 UTC, cassiohg commented on controllers/device_list.js
> +          await meshHandlers.enhanceSearchResult(matchedDevices.docs, true));
Eu levei a seguinte frase do card em consideração:
>o front espera receber os dados do mesmo jeito, não importa se é mesh Anlix ou vendor

Por isso fiz questão de manter todo o tratamento que vem após o `enhanceSearchResult()`. O que ainda é reforçado por:
>incluir os dados de secundários do mesh do fabricante de forma análoga ao que era feito para o mesh v1 e v2"

Como não há necessidade de fazer 3 loops sobre os mesmos dados não gerei um terceiro. Porém realmente não me toquei que os repeaters não tem o campo use_tr069 apesar de serem tr069. Não é dificil fazer eles entrarem no `if` que trata tr069.

2023-10-05 17:24 UTC, closed without merging