Added apiv3 entry to return mesh vendor master ids with pagination.
anlix-io/flashman pull request #833
Opened 2023-10-04 23:25 UTC by cassiohg

Added apiv3 entry to return mesh vendor master ids with pagination.
Added tests for said api entry.

2023-10-05 19:14 UTC, lucasperovani commented
Faltou a documentação da API para ser usada no swagger

2023-10-05 19:47 UTC, lucasperovani requested changes
Adicionar a documentação da API no swgger

2023-10-05 19:47 UTC, lucasperovani commented on controllers/api/v3.js
> +  ]).catch((e) => e);
`DeviceModel.paginate` já faz isso tudo para você

2023-10-05 19:47 UTC, lucasperovani commented on controllers/api/v3.js
> +  }
É preferível usar um `try/catch` e substituir o `console.log` por um `console.error`

2023-10-05 19:47 UTC, lucasperovani commented on controllers/api/v3.js
> +  }
Acredito que esse cálculo não será necessário com o `DeviceModel.paginate`

2023-10-05 19:47 UTC, lucasperovani commented on public/locales/en/translation.json
> +  "pageNotFound": "Page not found ({{errorline}})",
Acredito que não será necessário caso use `DeviceModel.paginate` na tua função

2023-10-05 19:47 UTC, lucasperovani commented on routes/api/v3.js
> +router.get('/device/search/mesh-vendor', apiController.getVendorMeshDevices);
Jogar para cima do search pois esse endpoint tem precedência ao endpoint do search genérico

2023-10-05 19:47 UTC, lucasperovani commented on test/unit/api/v3.test.js
> +  describe.only('Return vendor mesh tests', () => {
Remover o `only`

2023-10-05 19:47 UTC, lucasperovani commented on test/unit/api/v3.test.js
> +    test.only.each([
Remover o `only`

2023-10-05 19:47 UTC, lucasperovani commented on test/unit/api/v3.test.js
> +    });
Testar um de cada vez, já que não se sabe qual está dando erro e qual está deixando passar

2023-10-05 19:47 UTC, lucasperovani commented on test/unit/api/v3.test.js
> +    });
Page not found, mas está testando o `pageLimit` com um valor superior ao permitido

2023-10-05 19:47 UTC, lucasperovani commented on controllers/api/v3.js
> +    });
Não retornar o `devices` como um array vazio foge do padrão utilizado nos outros endpoints. O array é retornado para garantir caso o usuário tente ler o array nesses casos de erro. Se precisar habilitar o swagger para ver como que são os endpoints, o que retornam e como funcionam, eu te ajudo com isso Cassio

2023-10-05 19:47 UTC, lucasperovani commented on test/unit/api/v3.test.js
> +      const macs = ['a', 'b', 'c', 'd', 'e', 'f', 'g'];
`macs` poderia usar MACs válidos como `AA:AA:AA:AA:AA:AA` e `BB:BB:BB:BB:BB:BB`

2023-10-05 23:04 UTC, cassiohg commented on controllers/api/v3.js
> +
A função `validateRequest` sempre vai retornar bem sucedida pra qualquer requisição repassada do express para `getVendorMeshDevices`. Acaba não sendo útil nesse caso.

2023-10-05 23:05 UTC, cassiohg commented on controllers/api/v3.js
> +    Math.min(parseInt(req.params.pageLimit), MAX_PAGE_SIZE) : MAX_PAGE_SIZE;
A validação está feita. Irei mantê-las. Coloquei os valores padrão no caso de invalidos. O que significa que não existe mais erro pra valores inválidos.

2023-10-05 23:05 UTC, cassiohg commented on controllers/api/v3.js
> +  ]).catch((e) => e);
E faz outras coisas que não são necessária. Esse código é mais limpo do que o pacote importado.

2023-10-05 23:05 UTC, cassiohg commented on controllers/api/v3.js
> +  }
Melhor deixar o `console.error` para os erros não tratados. Esse `console.log` é só um aviso para quem for debugar o código.
É prefirível não criar identação à toa e não criar subblocos à toa, a fim de beneficiar a legibilidade.

2023-10-05 23:05 UTC, cassiohg commented on controllers/api/v3.js
> +  }
É um calculo muito simples pra justificar executar o pacote inteiro.

2023-10-05 23:05 UTC, cassiohg commented on test/unit/api/v3.test.js
> +    test.only.each([
Bem visto.

2023-10-05 23:05 UTC, cassiohg commented on test/unit/api/v3.test.js
> +    });
Esse código testa um de cada vez. O jest cria uma nova entrada pra cada teste no dashboard final onde é possivel ver qual está dando erro e qual está passando. Mas agora ele não vai mas ser necessário porque valores invalidos vão ser ignorados, como pedido a cima.

2023-10-05 23:05 UTC, cassiohg commented on test/unit/api/v3.test.js
> +    });
Pela que foi pedido, o valor superior ao permitido de `pageLimit` faz o código assumir um valor default. Esse valor foi colocado no teste pra justamente expor essa funcionalidade.

2023-10-05 23:05 UTC, cassiohg commented on controllers/api/v3.js
> +    });
Adicionei.

2023-10-05 23:05 UTC, cassiohg commented on test/unit/api/v3.test.js
> +      const macs = ['a', 'b', 'c', 'd', 'e', 'f', 'g'];
Não faz a menor diferença.

2023-10-05 23:05 UTC, cassiohg commented
Adicionei a documentação da API no swagger.

2023-10-10 17:10 UTC, GThurler commented on controllers/api/v3.js
> +    Math.min(parseInt(req.params.pageLimit), MAX_PAGE_SIZE) : MAX_PAGE_SIZE;
O problema que tem atualmente é que você não responde erro se as informações vieram inválidas:
- Se `page` ou `pageLimit` estão ausentes de `query`: usar valores default (ok)
- Se `page` ou `pageLimit` estão presentes e são válidos: usar os valores recebidos (ok)
- Se `page` ou `pageLimit` estão presentes e são inválidos: retornar erro pro usuário (hoje ele assume o default ao invés de avisar ao usuário do erro)

2023-10-10 17:10 UTC, cassiohg commented on controllers/api/v3.js
> +
`validateRequest` não checa os argumentos, apenas checa se o objeto que guarda argumentos está presente no request. Mas o express sempre coloca esse objeto, apenas deixa vazio quando não tem argumentos. Na verdade, a única coisa que o `validateRequest` faz de útil é checar presença do body e checar que o body é um objeto. Acho que o middleware `body-parser` já faz algo quanto a isso. Não lembro o que o `body-parser` faz quando o body não é parseavel.

2023-10-10 17:23 UTC, GThurler commented on controllers/api/v3.js
> +  ]).catch((e) => e);
Todo o código do Flashman que precisa de paginação usa a chamada de `paginate`. Só porque o pacote faz um monte de coisa, não quer dizer que seja menos eficiente ou que não deveria ser usado. Discordo fortemente sobre o código ser mais limpo - só tem menos linhas, a alternativa deixa muito mais claro o que está sendo feito sem ter que parsear ou dar manutenção em lógica:
```suggestion
  const paginateOptions = {
    page: page,
    limit: pageLimit,
    projection: {_id: 1},
    lean: true,
  };
  const ret = await Promise.all([ // Executing queries concurrently.
    // Querying for vendor mesh masters and returning only the ids.
    DeviceModel.paginate(query, paginateOptions).exec(),
    // Getting amount of documents that could be returned.
    DeviceModel.countDocuments(query),
  ]).catch((e) => e);
```

2023-10-10 17:26 UTC, GThurler commented on controllers/api/v3.js
> +  }
Todo o Flashman está (aos poucos) padronizando logs de erro no `console.error`, para acompanhamento de logs de erro no monitoramento. Mesmo sendo um erro tratado, o fato de ter ocorrido um erro ainda é relevante, e misturar com informações não críticas do `console.log` atrapalha a depuração, pelo menos até todos os pontos do código serem ajustados

2023-10-10 17:39 UTC, GThurler commented on controllers/api/v3.js
> +  }
Sobre questões de indentação, um `if (error)` fica tão indentado quanto um `try/catch` - exatamente um nível de indentação. O código do jeito que está hoje inclusive não funciona, o `await Promise.all(...)` vai estourar um `UnhandledPromiseRejection`. Recomendo ter um `.catch()` seguido de uma validação de erro:
```javascript
const ret = await Promise.all([f1(), f2()]).catch((err) => {
  console.error('Error querying devices for function foo');
  return [null, null];
});
const [devices, count] = ret; // Assigning returns from all promises.
if (!devices) {
  return res.status(500).json({});
}
```

2023-10-10 17:42 UTC, GThurler commented on controllers/api/v3.js
> +  }
Mesmo comentário que fiz acima, o `paginate` é usado em todos os lugares do Flashman, e não é porque é muito simples que a gente vai deixar de usar. A gente vai ter que replicar esse cálculo em todos os lugares do Flashman que dependem de paginação? Vamos isolar então esse cálculo em um módulo nosso? Por que fazer isso tudo se já existe um pacote que faz justamente isso pra gente?

2023-10-10 17:47 UTC, GThurler commented on routes/api/v3.js
> +router.get('/device/search/mesh-vendor', apiController.getVendorMeshDevices);
O match do express é exato, não vai fazer diferença nesse caso aqui. O que daria problema seria se o nosso endpoint de `search` fosse, por exemplo: `/device/search/:something`

2023-10-10 17:51 UTC, GThurler commented on test/unit/api/v3.test.js
> +      const macs = ['a', 'b', 'c', 'd', 'e', 'f', 'g'];
Fica meio ilógico mesmo, por mais que não faça diferença. Talvez só mudar o nome da variável, sei lá

2023-10-11 03:14 UTC, cassiohg commented on controllers/api/v3.js
> +    Math.min(parseInt(req.params.pageLimit), MAX_PAGE_SIZE) : MAX_PAGE_SIZE;
Eu tinha feito ele retornar erro quando tivesse valor inválido mas eu entendi que era pra colocar valor default quando fosse inválido. Voltei a retornar erro.

2023-10-11 03:14 UTC, cassiohg commented on controllers/api/v3.js
> +  ]).catch((e) => e);
Coloquei o paginate.

2023-10-11 03:14 UTC, cassiohg commented on controllers/api/v3.js
> +  }
Não haviam me avisado que era um padrão novo escrever os erros tratados no `console.error`. Troquei para `console.error`.
O try-catch cria um bloco próprio onde o código a ser testado é colocado. Como é um novo bloco, é mais uma identação. Isso ainda faz com que todas os retornos de função chamadas dentro do bloco, que precisam ser usado fora do bloco precisem ter referências pre instanciadas antes do bloco.
O `Promise.all` já tinha `catch`, portanto não iria estourar nenhum `UnhandledPromiseRejection`. O tratamento do erro é justamente a parte do código onde esses comentários estão indo.

2023-10-11 03:14 UTC, cassiohg commented on controllers/api/v3.js
> +  }
Coloquei o paginate.

2023-10-13 18:19 UTC, lucasperovani approved these changes

2023-10-13 18:19 UTC, merged