Feature/removing repeaters
anlix-io/flashman pull request #840
Opened 2023-10-06 19:02 UTC by cassiohg

2023-10-09 16:46 UTC, lucasperovani requested changes
Tem que utilizar `transactions` para só deletar os repeaters caso consiga deletar o device. Se um deles falhar, toda a operação precisa ser cancelada. Se quiser verificar o uso da `transaction` pode verificar a função `createRegistry`.

2023-10-09 18:27 UTC, cassiohg commented
Coloquei pra utilizar e também fiz a remoção legada utilizar transactions.

2023-10-10 17:50 UTC, lucasperovani commented on controllers/handlers/devices.js
> +  if (device.mesh_slaves && device.mesh_slaves.length > 0) {
Deixar a lógica anterior. Pode haver algum caso estranho que venha com `mesh_mode` igual a 10 e com o `mesh_slaves`.

2023-10-10 17:50 UTC, lucasperovani commented on controllers/handlers/devices.js
> +    await meshMasterReg.save({session});
Usar a sessão ao dar o `find` no device, e não durante o save até mesmo para ter apenas em um ponto e não haver necessidade de código duplicado. Não remover o `try/catch` que já estava.

2023-10-11 00:13 UTC, cassiohg commented on test/unit/audit.test.js
> +
Importar o arquivo `test/common/utils.js` causa conflitos dentro desse arquivo.

2023-10-11 00:13 UTC, cassiohg commented on test/black-box/device_list.test.js
> +
Adicionei um count de repeaters.
Criar testes que falham só faria sentido se pudessemos usar o banco de dados dentro dos testes unitários para podermos mockar alguma chamada para forçarmos uma falha sem alterar o código final. Mas isso seria um outro ambiente de teste que não utilizamos.

2023-10-11 00:13 UTC, cassiohg commented on controllers/handlers/devices.js
> +  if (device.mesh_slaves && device.mesh_slaves.length > 0) {
O `mesh_mode` não deve interferir na lógica de impedir uma remoção de device que tenha `mesh_slaves`. A lógica anterior permitia um `device` com `mesh_mode` igual a 10 e que também tivesse `mesh_salves` ser removido.

2023-10-11 00:13 UTC, cassiohg commented on controllers/handlers/devices.js
> +    await meshMasterReg.save({session});
Usar a sessão no `find` não é importante, mas adicionei mesmo assim, mas a sessão do `save` é necessária, portanto mastive. Recoloquei o try-catch.

2023-10-11 00:13 UTC, cassiohg commented on controllers/handlers/devices.js
>      return false;
Adicionei.

2023-10-11 00:13 UTC, cassiohg commented on controllers/handlers/devices.js
> +    await RepeaterModel.deleteMany({mesh_master: device._id}, {session}).exec();
Coloquei `catch` nessa chamada.

2023-10-13 21:52 UTC, lucasperovani approved these changes

2023-10-13 21:52 UTC, merged