Feature/api mesh repeaters from device
anlix-io/flashman pull request #841
Opened 2023-10-06 21:00 UTC by lucasperovani

Added route to return all repeaters from a device, given its mac address

2023-10-06 21:02 UTC, lucasperovani commented
@GThurler No card está escrito para adicionar informações do device, acha que é necessário? E quais informações seriam essas?
Deveríamos usar o paginate para essa rota?

2023-10-10 22:31 UTC, GThurler requested changes

2023-10-10 22:31 UTC, GThurler commented on controllers/api/v3.js
> +    );
```suggestion
    const masterId = request.params['mac'];
    [repeaters, device] = await Promise.all([
      RepeaterModel.find({mesh_master: masterId}).lean(),
      DeviceModel.findById(masterId, {mesh_mode: true}).lean(),
    ]);
```
- Projections sempre incluem o `_id` por default, pode deixar lá por clareza, só vai usar espaço
- Ter as queries dentro do `Promise.all` pra mim faz mais sentido, mas se for pra deixar fora, o `lean` tem que ir junto - não faz sentido separa-los
- `findById` vs `findOne` economiza um bom espaço também

2023-10-10 22:31 UTC, GThurler commented on controllers/api/v3.js
> +    return response.status(422).json({
- 422 deveria ser retornado se o CPE não possui suporte ao modo mesh vendor pelo Flashman
- `!repeaters` é erro 500, deu algo errado na query
- `repeaters.length === 0` é 200, a ausência de repeaters não é um erro

2023-10-16 15:13 UTC, GThurler requested changes

2023-10-16 15:13 UTC, GThurler commented on controllers/api/v3.js
> +  console.log(cpeInstance);
`console.log` vai pra produção?

2023-10-16 15:13 UTC, GThurler commented on controllers/api/v3.js
> +  }
Esse check não é necessário, `[].map(...)` é igual a lista vazia

2023-10-16 21:15 UTC, GThurler approved these changes

2023-10-16 21:43 UTC, merged