Sistema de transactions para tasks ao NBI
anlix-io/flashman pull request #852
Opened 2023-10-11 17:50 UTC by ggbruno

2023-10-17 14:14 UTC, lucasperovani requested changes
Seria legal ter os seguintes pontos:
- Testes para validar que caso alguém tente enviar um commit sem ter task, ou um abort caso não tenha tasks, ou verificar se de fato consegue guardar as tasks, ler e depois executá-las (esse último talvez numa próxima branch quando a gente habilitar as transactions nos endpoints);
- JSDoc nas funções criadas do `anlix-redis-client.js`;
- Se os provedores poderão usar esses comandos, deveria ter a documentação do swagger;
- Ter algum campo para guardar se é `deleteObject`, `addObject` ou `setParameterValues`.

2023-10-17 14:14 UTC, lucasperovani commented on controllers/api/v3.js
> +        };
Um sync pode chegar entre o envio das tasks e o commit, talvez o `data.old` não seja de fato o que estava no dispositivo... A não ser que aquela flag de bloqueio das atualizações enquanto tiver uma transaction rodando seja implementada por outro card. O problema disso é que vamos acabar jogando informações importantes fora... Talvez a gente precise alinhar esse ponto melhor...

2023-10-17 15:36 UTC, GThurler commented on controllers/api/v3.js
> +        };
O que tem que prevalecer nesses casos do sync é o que o usuário pediu pra alterar mesmo, no máximo só vai demorar um pouco mais pra sincronizar as alterações do usuário. Inserir um monte de lógica pra impedir um caso raro de bootstrap por exemplo pra mim não faz sentido

2023-10-17 15:36 UTC, GThurler commented on controllers/api/v3.js
> +    console.error(JSON.stringify(task));
JSON.stringify nunca falha, e mesmo assim Gaspare disse que já está dentro dum catch

2023-10-24 17:22 UTC, ggbruno commented on controllers/handlers/transactions.js
> +  }
É possivel disso acontecer. A maneira que foi desenhada permite multiplos usuarios alterando. Por enquanto, não tratamos isso... O ideal é um id de task... Faremos em um card futuro quando for preciso.

2023-10-24 17:30 UTC, ggbruno commented on controllers/handlers/transactions.js
> +        device[key] = data.value;
O sistema foi escrito pensando apenas no setDeviceReg e no modelo atual de dados do device. 
VoIP e MultiWan precisam alterar a função de commit e updateInfo, já que foi criado novas versões de save do Device.

2023-10-25 17:47 UTC, lucasperovani approved these changes

2023-10-25 17:47 UTC, merged