Feature/mesh conn devices
anlix-io/flashman pull request #857
Opened 2023-10-16 17:02 UTC by naccaratocarolina

![image](https://github.com/anlix-io/flashman/assets/41310085/275a3300-6009-4585-9b50-72126bb56298)
![image](https://github.com/anlix-io/flashman/assets/41310085/623b4300-048f-489f-84e5-36368c3a4d61)

2023-10-16 20:42 UTC, lucasperovani requested changes
Abriu PR para a master xD

2023-10-26 20:06 UTC, lucasperovani requested changes

2023-10-26 20:06 UTC, lucasperovani commented on controllers/device_list.js
> +
Isso aqui deveria estar aqui mesmo? xD

2023-10-27 16:46 UTC, naccaratocarolina commented on controllers/device_list.js
> +
Eu mantive pra quem fizer o review testar, porque eu fiz só a parte do front (o back ainda não existe, então vc n conseguiria ver as minhas modificações). Mas você ta certo, isso não deve ir pra development. Se ja tiver testado tudo certin, me avisa que eu apago esse trecho.

2023-10-31 12:49 UTC, lucasperovani commented on controllers/device_list.js
> +
Pode deixar, vou testar aqui e aí eu apago!

2023-10-31 14:38 UTC, lucasperovani requested changes

2023-10-31 14:38 UTC, lucasperovani commented on public/javascripts/show_lan_devices_actions.js
> +    } else {
Imagino que deva mostrar os dispositivos conectados que estão no roteador principal também e não apenas nos repetidores... Então acho que esse `else` não deveria existir e a lógica que está dentro deveria ser passada para cima

2023-10-31 14:38 UTC, lucasperovani commented on public/javascripts/show_lan_devices_actions.js
> +    idx, device, deviceId, hasSlaves, isBridge, upnpSupport, isVendorMesh=false,
`isVendorMesh` não está sendo usado para nada

2023-10-31 14:38 UTC, lucasperovani commented on public/javascripts/show_lan_devices_actions.js
> +    }
Esse `true` provavelmente está gerando os true's na interface. Validar nos pontos que usam essa função se está vindo em branco para evitar de influenciar no cálculo da quantidade de dispositivos
```suggestion
    if (device.is_old && !device.is_blocked) {
      return '';
    }
```

2023-10-31 14:38 UTC, lucasperovani commented on public/javascripts/show_lan_devices_actions.js
> +  const createLanDeviceCard = function(
Seria legal ter um JSDoc para essas funções

2023-10-31 14:38 UTC, lucasperovani commented on public/javascripts/show_lan_devices_actions.js
> +    if (isVendorMesh) {
Se vier com `repeaters` definidos, acredito que possa adicionar os dropdowns sem problema porque isso está vindo do backend. Talvez não haja necessidade desse `if`

2023-10-31 14:38 UTC, lucasperovani commented on public/javascripts/show_lan_devices_actions.js
> +              $('<i>').addClass('fas fa-chevron-down pr-2')
Acredito que a lógica do `chevron` esteja ao contrário. Quando está aberto o dropdown, o `chevron` deve estar virado para cima e azul. Acredito que ficaria legal se os dropdowns começassem fechados

2023-11-13 20:53 UTC, naccaratocarolina commented on public/javascripts/show_lan_devices_actions.js
> +    if (isVendorMesh) {
Acabei mantendo o isVendorMesh que indica se o dispositivo está no mesh vendor (agora a variavel é usada de verdade). Tive essa preocupação porque os fluxos de mesh são mutuamente exclusivos.

2023-11-21 17:48 UTC, closed without merging

2023-11-21 17:48 UTC, GThurler commented
#916 já contém estas alterações, e é necessário para o bom funcionamento da feature deste PR. Sendo assim, vamos mergear apenas #916, ao invés de fazer em 2 momentos.