Feature/multiwan csv
anlix-io/flashman pull request #865
Opened 2023-10-19 18:59 UTC by naccaratocarolina

2023-10-27 15:16 UTC, lucasperovani requested changes

2023-10-27 15:16 UTC, lucasperovani commented on controllers/device_list.js
> +        device[rowId] = wan.connection_type;
Não acho legal as chaves do objeto ter espaços, mas okay, funciona kkkk

2023-10-27 15:16 UTC, lucasperovani commented on controllers/device_list.js
> +        }
Tomar cuidado com o outro `map` (Linhas 5355 ~ 5364). Talvez tenha que apagar aquele e colocar aqui quando fizer a conversão do firmware. Teria que fazer a conversão para `'Yes'` e `'No'` aqui também

2023-10-30 20:34 UTC, naccaratocarolina commented on controllers/device_list.js
> +        device[rowId] = wan.connection_type;
VocÊ acha que eu devo substituir o espaço pelo o que? _?

2023-11-04 19:05 UTC, naccaratocarolina commented
Lucas, modificações finais realizadas. Pode finalizar o review. @lucasperovani

2023-11-07 14:07 UTC, lucasperovani approved these changes

2023-11-07 14:08 UTC, lucasperovani commented
Parabéns Carol, ficou top!

2023-11-07 14:13 UTC, merged