Feature/real multiwan sync
anlix-io/flashman pull request #869
Opened 2023-10-23 23:16 UTC by GThurler

- Sem documentação (por enquanto)
- Testes todos quebrados (wont fix, alguém me ajuda :cry:)

2023-10-26 19:03 UTC, ggbruno requested changes

2023-10-26 19:34 UTC, GThurler commented on controllers/handlers/acs/wan.js
> +) {
O problema é que eu tenho que recalcular essas 2 funções, fiz isso puramente pra não ter que executá-las múltiplas vezes para um mesmo escopo. Pode alterar, mas sei lá se vale a pena

2023-10-26 19:37 UTC, GThurler commented on controllers/handlers/acs/wan.js
> +    }
Deixei assim pra minimizar o diff de lógica lá onde o upstatus é manipulado. Poderia entrar sim, dado que o comentário feito acima seja seguido (hoje só com o field e permission não tem a função). Mas de qualquer forma, concordo que a responsabilidade de conversão deveria ser do handler da WAN, só endereçar o ponto do field e permission mesmo

2023-10-26 19:39 UTC, GThurler commented on controllers/handlers/acs/wan.js
> +acsWanHandler.mustRebootFromChanges = async function(wanChanges) {
Poderia passar o permission, não o CPE. Na real real, a flag de `mustReboot` do CPE que deveria ser uma função, pode ser que tenha CPE que só reboote se trocar o PPP, outra só se trocar VLAN, etc. Mas dá pra passar sim

2023-10-30 22:17 UTC, ggbruno approved these changes

2023-10-30 22:45 UTC, merged