Feature/flashify adapter iteration
anlix-io/flashman pull request #873
Opened 2023-10-26 14:07 UTC by danielatk

New models:
- Zyxel PX3221-T1

Features:
- adding port mapping permission
- adding hasWifi permission
- adding band5_160 permission
- adding dhcpUptime permission
- adding hasUptimeField permission

Fixes:
- fixing dnsServersWrite permission
- fixing voip regions permission

2023-10-27 17:27 UTC, GThurler requested changes
Por que sair mudando esse monte de coisa sem o Romeu aqui? Isso tudo foi necessário pro Zyxel? Algumas dessas decisões NÃO PODEM partir de uma pessoa sozinha assim, especialmente mudanças de comentários... Pode gerar um problema de comunicação imenso no futuro.

2023-10-27 17:27 UTC, GThurler commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    permissions.features.meshCable = false; // Not tested (disabling by default)
Mesh cable funciona de graça pra todo mundo, não tem nem o que testar - pode deixar liberado pra todo mundo

2023-10-27 17:27 UTC, GThurler commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // permissions.features.meshWifi = false; // Not tested
Discordo das alterações - WONT-DO está correto, nós não vamos mais homologar mesh wifi

2023-10-27 17:27 UTC, GThurler commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // permissions.features.wlanAccessControl = false; // Not tested
Se comentar assim ele só pega o do base-model, certo?

2023-10-27 17:27 UTC, GThurler commented on controllers/external-genieacs/cpe-models/flashify-model.js
> -    // I hate that it doesnt comes as a single field 😤
Que absurdo, apagou o comentário de graça

2023-10-27 17:27 UTC, GThurler commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // permissions.mesh.setEncryptionForCable = false; // Not tested
Tudo de mesh é WONTDO

2023-10-27 17:27 UTC, GThurler commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    permissions.voip.regions = (rfev('voipRegions', !hasVoip) || '').split(',');
Cuidado que split NUNCA GERA uma lista vazia nesse caso:
```javascript
let a = ''.split(','); // ['']
```

2023-10-27 17:27 UTC, GThurler commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // permissions.stavixXMLConfig.webCredentials = false; // Not tested
Campos de XML nunca serão homologados mais, gambiarra legado - WONTDO

2023-10-27 19:04 UTC, danielatk commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    // permissions.features.wlanAccessControl = false; // Not tested
Sim, mas no base-model tão todos como false. Pra mim tinha que tirar esse fallback, não acho que faça sentido, mas até lá queria deixar padronizado que as permissões que a gente não fez e que o valor do base-model está ok a gente deixa asism. Tá uma mistura de override e comentários.

2023-10-27 19:04 UTC, danielatk commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +    permissions.voip.regions = (rfev('voipRegions', !hasVoip) || '').split(',');
Importante!

2023-10-30 21:54 UTC, GThurler approved these changes

2023-10-31 19:28 UTC, merged