Feature/apiv3 new multi wan model
anlix-io/flashman pull request #883
Opened 2023-11-01 03:14 UTC by cassiohg

Did not touch user projection in device search not applying projection to wifi and wans arrays using the new apiv3 model fields.

2023-11-09 14:54 UTC, lucasperovani requested changes
Uma última observação é que a rota de search não está fazendo a tradução para a multiwan, pelo menos para firmware o campo `wans` veio em branco

2023-11-10 22:01 UTC, cassiohg commented on controllers/api/v3.js
> +        mask: 'wan_ipv4_mask',
Botei.

2023-11-10 22:01 UTC, cassiohg commented on controllers/api/v3.js
> +            {case: {'$eq': ['$ipv6_enabled', 2]}, then: 'unknown'},
Feito.

2023-11-10 22:01 UTC, cassiohg commented on controllers/api/v3.js
> +      }
Nossa, eu botei na minha cabeça que essa parte do código tinha a ver com a projeção. Mas como é filtro de busca, o problema é muito maior. Não tem como eu pedir pro banco filtrar documentos por campos que só serão construidos após o retorno. Portanto, os campos que não são meramente troca de nome do campo, não tem como pedir pro banco filtrar.
Eu to pensando ainda como eu vou fazer isso. Vai ficar complexo e com uma busca impossivel de otimizar com indices.

2023-11-10 22:01 UTC, cassiohg commented on controllers/api/v3.js
> +      _id: 'firmware',
Esqueci de mudar pra ficar com `wan_ppp_1` ou `wan_ip_1` como vc tinha feito num review anterior.

2023-11-10 22:02 UTC, cassiohg commented on test/black-box/v3.test.js
> +      test.only('Get firmware WANs by search', async () => {
Sempre esqueço... Já mudei.

2023-11-10 22:02 UTC, cassiohg commented on docs/api/v3/search_responses_schemas.yaml
> +                      example: 'ethernet'
Desculpa, apaguei sem ler. Eu apaguei o array de wans todo e refiz do zero, mas essa sua descrição deu deveria ter montida. Coloquei de volta.

2023-11-10 22:02 UTC, cassiohg commented on docs/api/v3/search_responses_schemas.yaml
> +                      description: Which services are bound to this WAN interface.
Botei em 80.

2023-11-10 22:02 UTC, cassiohg commented on docs/api/v3/get_device_responses_schemas.yaml
> +                    example: 'ethernet'
Tipos de que?

2023-11-10 22:02 UTC, cassiohg commented on controllers/api/v3.js
> +            {'$or': ['$wan_ipv6', '$default_gateway_v6']},
Juarava que string vazia era false. Pelo jeito isso não é executado dentro do javascript. Usei `$gt: ['$key', '']`.

2023-11-13 12:02 UTC, lucasperovani commented on docs/api/v3/get_device_responses_schemas.yaml
> +                    example: 'ethernet'
O mesmo do `search_responses_schemas.yaml`, que o `connection_type` possuia os tipos de conexão (PPPoE e DHCP) explicando

2023-11-13 12:51 UTC, lucasperovani commented on controllers/api/v3.js
> +      }
Eu acredito que você consiga montar as queries com um `$or` entre os parâmetros. Você verifica o modelo antigo e novo ao mesmo tempo.
Quanto ao `wans.enable`, eu acredito que você consiga verificar algo do tipo: se for firmware, ou se for tr-069 (sem `wans` ou com `wans` vazia), ou tr069 com o `wans` preenchido e o campo `enable` em `true`

2023-11-13 15:37 UTC, cassiohg commented on controllers/api/v3.js
> +      }
Os CPEs tr069 foram migrados pro modelo novo, segundo o gaspare.
Não é tão simples criar queries pra todos os campos que não existam. Porque tem campos passaram a ser combinação de campos, e se a pessoa coloca um parametro pra esse tipo de campo, precisaria traduzir o valor passado pro formato antigo em cada campo separado.

2023-11-13 15:38 UTC, cassiohg commented on docs/api/v3/get_device_responses_schemas.yaml
> +                    example: 'ethernet'
Acho que vc criou 2 comentários parecidos pra mesma coisa.

2023-11-14 13:11 UTC, lucasperovani commented on docs/api/v3/get_device_responses_schemas.yaml
> +                    example: 'ethernet'
Isso, é que eu encontrei a mesma modificação em 2 arquivos diferentes. Por isso criei 2 comentários, só para lembrar mesmo. Porque nesse arquivo aconteceu o mesmo detalhe do outro

2023-11-14 19:59 UTC, cassiohg commented
> Uma última observação é que a rota de search não está fazendo a tradução para a multiwan, pelo menos para firmware o campo `wans` veio em branco

Vê se agora voltou a mostrar.

2023-11-27 15:31 UTC, lucasperovani commented on controllers/api/v3.js
>    return [{
Essa função está recebendo o `device` sem os campos da conversão para a rota de search e com o filtro só para `wans` por exemplo. Talvez tenha que adicionar esses campos junto do `querySetup['fields']` na função `apiController.search`

2023-11-27 15:31 UTC, lucasperovani commented on controllers/api/v3.js
> +    query: (value) => value.$eq === [] ? {'use_tr069': false} : undefined},
`value.$eq === []` sempre retorna `false`. Essa deveria ser a funcionalidade mesmo?

2023-11-27 18:35 UTC, cassiohg commented on controllers/api/v3.js
> +    query: (value) => value.$eq === false ? {'use_tr069': false} : undefined},
São muito. Se não, ele não vai retornar nenhum device firmware, porque o device firmware não tem esses campos.

2023-11-27 18:35 UTC, cassiohg commented on controllers/api/v3.js
>      mtu: device.wan_mtu,
Nem sei como isso saiu. Coloquei de volta

2023-11-27 18:37 UTC, cassiohg commented on docs/api/v3/search_responses_schemas.yaml
> +                      example: 'ethernet'
Coloquei.

2023-11-27 18:37 UTC, cassiohg commented on docs/api/v3/get_device_responses_schemas.yaml
> +
Coloquei.

2023-11-27 18:37 UTC, cassiohg commented on docs/api/v3/get_device_responses_schemas.yaml
> +                    description: The nature of the IP connection.
Coloquei

2023-11-27 18:40 UTC, cassiohg commented on controllers/api/v3.js
>    return [{
Isso é um problema que o thurler pediu pra não resolver nesse pull request. Pra isso foi feito outro pull request: https://github.com/anlix-io/flashman/pull/929

2023-11-27 18:45 UTC, cassiohg commented on controllers/api/v3.js
> +    query: (value) => value.$eq === [] ? {'use_tr069': false} : undefined},
Se o usuário quiser qualquer valor de DNS pra ipv6, os firmwares não vão poder retornar nada. Essa linha entrou aí porque eu fiz todas as querries traduzidas retornarem firmwares pro unico valor possível desses campos que não existem na firmware. Nesse caso é melhor mesmo retornar `undefined` sempre.

2023-11-29 12:00 UTC, lucasperovani commented on controllers/api/v3.js
>    return [{
Ahh tranquilo então!

2023-11-29 12:03 UTC, lucasperovani commented on controllers/api/v3.js
> +    query: (value) => value.$eq === false ? {'use_tr069': false} : undefined},
Sim, eu entendo, é que na query vai ter um monte de `{'use_tr069': false}` repetido, não? Não sei se seria complicado de só permitir que apenas uma dessas queries entre, o que acha?

2023-11-29 13:26 UTC, lucasperovani approved these changes

2023-11-29 13:46 UTC, merged