Feature/anlixid sign in
anlix-io/flashman pull request #898
Opened 2023-11-08 19:56 UTC by rilpires

Falta os hints pro frontend não permitir alterar nome de usuário que é remoto
E talvez um tooltip que explique que a senha alterável pelo front é a senha do basic auth...

2023-11-08 22:39 UTC, rilpires commented
Duas mudanças que fiz no front: 
 - Não é possível alterar o username e o password de usuários com is_remote (pelo back pode alterar a senha)
 - Iconezinho ao lados de nomes de usuários remotos 🤓
![image](https://github.com/anlix-io/flashman/assets/12648211/8e914ca5-f2c7-4df9-b223-10a10f222e97)
![image](https://github.com/anlix-io/flashman/assets/12648211/a42ab58a-dac5-433c-a0b8-dcf80b1c2154)

2023-11-09 20:15 UTC, rilpires commented
Consertar esse blackbox foi foda, olhem o commit do "javascript 7 x 1 me" e me expliquem pq ele consertou pra ganharem phd em javascript

Also, desisti de fazer teste unitário pq percebi q não existe nada que não dependa do anlixid pra testar...

2023-11-10 21:25 UTC, lucasperovani requested changes
Fiz os comentários do que observei até agora. Ainda irei testar melhor e tentar quebrar a sua feature xD. Um outro ponto seria esconder aquele botão de editar para os casos que não conseguem editar nada, que a gente já tinha conversado...

2023-11-13 18:15 UTC, rilpires commented on controllers/auth.js
> +  return async function(req, res, next) {
Tirei o async, mas qual o problema real? Middleware do express lida com os dois...

2023-11-13 18:20 UTC, rilpires commented on controllers/auth.js
> +        }
Realmente rs, mas vc quer q eu retire né? Segurança adicional!

2023-11-13 18:20 UTC, rilpires commented on controllers/auth.js
> +        }
(estou retirando)

2023-11-13 18:28 UTC, rilpires commented on controllers/auth.js
> +  return crypto.createHash('sha256').update(jwt || '').digest('hex');
done

2023-11-13 18:29 UTC, rilpires commented on controllers/auth.js
> +  setTimeout(tryDelete, 60000);
belezura

2023-11-13 18:44 UTC, rilpires commented on controllers/auth.js
> +            .then(() => {
Você diz assim? (🤢)

2023-11-13 18:50 UTC, rilpires commented on controllers/auth.js
> +  });
Não é bem assim que funciona o monitoramento... essa função tem que me dizer qual é o tamanho atual da minha estrutura e só, onde a gente zera ela é fora do escopo

2023-11-13 19:12 UTC, rilpires commented on migrations.js
> +        name: t('defaultRole'),
pois é!

2023-11-13 20:30 UTC, lucasperovani commented on controllers/auth.js
> +        }
Olha, no dia que o mongo/mongoose começar a retornar coisas que a gente não pediu... vai ser complicado kkkkkk

2023-11-13 20:37 UTC, lucasperovani commented on controllers/auth.js
> +  return async function(req, res, next) {
Problema nenhum, é porque anteriormente não tinha, e agora colocou, só comentei mesmo

2023-11-13 20:44 UTC, lucasperovani commented on controllers/auth.js
> +  });
Okay, eu só não vi onde isso foi zerado. Tem grandes chances dessas variáveis chegarem ao limite

2023-11-13 22:07 UTC, rilpires commented on controllers/auth.js
> +  });
É por isso que eu criei o monitoramento kk

2023-11-13 22:46 UTC, lucasperovani approved these changes

2023-11-13 22:47 UTC, merged