Feature/apiv3 multissid projection
anlix-io/flashman pull request #929
Opened 2023-11-23 18:56 UTC by cassiohg

2023-12-01 17:19 UTC, lucasperovani requested changes

2023-12-01 19:48 UTC, cassiohg commented on controllers/api/v3.js
> +  'wans.ipv4': {instance: 'Object', leafFields: newWanIpv4LeafFields},
Ele estava entrando duas vezes, sobreescrevendo a sí próprio.

2023-12-01 20:09 UTC, cassiohg commented on controllers/api/v3.js
> +  'wifi.bssid': {instance: 'String', from: ['wifi_bssid', 'wifi_bssid_5ghz']},
Precisa sim. Tinha esquecido mesmo e coloquei agora pra esses 2.
Esse campo é necessário pra saber se o device tem wifi5 apesar de não ter um campo selecionado pelo usuário ou se ele não tem wifi5. Isso define se, após uma projeção de um usuario, o array `device.wifi` vai ter um objeto representando o wifi5 sendo vazio ou não vai ter um objeto pro wifi5. Isso porque não ter wifi5 e não ter os campos selecionaods de wifi5 dá o mesmo retorno do banco de dados porque os campos do wifi, no banco, estão todos na raíz do `device`. Se a estrutura de multissid estivesse no banco, esses 2 casos retornariam diferente, e o código está produzindo essa diferença.

2023-12-01 20:23 UTC, cassiohg commented on controllers/api/v3.js
>    if (device.use_tr069 || device.wans !== undefined) return;
Isso nao dá pra pegar no blackbox pq a gente não tem criação de firmware pelo flashman, é difereto pelo banco.

2023-12-04 12:11 UTC, lucasperovani commented on controllers/api/v3.js
> +    device.use_tr069 || (device.wans && Object.keys(device.wans).length > 0)
Sobre isso: `Object.keys(device.wans)`. Precisa necessariamente passar por um `Object.keys`? O campo `wans` deveria ser um array e a validação do `.length` já deveria valer, não?

2023-12-04 17:21 UTC, lucasperovani commented on controllers/api/v3.js
>    if (device.use_tr069 || device.wans !== undefined) return;
Sim, isso é um problema que a gente ainda vai resolver. Pensamos em algumas coisas, mas talvez a gente tenha que usar uma cpe de verdade mesmo para analisar o seu comportamento, já que estamos com aquele outro projeto....

2023-12-04 18:10 UTC, cassiohg commented on controllers/api/v3.js
> +    device.use_tr069 || (device.wans && Object.keys(device.wans).length > 0)
Deveria. Doideira minha. Consertei agora.

2023-12-05 11:16 UTC, lucasperovani commented on controllers/api/v3.js
> +    device.use_tr069 || (device.wans && Object.keys(device.wans).length > 0)
Tranquilo, valeu Cassio!! 😁️

2023-12-05 11:57 UTC, lucasperovani approved these changes

2023-12-05 12:04 UTC, merged