Tratamento de requisições AJAX para redirecionar sessões expiradas
anlix-io/flashman pull request #933
Opened 2023-11-24 17:28 UTC by rilpires

Além do problema do título, também resolvi o problema do cookie inválido quando as pessoas terem o flashman atualizado entre a versão PRÉ e PÓS suporte ao anlixid: o cookie antes salvava apenas uma string que era o id do usuário, agora o cookie salva um JSON do tipo {userid:string, _rt:string, _exp:string}
Isso quebrava o front de quem abria o flashman novo com um cookie antigo...

2023-11-24 17:34 UTC, rilpires commented on public/javascripts/showvlanprofiles_actions.js
> +            displayAlertMsg(JSON.parse(xhr.responseText));
Esses handlers q antes eram só tinham o argumento res, (res) => ...
Eu acho que não funcionavam... e acho perigoso usar esse JSON.parse, não temos garantia que o  seja JSON, temos?

2023-11-24 18:37 UTC, rilpires commented on controllers/auth.js
> +    if (req.headers['x-requested-with'] == 'XMLHttpRequest' ) {
Esse header é adicionado automaticamente pelos nossos AJAX!!!

2023-11-24 18:38 UTC, rilpires commented on controllers/auth.js
> +  if ( !req.isAuthenticated || !req.isAuthenticated() ) {
Eu sei que isso é meio estranho... mas é exatamente o if que o antigo middleware fazia, não quis mudar!
https://github.com/jaredhanson/connect-ensure-login/blob/master/lib/ensureLoggedIn.js#L44

2023-11-27 22:56 UTC, GThurler requested changes

2023-11-27 22:56 UTC, GThurler commented on public/src/common.index.js
> +      }
Esse `if` aqui vai impedir o redirect de acontecer se alguém clicar fora do dialog, pois se não me engano isso entra como um evento de dismiss, não de confirm

2023-11-27 22:56 UTC, GThurler commented on public/src/common.index.js
> +      text: i18next.t('frontendUnauthorized'),
Talvez o title fique melhor como "Sua sessão expirou", e o texto ter algo como "A página será atualizada, e pode ser necessário fazer login novamente", sei lá

2023-11-28 18:59 UTC, rilpires commented on public/src/common.index.js
> +      text: i18next.t('frontendUnauthorized'),
donado

2023-11-29 14:47 UTC, GThurler approved these changes

2023-11-29 15:22 UTC, merged