Feature/flashboard metrics
anlix-io/flashman pull request #937
Opened 2023-11-24 22:00 UTC by rilpires

Inserção do "flashboard_api.js", controller pra requisitar métricas do último relatório no flashboard

Pra fazer chamadas ao flashboard, é preciso o access token do usuário remoto, coisa que eu não salvava antes. Por isso precisei fazer as alterações que fiz no auth.js

Eu dividi a tarefa com a @naccaratocarolina pra ela usar esse controller e fzer o front que usa essas informações 🤓🤓🤓

2023-11-30 20:59 UTC, rilpires commented
Ahhhh eu consertei os conflitos e os testes na branch q eu parti daqui (o PR do front), vou tentar fazer um rebase esperto...

2023-12-04 14:31 UTC, lucasperovani submitted a review, later dismissed
Alguns outros pontos:
- O swagger está dando alguns erros, mas acredito que seja por causa de um dos comentários que coloquei aqui;
- A rota está retornando "302 Found" quando envio a requisição sem  a autorização, isso faz sentido para a API?;
- Vou precisar de algum login ou algo do tipo para testar essa funcionalidade, mas isso eu vejo diretamente contigo.

2023-12-04 19:06 UTC, rilpires commented on controllers/api/v3.js
> + * @param {bool} ignore_fb_status_code.query - Ignore Flashboard Status Code.
Aqui você se referiu ao ignore_fb_status_code, né?

2023-12-04 22:36 UTC, rilpires commented on controllers/flashboard_api.js
> +  // }
Ahhh eu não queria botar isso em jsdoc pq é uma API externa com sua própria documentação... isso é o que tá sendo retornado hoje, botei esse comentário mais pra facilitar... ainda acha q faz sentido botar em jsdoc?

2023-12-04 22:44 UTC, rilpires commented on controllers/flashboard_api.js
> +          if (result.entity && Array.isArray(result.entity)) {
Existe o parâmetro "t" que é o termo de busca, não precisa ser necessariamente um termo exato... então o resultado da requisição é sempre uma lista. Eu só fiz esse `then` adicional pra me certificar que o Flashboard não vai trazer outros devices indesejados, pois não sei como funciona a busca dele

2023-12-04 22:56 UTC, rilpires commented on controllers/flashboard_api.js
> +          if (result.entity && Array.isArray(result.entity)) {
> Acredito que queira validar o `else` dessa função? Talvez dando um `reject` ou um `throw`? Não sei se a resposta sempre deverá vir como um array ou não. Seria legal ter um comentário nessa parte para explicar o porque de fazer isso e filtrar pelo `device`

Eu só fiz isso pq algumas rotas do Flashboard retornam o "entity" como uma lista de objetos (no caso desse search que dou aqui), e outras retornam o entity como um único objeto, pois a função faz exatemente isso ("get latest report").

Esse if eu me resguardei desnecessariamente, minha função `getResource` já se certifica que o status é 2XX, não tem na documentação do flashboard como não vir esse entity Array, se isso não existe algum dos mil `catch` já pegou...

2023-12-04 23:14 UTC, rilpires commented on controllers/flashboard_api.js
> +      });
Olha, vou ser sincero, achei esse encadeamento de `then` um pouco confuso, não sei se ele faz exatamente o que estamos pensando que ele faz. Entendi que você quer que eu desfaça o haduken (hadukinho vai), mas posso então trocar tudo pra função assíncrona com `await` e `throw`?

2023-12-04 23:19 UTC, rilpires commented on controllers/flashboard_api.js
> +              );
Não checo o ID do dispositivo pq eu já fiz, eu to partindo de `getWifiScore` aqui, não viu?
Eu fiz o filter extra pra retornar apenas os LanDevices com measures maior ou igual ao mínimo necessário pra se ter alguma nota (pq o flashboard, igual como no flashman, mantém um histórico dos lan devices que cresce infinitamente!)

2023-12-04 23:23 UTC, rilpires commented on controllers/flashboard_api.js
> +            },
Eu já uni muita lógica com o `getResource`, perceba como ela é a única função que faz requisição web do arquivo. Eu posso criar uma função extra pra fazer só esse trabalho de filtrar o device que estamos buscando, é que eu pensei que isso fosse uma lógica muito simples e calculei que isso vai dar mais linhas no total ainda

2023-12-04 23:26 UTC, rilpires commented on controllers/api/v3.js
> +    flashboardApi.getPonScore(jwt, request.params.mac),
> Embora esteja fazendo tudo em paralelo. Essa seria a primeira API nossa que envia a requisição e espera a resposta do servidor. Não sei se isso é uma boa prática. Talvez o ideal é ter uma terceira rota que pede para atualizar os reports e a gente salvar isso na base. Então, essa rota aqui só iria pegar os reports que a gente já tem na base. Acredito que dessa forma elimine até a necessidade da flag `ignore_fb_status_code`. O que acha? Seria legal do @GThurler e @ggbruno opinarem sobre isso também

Acho que o @GThurler também concordou que essa não é uma boa ideia então vou deixar como tá, né?

2023-12-04 23:27 UTC, rilpires commented on controllers/api/v3.js
> +    flashboardApi.getPonScore(jwt, request.params.mac),
> É bom validar os `mac`s antes de enviar diretamente para a rota. Não sei se também é importante validar se o banco do Flashman possui o dispositivo antes de mandar as requisições

Essa é uma boa mesmo

2023-12-04 23:28 UTC, rilpires commented on controllers/api/v3.js
> +  // unauthorized (401), so I will check for both
Esse comentário nem faz sentido, eu confirmei que 403 é o que a gente queria (forbidden - autenticado mas sem autorização)

2023-12-04 23:32 UTC, rilpires commented on controllers/api/v3.js
> +  try {
Minha motivação aqui foi que como estamos dependendo de alguma coisa externa, eu to tentando me precaver pro caso de vir lixo do Flashboard... posso tirar o `try` sem problema

2023-12-04 23:42 UTC, rilpires commented on controllers/api/v3.js
> +  }
Cara, eu percebi que a validação de checar se `request.user` existe é redundante, pq já tem o middleware no router da v3 que faz isso... vou manter só a do bearerToken. Vou criar um middleware no `auth.js` pra esse tipo de validação - acredito que serão pouquíssimas rotas que vão usar ela...

2023-12-04 23:42 UTC, rilpires commented on controllers/api/v3.js
> +  // unauthorized (401), so I will check for both
Comentário deprecado, já estou checando só 403

2023-12-05 00:04 UTC, rilpires commented on controllers/api/v3.js
> +    });
Sobre o que exatamente aqui?

2023-12-05 00:06 UTC, rilpires commented on controllers/api/v3.js
> +  try {
Eu só tirei o `try/catch`, tá bom? O que seria outra devida validação extra? Checar a existência ou não de cada um dos campos? (latencyMin, latencyMean, etc)

2023-12-05 00:07 UTC, rilpires commented on controllers/api/v3.js
> + */
boa

2023-12-05 00:16 UTC, rilpires commented on controllers/flashboard_api.js
> +        }
> Já que está dando um `reject` com um erro aqui. Acho válido de implementar nas outras funções também, mas a cada função ter a validação com o `catch` e dar o `reject` com o erro da função que deu o erro.

Mas todo catch nas outras funções só podem ser proveniente desses erros que estou jogando aqui, pois tudo usa o `getResource`, não existe outro erro desconhecido

2023-12-05 00:19 UTC, rilpires commented on controllers/flashboard_api.js
> +        }
> Seria legal também documentar com o @throws no JSDoc. Ou usar o segundo argumento do .then: .then(onFulfilled, onRejected), onde onFulfilled e onRejected são funções que recebem o valor thar promise que foi aceita ou rejeitada

E eu não sei como documentar o outro erro que não esse do status code. Pode ser um milhão de outros erros, pode ser pq o fqdn não resolve, pode ser timeout, pode ser port refused, você quer que eu faça um tratamento especial pra um cada um desses tipos?

2023-12-05 00:22 UTC, rilpires commented on controllers/flashboard_api.js
> +          reject(error);
Beleza

2023-12-05 13:09 UTC, rilpires commented on controllers/api/v3.js
> +    flashboardApi.getPonScore(jwt, request.params.mac),
> É bom validar os `mac`s antes de enviar diretamente para a rota. Não sei se também é importante validar se o banco do Flashman possui o dispositivo antes de mandar as requisições

Mas eu tava pensando, esse parece o tipo de coisa que fazemos em mil outras rotas (todas que tem no path /{mac_address}/). Não seria legal fazer um middleware que faz essa checagem? E poderia preencher o "req" com o device já

2023-12-05 18:01 UTC, rilpires commented on controllers/api/v3.js
> +    flashboardApi.getPonScore(jwt, request.params.mac),
Thurler falou que checar se existe na nossa base é desnecessário, e eu concordo um pouco agora... 
E outra, apesar do parametro se chamar mac, ele pode ser um serial do tr069 também, a gente parou de aceitar isso? Pq nesse caso aí não existe função de validação de serial né...

2023-12-05 18:05 UTC, rilpires commented
> Alguns outros pontos:
> 
>     * O swagger está dando alguns erros, mas acredito que seja por causa de um dos comentários que coloquei aqui;
> 
>     * A rota está retornando "302 Found" quando envio a requisição sem  a autorização, isso faz sentido para a API?;
> 
>     * Vou precisar de algum login ou algo do tipo para testar essa funcionalidade, mas isso eu vejo diretamente contigo.

Consertei o Swagger, e sobre o retorno da rota estar sendo 302... não sei oq pode ser, aqui não tomo isso, pode ser alguma coisa faltando no seu ambiente, tem mais informações dessa resposta?

Pra testar a funcionalidade, você precisa estar com o AnlixId habilitado E com o realm de um cliente que tenha flashboard, isso exige colocar alguns secrets nas variáveis de ambiente. E ainda assim não vai dar pra testar no front sem algum mock, pq os roteadores que existem na sua base provavelmente não existem na base do cliente!

2023-12-05 18:57 UTC, rilpires commented on controllers/flashboard_api.js
> +  // }
botei em jsdoc, não cada campo da resposta, isso é documentação externa!

2023-12-06 17:35 UTC, GThurler commented on controllers/api/v3.js
> +    flashboardApi.getPonScore(jwt, request.params.mac),
> E outra, apesar do parametro se chamar mac, ele pode ser um serial do tr069 também, a gente parou de aceitar isso? Pq nesse caso aí não existe função de validação de serial né...

Toda a API v3 é baseada no MAC usado como chave primária no Flashman (o MAC da LAN). Caso só tenha o serial, existe um endpoint que retorna um device a partir de um serial, que pode ser usado para identificar o MAC dele para o resto da API

2023-12-06 17:42 UTC, GThurler commented on controllers/flashboard_api.js
> +
Todas as nossas integrações com APIs externas (exceto o genie, por motivos de legado) ficam dentro do diretório `controllers/external-api`, poderia mover esse arquivo pra lá

2023-12-06 17:51 UTC, GThurler commented on controllers/api/v3_flashboard.js
> +  ]).then((results) => {
Misturar `await` e `then` é a receita para o disastre, ou você usa await com try ou usa promise chaining:
```javascript
const promiseResults = await Promise.allSettled([
  callPromise1(),
  callPromise2(),
]);
console.log(promiseResults.length); // 2

Promise.allSettled([
  callPromise1(),
  callPromise2(),
]).then((promiseResults) => {
  consol.log(promiseResults.length); // 2
});
```

Todo o Flashman (ou quase todo) está padronizado para usar await com try/catch, para evitar encadeamentos gigantes de `then`, que pode atrapalhar o error handling quando cada promise pode dar reject no meio da sequência.

No caso do Promise.allSettled, ele nunca dá um reject, pois sempre retorna um iterável com o resultado de cada promise. O que eu não sei é o que acontece quando uma das promised encontra uma exception não tratada - o Promise.allSettled dá um throw também? Se sim, precisaria de um .catch() em cada uma das abordagens acima

2023-12-06 18:01 UTC, GThurler commented on locals.js
> +// dependencies on other modules. It also __SHOULD NOT __ set variables by
Não entendi a mudança aqui, rs

2023-12-08 04:23 UTC, rilpires commented on controllers/api/v3_flashboard.js
> +  ]).then((results) => {
doc da [developer.mozilla.org](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled):
`Para cada objeto no array retornado, existe uma string status. Se o status for fulfilled, então o campo value estará presente. Se o status for rejected, então o campo reason estará presente. O valor (value) ou o motivo da falha (reason) refletem o valor com que cada promessa foi completada (ou rejeitada).`

allSettled não dá throw, o objeto saída de cada promise contém um status e um value/reason, dependendo do status

2023-12-08 04:32 UTC, rilpires commented on controllers/api/v3_flashboard.js
> +    });
Olha, eu concordo que é um pouco estranho, mas aí é a questão que já debatemos, a única informação extra q eu retorno quando falha é se for um forbidden, pq acho importante isso ficar claro. 
Não acho legal só fazer  um proxy do flashboard e só repassar o status code dele no lugar do do flashman, mas se for pra dar mais informação total de todo o intermédio com o flashboard, vc sugere que eu mude essa resposta da api com um status_code do flashboard embutindo em um campo? (eu acho essa uma boa ideia)

2023-12-08 04:34 UTC, rilpires commented on locals.js
> +// dependencies on other modules. It also __SHOULD NOT __ set variables by
Pq depois da mudança q fiz ali em baixo achei legal isso ficar mais claro, é tentador pensar q podemos setar algumas variaveis globais a partir de requests assincronas e etc mas foi justamente isso que eu precisei evitar quando criei esse locals.js, coisas q não dependem de ordem de inicialização

2023-12-08 04:50 UTC, rilpires commented on controllers/api/v3_flashboard.js
> +      packetloss_percent_normal_lower_thresh:
sério eu detesto variável enorme desse jeito mas eu juro q não pensei em nome melhor. Eu sinto que PRECISO especificar de qual limiar do "normal" esse valor é: se é do limiar inferior (com o bom) ou superior (com o ruim). Nessa confusão vi q tinha trocado a ordem tb (antes era superior com bom), agora tá certo 🐧🐧🐧

2023-12-08 19:02 UTC, edufolly commented
Buscando uma ajuda para vcs.

@CodiumAI-Agent /review

2023-12-11 17:52 UTC, lucasperovani commented on routes/api/v3.js
> +  '/device/mac/:mac/flashboard/latest-landevice-report/',
@GThurler o que acha de passar para: `/device/mac/:mac/flashboard/latest/report/` e `/device/mac/:mac/flashboard/latest/lan-devices/report/`?

2023-12-11 23:33 UTC, GThurler commented on routes/api/v3.js
> +  '/device/mac/:mac/flashboard/latest-landevice-report/',
Por mim poderia ser:
`/device/mac/:mac/flashboard/reports/overall/latest`
`/device/mac/:mac/flashboard/reports/lan-devices/latest`
O racional seria simplesmente pra ser mais tranquilo/intuitivo criar outros endpoints similares no future, por mais improvável que seja:
`/device/mac/:mac/flashboard/reports/overall/:reportId`
`/device/mac/:mac/flashboard/reports/pon/:reportId`
`/device/mac/:mac/flashboard/reports/wifi/latest`
Só que é aquela né, até que ponto vale adicionar isso tudo ao invés de fazer um API-in-API?

2023-12-11 23:34 UTC, GThurler commented on routes/api/v3.js
> +  '/device/mac/:mac/flashboard/latest-landevice-report/',
Agora, esse ponto deveria ter sido levantado lá na versão original do PR, não? Por que foi levantado só hoje isso?

2023-12-11 23:52 UTC, rilpires commented on routes/api/v3.js
> +  '/device/mac/:mac/flashboard/latest-landevice-report/',
![image](https://media1.giphy.com/media/u5BzptR1OTZ04/200.webp?cid=ecf05e47jqcpx08tqzumss4qguojsc24yxdzfqlp98y3tr09&ep=v1_gifs_search&rid=200.webp&ct=g)

2023-12-12 17:24 UTC, GThurler requested changes

2023-12-12 17:24 UTC, GThurler commented on controllers/api/v3_flashboard.js
> +  });
Fiz o teste aqui e isso vai estourar se uma das chamadas pra `flashboardApi` der exception (não reject). Continua o problema de misturar `await` com `then`, ou usa um ou usa o outro:
```javascript
const a = function() {throw new Error('a');}
const b = function() {return new Promise((res, rej)=>rej());}
const c = function() {return new Promise((res, rej)=>res());}

const main = async function() {
  Promise.allSettled([b(), c()]).then(
    (e)=>console.log(`Resolved: ${JSON.stringify(e)}`),
    (f)=>console.log(`Rejected: ${JSON.stringify(f)}`),
  );
  try {
    const g = await Promise.allSettled([b(), c()]);
    console.log(`Await result: ${JSON.stringify(g)}`);
  } catch (err) {
    console.log(`Await exception: ${err}`);
  }
  try {
    Promise.allSettled([a()]).then(
      (e)=>console.log(`Resolved: ${JSON.stringify(e)}`),
      (f)=>console.log(`Rejected: ${JSON.stringify(f)}`),
    );
  } catch (err) {
    console.log(`Then exception: ${err}`);
  }
  try {
    const h = await Promise.allSettled([a()]);
    console.log(`Await 2 result: ${JSON.stringify(h)}`);
  } catch (err) {
    console.log(`Await 2 exception: ${err}`);
  }
};
main();
```

2023-12-12 17:24 UTC, GThurler commented on controllers/api/v3_flashboard.js
> +    });
A ideia não é fazer o proxy do status code, era só retornar um status code 500 com uma mensagem genérica de "Erro ao consultar os dados no Flashboard". Pode ter um campo de detalhes pra poder ajudar a depurar, mas enfim.

Não acho estritamente necessário mudar o 200 com body vazio, dado qu vai mudar algumas coisas que já estão ok, é só porque do ponto de vista de design pra API fica ruim. Como não é algo que vai ser amplamente usado, por mim tanto faz por agora, só vamos ter que carregar isso como legado pro futuro, já que alguém pode depender do 200 com body vazio

2023-12-12 17:24 UTC, GThurler commented on controllers/flashboard_api.js
> +
Lembrando que isso aqui precisa ser endereçado

2023-12-13 00:00 UTC, rilpires commented on controllers/api/v3_flashboard.js
> +  });
ta donado isso né

2023-12-13 13:09 UTC, guissenges commented
Agora vai @GThurler ?

2023-12-13 13:19 UTC, GThurler commented
Sim, só faltavam esses 2 ajustes

Em qua., 13 de dez. de 2023 10:09, Guilherme da Silva Senges <
***@***.***> escreveu:

> Agora vai @GThurler <https://github.com/GThurler> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/anlix-io/flashman/pull/937#issuecomment-1853889705>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI6QSFEROAPBGCMARPJKGRDYJGSKDAVCNFSM6AAAAAA7ZTFUL2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJTHA4DSNZQGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-13 15:00 UTC, GThurler approved these changes

2023-12-13 15:00 UTC, merged