Feature/voip sip edit
anlix-io/flashman pull request #942
Opened 2023-11-28 17:02 UTC by RaphaelAN

Adding sip edition in fontend and voip api

2023-11-30 19:53 UTC, GThurler approved these changes

2023-11-30 19:53 UTC, GThurler commented on controllers/voip/validators.js
> + */
Descrições ainda estão com o texto do copy/paste

2023-11-30 19:53 UTC, GThurler commented on controllers/voip/validators.js
> +  };
- O campo de IP do servidor SIP pode ficar vazio, o backend está exigindo que tenha 7 caracteres
  - Se o profile está desabilitado, por exemplo, é normal o IP estar vazio
  - Pode-se também querer tirar o apontamento sem desabilitar o perfil inteiro

2023-11-30 19:55 UTC, GThurler requested changes
Só deixando o request changes, errei o botão quando deixei 2 comentarios rs

2023-12-11 15:01 UTC, rilpires approved these changes
showw

2023-12-11 15:18 UTC, rilpires commented
Vou só pedir pra você fazer o merge da development de volta pra essa feature, eu tentei fzer o merge achando q teria sido simples, mas parece q quebraram algumas coisas (formato do getChanges())

2023-12-11 22:25 UTC, rilpires commented
🤙🤙🤙🤙🤙🤙🤙

2023-12-11 22:26 UTC, rilpires approved these changes

2023-12-11 22:39 UTC, merged