Move portForward and wlanAC tasks to TasksAPI
anlix-io/flashman pull request #949
Opened 2023-11-30 21:46 UTC by ggbruno

Corrige o problema do NBI estar fora quando tasks devem ser enviadas. O tasksAPI realiza o catch em caso de erro na requisicao ao NBI. As rotinas do portForward e do wlanAccessControl ainda estavam enviando diretamente por http sem tratar erro de conexão.

2023-12-04 20:16 UTC, lucasperovani requested changes

2023-12-04 20:22 UTC, lucasperovani commented
`makeWanFieldsProjection` e `readWanUpstatus` não validam se o retorno da função `replaceWildcardsWithChosenWan` é `null` ou não

2023-12-04 20:40 UTC, GThurler commented on controllers/handlers/acs/measures.js
> +    if (!addressField) return;
Sim, a informação não deveria ser retornada incompleta. Até porque, se esse falhou, provavelmente os seguintes vão falhar também

2023-12-04 20:42 UTC, GThurler commented on controllers/acs_device_info.js
> +      if (!fieldData) return;
A gente poderia adicionar em todos os pontos, mas provavelmente vai ficar printando em loop por conta do Flashboard. O fato de relojar no front pra sempre é um card em aberto, pois esse `return` solto deveria enviar um socket.io ao front antes de dar o `return`, para impedir de ficar relojando

2023-12-04 20:44 UTC, GThurler commented on controllers/external-genieacs/tasks-api.js
>          path: `/devices/${encodeURIComponent(device.acs_id)}`,
Seria legal mas queria minimizar alterações no código sem o Gaspare estar aqui, rs

2023-12-04 21:14 UTC, lucasperovani commented
Aparentemente está funcionando. Conversei sobre os comentários com o @GThurler . Seria interessante testar o port mapping, entretanto, todas as outras funcionalidades parecem estar corretas, apenas necessitando das alterações comentadas. Após isso, acredito que esteja pronta para ser liberada.

2023-12-05 00:03 UTC, GThurler approved these changes

2023-12-05 00:03 UTC, merged