Feature/flashboard data front
anlix-io/flashman pull request #950
Opened 2023-12-01 18:17 UTC by naccaratocarolina

**(!) Falta fazer a integração ainda!!!**

![image](https://github.com/anlix-io/flashman/assets/41310085/926facf7-2889-423c-8fd2-e85cd667ca63)

![image](https://github.com/anlix-io/flashman/assets/41310085/6ebf48fb-6f19-43ff-ac2e-913733118280)

2023-12-06 02:43 UTC, rilpires commented
Pra mim tá zero bala :gun::gun::gun:

2023-12-11 20:17 UTC, naccaratocarolina commented on public/javascripts/handlers/table_anim_redraw_handler.js
> +};
Para fazer testes nessa branch, altere essa função sobrescrevendo o argumento `data` para ser igual aos objetos mockados.
@lucasperovani

2023-12-12 14:32 UTC, rilpires commented
Só registrando aqui @naccaratocarolina sobre aquilo que conversei com você: é preciso que essa aba não apareça se o usuário não tive a permissão do flashboard no flashman (`grantFlashboardResume==true` na role).

2023-12-13 17:52 UTC, GThurler requested changes
Vou dar submit logo dos comentários periféricos aos widgets criados, que peguei só com o review do código. Vou colocar pra rodar na minha máquina pra ver detalhes de funcionalidade e de código dos widgets

2023-12-13 17:52 UTC, GThurler commented on public/javascripts/handlers/table_anim_redraw_handler.js
> +let toggleFlashboardHtml = function(index, t, data, isLoading=false) {
Eu sei que as outras funções passam isso, mas você não precisa passar `t` como argumento, ele está disponível no escopo "global"

2023-12-13 17:52 UTC, GThurler commented on public/javascripts/handlers/table_anim_redraw_handler.js
> + * @param {object} data - The data fetched from the server
Seria bom documentar esse formato de dados aqui, pra não ficar um object solto que ninguém sabe como usar. Se você documentar lá no FlashboardTab com um typedef você pode usar o mesmo typedef aqui

2023-12-13 17:52 UTC, GThurler commented on public/javascripts/handlers/table_anim_redraw_handler.js
> + * @param {*} mac - The mac address of the device
Não deveria ser `string` não?

2023-12-13 17:52 UTC, GThurler commented on public/javascripts/table_anim.js
> +  .on('click', '.fa-chevron-down.device-table-row', async function(event) {
Por que essa função precisou virar async se não tem nenhum await dentro dela?

2023-12-13 17:52 UTC, GThurler commented on public/locales/pt/translation.json
> +  "times": "vezes",
`time` e `times` pode ficar ambíguo com noções de tempo (ex.: segundos); typo na forma singular
```suggestion
  "timeRepetition": "vez",
  "timesRepetition": "vezes",
```

2023-12-14 21:44 UTC, GThurler approved these changes

2023-12-14 22:32 UTC, merged