searchDeviceReg now honors frontend timezone
anlix-io/flashman pull request #951
Opened 2023-12-01 21:27 UTC by rilpires

2023-12-05 17:09 UTC, lucasperovani requested changes
Parabéns Romeu, a solução ficou muito boa e enxuta, sei que teve que pensar bastante para chegar nesse resultado! Só pontuei a questão de caso o `tzOffsetMinutes` não vir, para a gente manter do jeito que já está, que é detalhezinho.

Mas outro ponto que quero levantar, que vai ser chato de fazer, infelizmente, é de ver onde a função `complexSearch` está sendo usada e adaptar o código para usar o timezone nesses pontos também, principalmente na API e upgrade em massa. Digo isso porque o upgrade em massa é um caso sensível, retornar algo diferente do que tinha pesquisado inicialmente pode ser perigoso. Se não conseguir fazer algum dos casos, me avise que a gente conversa sobre.

De qualquer forma, ficou muito bom! Parabéns Romeu!

2023-12-05 17:09 UTC, lucasperovani commented on controllers/device_list.js
> +        + (minuteOffset >= 0 ? '+' : '-')
Acredito que fique melhor se isso só for adicionado caso o `tzOffsetMinutes` não seja `undefined` ou `null` ou `NaN` (depende do default que colocar na função). O motivo disso é que se o offset não for passado, ele já leve em conta o timezone do próprio servidor e não usa GMT+0. Ou seja, ele continua funcionado do jeito que está caso não tenha vindo.

2023-12-08 20:37 UTC, rilpires commented on controllers/device_list.js
> +        + (minuteOffset >= 0 ? '+' : '-')
Eu fiz o fallback de quando `tzOffsetMinutes` não vem definido pra ser igual ao do backend. Agora que eu vi a preocupação do timezone passado em todos as rotas que terminam caindo no complexSearch... to passando por isso

2023-12-08 21:58 UTC, rilpires commented on controllers/device_list.js
> +        + (minuteOffset >= 0 ? '+' : '-')
O Thurler me convenceu que isso de usar o timezone do backend como default não deveria ser assim, e faz sentido, nunca foi assim, foi só depois do PR da Carol que passou a funcionar dessa forma, antes disso o timezone sempre foi GMT+00

2023-12-08 23:12 UTC, rilpires commented
Cara... tem um problema... 
Existe [um form](https://github.com/anlix-io/flashman/blob/2009d6c62d10f872c22754bb7e04bc9e52224aa2/views/includes/showdatacollectingmodal.pug#L169) feito pelo front que termina caindo no complexsearch, que tá até em pug: não dá pra adicionar header em form...
E assim, isso vai exigir muuuuita mudança pra algo que acho muito caso de borda... (feature ficando bem complexa, visto o trabalho que eu tive que fazer nos testes unitários só pra poder incluir headers)

2023-12-11 19:18 UTC, lucasperovani commented on controllers/device_list.js
> +/**
❤️

2023-12-11 19:25 UTC, lucasperovani commented on controllers/device_list.js
> + */
❤️

2023-12-11 19:37 UTC, lucasperovani commented on controllers/device_list.js
> +        + (minuteOffset >= 0 ? '+' : '-')
Claro, porque isso não tinha sido implementado antes. Ninguém costuma adicionar CPE meia noite para perceber esse problema e porque não tem nenhum provedor com um GMT que dê para perceber o problema. Mas agora usar o GMT do servidor tem mais chance de estar certo pela atual situação da Anlix de apenas estar no Brasil ou ter empresas que apenas operam no Brasil. E quanto aos provedores que estão na nuvem, usar o GMT do servidor tem menos chance de dar problema por ter um offset menor que para o GMT+00

2023-12-11 20:42 UTC, lucasperovani commented
> Cara... tem um problema... Existe [um form](https://github.com/anlix-io/flashman/blob/2009d6c62d10f872c22754bb7e04bc9e52224aa2/views/includes/showdatacollectingmodal.pug#L169) feito pelo front que termina caindo no complexsearch, que tá até em pug: não dá pra adicionar header em form... E assim, isso vai exigir muuuuita mudança pra algo que acho muito caso de borda... (feature ficando bem complexa, visto o trabalho que eu tive que fazer nos testes unitários só pra poder incluir headers)

Sobre isso, talvez seja melhor a gente passar isso como um query parameter pelas rotas ao invés de um header, outro ponto que pode haver discrepância é o de exportar por CSV. E aí para a gente ter apenas metade do Flashman fazendo o certo e a outra metade com  o padrão antigo é estranho e vai gerar confusão

2023-12-11 22:38 UTC, rilpires commented
> > Cara... tem um problema... Existe [um form](https://github.com/anlix-io/flashman/blob/2009d6c62d10f872c22754bb7e04bc9e52224aa2/views/includes/showdatacollectingmodal.pug#L169) feito pelo front que termina caindo no complexsearch, que tá até em pug: não dá pra adicionar header em form... E assim, isso vai exigir muuuuita mudança pra algo que acho muito caso de borda... (feature ficando bem complexa, visto o trabalho que eu tive que fazer nos testes unitários só pra poder incluir headers)
> 
> Sobre isso, talvez seja melhor a gente passar isso como um query parameter pelas rotas ao invés de um header, outro ponto que pode haver discrepância é o de exportar por CSV. E aí para a gente ter apenas metade do Flashman fazendo o certo e a outra metade com o padrão antigo é estranho e vai gerar confusão. Dependendo de como isso for passado, é interessante colocar essa informação na rota da API V3:
> 
> ```
>       - in: header
>         name: Timezone offset
>         schema:
>           type: number
>         required: false
>         description: |
>           The timezone offset in minutes. It is used to calculate the time
>           difference between the server and the client. If not passed, it will
>           use GMT+00 as default.
> ```

Cara, o Thurler falou que esse form é um legado deprecadaço, manda bala

2023-12-12 13:18 UTC, lucasperovani commented
> > > Cara... tem um problema... Existe [um form](https://github.com/anlix-io/flashman/blob/2009d6c62d10f872c22754bb7e04bc9e52224aa2/views/includes/showdatacollectingmodal.pug#L169) feito pelo front que termina caindo no complexsearch, que tá até em pug: não dá pra adicionar header em form... E assim, isso vai exigir muuuuita mudança pra algo que acho muito caso de borda... (feature ficando bem complexa, visto o trabalho que eu tive que fazer nos testes unitários só pra poder incluir headers)
> > 
> > 
> > Sobre isso, talvez seja melhor a gente passar isso como um query parameter pelas rotas ao invés de um header, outro ponto que pode haver discrepância é o de exportar por CSV. E aí para a gente ter apenas metade do Flashman fazendo o certo e a outra metade com o padrão antigo é estranho e vai gerar confusão. Dependendo de como isso for passado, é interessante colocar essa informação na rota da API V3:
> > ```
> >       - in: header
> >         name: Timezone offset
> >         schema:
> >           type: number
> >         required: false
> >         description: |
> >           The timezone offset in minutes. It is used to calculate the time
> >           difference between the server and the client. If not passed, it will
> >           use GMT+00 as default.
> > ```
> 
> Cara, o Thurler falou que esse form é um legado deprecadaço, manda bala

Mas então, tem rotas, em AJAX, que não estão recebendo o header. Vou conversar com ele para entender isso melhor...

2023-12-12 22:14 UTC, lucasperovani approved these changes

2023-12-12 23:21 UTC, merged