Feature/huawei zone multilazer temperatures
anlix-io/flashman pull request #952
Opened 2023-12-02 00:41 UTC by cassiohg

2023-12-06 21:20 UTC, lucasperovani requested changes
Não consegui verificar a temperatura da PON no EG8145X6 na interface web. Talvez por aquele typo que eu comentei

2023-12-07 00:13 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.md
> +| wan.pon_temperature | ❌ | ❌ | Não possui | Campo que informa a temperatura da PON na CPE, em Celcius. |
Retirei a menção de Celsius.
Nao tem nada de `diagnostics.statistics` nesse arquivo. Segui a regra, mas agora coloquei o `diagnostics.statistics.cpu_temperature`.

2023-12-07 00:13 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +  }
Tem que esperar aparecer pra mudar o código.

2023-12-07 00:13 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +    let regexpString = '(\\d{1,}(?:.\\d{1,})?)\\s*°?';
Ele pega numero, talvez com ponto, talvez com espaço mais "°"

2023-12-07 00:13 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +          'TemperatureSensor.1.Value',
Todos os modelos só tem em campo proprietário.

2023-12-07 00:17 UTC, cassiohg commented on controllers/acs_device_info.js
> +  let taskParameterNames = [rxPowerField, txPowerField, ponTemperature];
Adicionei uma checagem antes de adicionar.

2023-12-07 00:22 UTC, cassiohg commented on views/includes/showstatistics.pug
> +                h4#resource-cpu-temperature.text-muted.m-0(style='height:30px;')= ''
Mudei.

2023-12-07 00:25 UTC, cassiohg commented
> Não consegui verificar a temperatura da PON no EG8145X6 na interface web. Talvez por aquele typo que eu comentei

Acredito que seja. Tem gente usando a cpe e não consigo restertar agora.

2023-12-07 11:39 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +  }
Sim sim, só coloquei esse comentário para a gente ter noção no futuro. Acho razoável essa verificação que você fez

2023-12-07 11:55 UTC, lucasperovani commented on controllers/handlers/acs/measures.js
> +  }
Sim, eu entendo, de fato não precisa dela. Não sei se com o Flashify essa flag será necessária porque pode ser que a gente tenha o registro desse campo mas por algum motivo a gente queira desabilitar para o modelo X porque está crashando/não está funcionando de forma correta atualmente. Acho válido de testar a permissão aqui de qualquer forma. Pelo menos a gente consegue desativar o recurso e quando a quisermos a gente consegue reabilitar sem remover o campo já mapeado...

2023-12-07 11:56 UTC, lucasperovani commented on test/unit/cpe_model.test.js
> +    [12, 12],
Sim sim, bastante coisa, mas aposto que quando entrar uns modelos estranhos, a gente vai ter que adicionar mais detalhes na regex haha

2023-12-07 12:03 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.md
> +| wan.pon_temperature | ❌ | ❌ | Não possui | Campo que informa a temperatura da PON na CPE, em Celcius. |
Verdade, estranho não possuir esse campo aqui. Obrigado por adicionar Cassio, pelo menos a gente vai ter a documentação completa aqui

2023-12-07 15:53 UTC, lucasperovani commented
Mesmo após a correção não consegui verificar a temperatura. O X6 está comigo, se quiser pegar ele, fica a vontade

2023-12-07 17:22 UTC, lucasperovani commented
Descobri o motivo. O campo `pon_temperature` está sendo atualizado apenas ao abrir o menu `opções > sinal óptico`. Que não tem haver com esse campo da WAN, pelo menos não na representação do front. O que acho legal de fazer é remover esse campo da função `fetchPonSignalFromGenie` e passar ele para dentro do sync, porque sempre que a gente quiser atualizar, a gente pode simplesmente apertar aquele botão de atualizar da tabela

2023-12-07 19:12 UTC, cassiohg commented
> Descobri o motivo. O campo `pon_temperature` está sendo atualizado apenas ao abrir o menu `opções > sinal óptico`. Que não tem haver com esse campo da WAN, pelo menos não na representação do front. O que acho legal de fazer é remover esse campo da função `fetchPonSignalFromGenie` e passar ele para dentro do sync, porque sempre que a gente quiser atualizar, a gente pode simplesmente apertar aquele botão de atualizar da tabela

Me foi pedido para ele ser coletado junto aos dados de rx e tx da pon. E esses dados são coletado quando o usuário acessa `opções > sinal óptico`. Melhor confirmar com o thurler que foi quem criou o card.

2023-12-07 21:10 UTC, lucasperovani commented
Pelo que me informei com o Thurler, esses campos eles são carregados também no sync, talvez não a mensagem não tenha ficado tão clara assim e por isso a confusão. No caso seria só adicionar mesmo no sync

2023-12-08 02:18 UTC, cassiohg commented on controllers/handlers/acs/measures.js
> +  }
Depois de trocar a logica de update pro device sync, eu precisei usar a flag então acabou sendo util.

2023-12-08 02:19 UTC, cassiohg commented
> Pelo que me informei com o Thurler, esses campos eles são carregados também no sync, talvez não a mensagem não tenha ficado tão clara assim e por isso a confusão. No caso seria só adicionar mesmo no sync

Reescrevi a logica pra rodar dentro do sync do device.

2023-12-08 13:29 UTC, merged

2023-12-14 01:00 UTC, guissenges commented
![image](https://github.com/anlix-io/flashman/assets/35816487/c28de796-bfcd-4b3d-a13b-f18745b24394)

Esse é um cadastro de um EG8145V5 . Não apareceu a info de temperatura da CPU. Foi testado nesse modelo?
@lucasperovani @cassiohg

2023-12-14 17:52 UTC, cassiohg commented
![20231214-144815](https://github.com/anlix-io/flashman/assets/2954166/e651f9bf-e1d4-49a8-a02c-e78e55df3d19)
Essa CPE é um Huawei HG8145V5 usado pra teste dentro da anlix.

2023-12-14 18:18 UTC, guissenges commented
@cassiohg : Pois é, vou disparar esse comando na mão para essa CPE e ver o que está chegando como retorno... Um mistério até agora