Feature/add status wifi
anlix-io/flashman pull request #953
Opened 2023-12-04 17:26 UTC by RaphaelAN

Adding wifi status to the wifi tab.

2023-12-05 19:48 UTC, lucasperovani requested changes
Embora a ideia tenha sido boa de adicionar o status na própria aba, infelizmente a nossa cor não ajuda. Talvez seria legal de colocar dentro do `wifi-tab-content`. Mas preciso de mais opniões... @GThurler @naccaratocarolina

2023-12-05 19:48 UTC, lucasperovani commented on models/device_version.js
> +    grantWifiStatus: cpePermissions.wifi.hasWifiStatus,
Assim como existe a permissão para TR-069, também existem as permissões para Firmware/Flashbox. Elas estão na função `devicePermissions`. No caso dessa outra função, vai estar marretado em `false`

2023-12-05 19:48 UTC, lucasperovani commented on controllers/acs_device_info.js
> +    }
Eu não sei como vem esse campo da CPE, mas você deve precisar criar uma função de conversão no base-model para salvar na base um valor nosso. Ainda que todos os CPEs testados retornem a mesma coisa, não que dizer que um modelo X retorne, e também é uma segurança a mais para a gente não guardar algo inválido na base.

Outro ponto é que se for do tipo `boolean`, `false` dará problema nesse ponto por causa de `data.wifi2.status.value`.

O mesmo vale para o 5GHz

2023-12-05 19:48 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +              (device.permissions.grantWifiStatus ? wifi5Status : '' )+
Acredito que aqui tenha que adicionar mais um nível de tabulação por estar dentro do `<a>`
```suggestion
                '5.0GHz'+
                (device.permissions.grantWifiStatus ? wifi5Status : '' )+
```

2023-12-05 19:48 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +            }
Eu validaria nesse `else` se o `wifi_status_5ghz` é por exemplo `Down`. A razão de fazer isso é para manter o legado ou dispositivos que não possuam esse campo por ainda não ter atualizado e mostrar como se o Wi-Fi estivesse desligado

2023-12-05 19:48 UTC, lucasperovani commented on public/javascripts/table_anim.js
>                      '</a>'+
```suggestion
                        '2.4GHz'+
                        (
                          device.permissions.grantWifiStatus ?
                          wifiStatus : ''
                        ) +
```

2023-12-05 19:57 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +            'title="'+device.wifi_status_5ghz+'"'+
Já que está usando isso como título, poderia colocar uma tradução para esse campo

2023-12-06 13:29 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +      hasWifiStatus: false, // will collect and display wifi status
Vou te pedir para adicionar esse campo e os `fields` no arquivo `base-model.md`

2023-12-08 20:27 UTC, guissenges commented
@RaphaelAN esse PR morreu?

2023-12-08 20:36 UTC, RaphaelAN commented
Não morreu não, só estou terminando os acertos pedidos pelo Lucas.

On Fri, Dec 8, 2023, 17:27 Guilherme da Silva Senges <
***@***.***> wrote:

> @RaphaelAN <https://github.com/RaphaelAN> esse PR morreu?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/anlix-io/flashman/pull/953#issuecomment-1847804240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIB76NN67WIJHVF6KYUT27TYINZ4FAVCNFSM6AAAAABAGLAGDCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNBXHAYDIMRUGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-13 13:46 UTC, lucasperovani requested changes

2023-12-13 13:46 UTC, lucasperovani commented on controllers/acs_device_info.js
> +    }
Fiz o re-review e aparentemente isso aqui não foi alterado. É bom a gente ter um padrão na base, talvez mapeado para os valores que nem foi feito para o status da WAN no device models, utilizando um `enum`. E é importante ter uma função tipo a `convertWanStatus` no `base-model.js` para fazer essa conversão se houver algum valor diferente
Percebi agora que o comentário do `enable` acabou ficando acima, seria legal mover para baixo apenas para não gerar confusão

2023-12-14 14:41 UTC, lucasperovani approved these changes
Só alguns feedbacks que as vezes passa sem querer e para lembrar de todos eles é complicado:
- Eu adicionei o enum no device model para a gente limitar o que está chegando na base, não guardar alguma coisa inválida e ficar congruente com o restante do código;
- Não sei se nos casos que você pegou tinha algum `Disabled`. Adicionei dentro das possibilidades por ter encontrado ele no AX2S (sei que não foi pedido esse roteador, mas adicionei pela facilidade);
- Eu mapeie os campos de status na API V3 para ficar dentro do array de wifis. É só mais um detalhe para ficar de olho em implementações futuras...

2023-12-14 15:19 UTC, merged