Collecting LAN status of CPE ports.
anlix-io/flashman pull request #959
Opened 2023-12-07 22:28 UTC by cassiohg

Enabled the collecting of lan status for several ligga CPEs. Added front end visual information to display a CPE lan ports status. Added blackbox test to check lan status values.

2023-12-11 21:18 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +      ],
Essa é a nossa melhor opção? Se a gente tiver apenas 1 `field` com asterístico no número e ter uma `permission` que diga quais índices estão mapeados a LAN ficaria melhor? Talvez dessa forma a gente conseguiria expandir isso para o futuro quando e se implementarmos o "MultiLAN". O que acha?

2023-12-12 01:22 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +      ],
Nossa lógica com asterístico tansforma campos com asterístico em um único valor, o primeiro ou o último.

2023-12-12 13:55 UTC, danielatk commented on controllers/external-genieacs/cpe-models/base-model.js
> +      ],
Dando meus dois centavos aqui sem ninguém ter pedido:

Acho que poderia ter realmente um campo só com asterísco, uma permissão chamada algo como numberOfLanPorts, que informa a quantidade de portas LAN, ajudando na visualização, e uma função que recebe como entrada a porta LAN e retorna o mapeamento correto.

2023-12-12 14:15 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +      ],
Isso, com a MultiWAN, mudou um pouco isso. A gente pega todos as WANs que a gente encontrar na árvore. Eu digo isso para não ter que alterar a provision, que é um ponto delicado. E a gente mapear o campo da LAN como os outros campos com `*` e nas `permissions` a gente ter quais índices puxar dentro da árvore. Nesse ponto das `permissions`, acredito que a gente já estaria no Flashman

2023-12-12 14:46 UTC, GThurler commented on controllers/external-genieacs/cpe-models/base-model.js
> +      ],
Os fields não podem ser arrays, para permanecer no padrão do resto co código. O certo é mapear com `*` mesmo, e usar algum artifício pelo código para dar replace com os índices apropriados. Provavelmente vai ter que incluir uma variável (esta sim um array) para informar o índice de cada porta. Como já vai ter um array acho redundante armazenar junto o número de portas, afinal deveria ser o length do array

2023-12-12 17:45 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +      ],
Quem pega o primeiro, ou o último, campo com asterístico é a provision. O flashman já recebe colapsado. O flashman não chega a ver todos os dados relacionados ao asterístico. Todas os campos com asterístico esperam receber apenas um único valor. Esse é o padrão do flashman. Como o flashman recebe apenas um único valor, não tem artifício que ele possa fazer para transformar um único campo com asterístico em um grupo de valores. Colocando um array em `fields.lan.status` cria-se uma forma de definir que um grupo de valores precisa ser retornado. Além do mais, o asterístico pode, em algumas CPEs, incluir campos além das portas lan que estão sendo mapeadas.

A parte da provision que pega os dados de MultiWAN faz algo completamente diferente da parte que pega dados da LAN. Se quisermos replicar a mesma lógica da MultiWAN para os dados de LAN, teriamos que refatorar toda a recepção de dados da LAN do tr069 no flashman. A lógica da MultiWAN retorna um pedaço da árvore da CPE em uma estrutura de objetos aninhados. A lógica da LAN apenas faz uma estrutura de dados chave-valor, onde todo campo com asterístico é reduzido a apenas um único valor, e a recepção de cada um desses dados, no flashman, espera que seja um único valor.

2023-12-12 18:42 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +      ],
Vou usar a parte do código da provision da MultiWAN diretamente no campo mapeado do LAN status e depois eu vejo como trato isso.

2023-12-19 15:06 UTC, lucasperovani requested changes

2023-12-19 15:17 UTC, GThurler commented on public/javascripts/table_anim.js
> +                )+
Sem um print fica difícil avaliar, me ajuda aí rs

2023-12-19 15:21 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +                )+
![Captura de tela de 2023-12-19 12-20-28](https://github.com/anlix-io/flashman/assets/11947466/9de14ca2-4ffc-48ed-8636-2ec0f0ada01a)

2023-12-19 16:54 UTC, cassiohg commented on controllers/acs_device_info.js
> +    }
A função `extractPathFromObjcetTree` substitui os indices de todos os wildcards e passa pela árvore uma vez só. Ela executa o `for` dentro dela. Essa lógica foi colocada dentro de uma função pra poder ser reaproveitada.

2023-12-19 17:16 UTC, lucasperovani commented on controllers/acs_device_info.js
> +    }
Okay, mas me parece algo mais difícil do que é necessário. É necessário mesmo fazer todo um cálculo em cima do campo e fazer isso de forma recursiva sendo que só precisa fazer um `replace`? Além disso tem funções que todos os parâmetros estão recebendo um objeto com `writable` e `value` e o `status` está o formato igual como vem direto do CPE.

2023-12-19 17:19 UTC, cassiohg commented on controllers/acs_device_info.js
> +};
O motivo é deixar uma função que pode ser usada no futuro pra retornar valores de um path com um ou mais wildcards, passando uma vez só pela árvore toda, retornando todos os valores do path de uma só vez. Não temos uma função dessa ainda. A única que tem retorna um único valor de cada vez.
  
  O typo no nome da função eu consertei aqui.

2023-12-19 17:26 UTC, cassiohg commented on public/javascripts/table_anim.js
> +                )+
Não sei se dá pra assumir que os índices na árvore tr069 estão corretamente ordenados. Melhor não dar nomes às portas pra não termos que ficar homologando índice de árvore com a ordem das portas.

2023-12-19 17:28 UTC, cassiohg commented on controllers/acs_device_info.js
> +  }
A única logica que tem igual é a extração do campo `_value`. A string vazia só ta aí pq coloquei, no mongoose, que o campo é String, se não fosse por isso ficaraia `undefined` mesmo. Mas sinceramente, não testei com `undefined` pra saber se o mongoose aceita. O resto do código, front end inclusive, aceita qualquer coisa que não seja `'NoLink'`, `'Up'` ou `'Down'`.

2023-12-19 17:34 UTC, lucasperovani commented on controllers/acs_device_info.js
> +};
Eu entendo, mas eu acho que a função ficou complexa e parece que está usando um tiro de bazuca contra uma mosca rsrs. Para a WAN a gente não precisou fazer isso porque a gente registra quais os indexes do TR-069...

2023-12-19 17:36 UTC, cassiohg commented on controllers/acs_device_info.js
> +    }
Criar esse código é mais difícil mas ele executa com mais facilidade. A complexidade algoritimica dele é menor do que fazer um `for` e chamar o `getFieldFromGenieData` pra cada índice.

2023-12-19 17:36 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +                )+
Mas se colocar uma ordem diferente no array de índices, teoricamente ele deveria ordenar, não?

2023-12-19 17:55 UTC, lucasperovani commented on controllers/acs_device_info.js
> +    }
Sobre a complexidade, eu não quis dizer que ficaria mais fácil se simplesmente fizesse a mesma lógica só que com um `for`. Mas eu não consigo ver isso sendo mais fácil que um `for`, `replace` e `getFieldFromGenieData`

2023-12-19 19:52 UTC, cassiohg commented on public/javascripts/table_anim.js
> +                )+
Sim, ordena. O problema é verificar ordem em todos os modelos de CPE.

2023-12-19 19:55 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +                )+
A gente vai precisar verificar isso. Imagina a pessoa colocando o cabo na porta LAN 2 e aparecendo na 4 no front. Acredito que será um tanto quanto estranho isso. Mas imagino que a maioria dos CPEs irá seguir alguma ordem. Mas sim, de fato a gente vai precisar verificar essa ordem

2023-12-19 20:38 UTC, cassiohg commented on controllers/acs_device_info.js
> +};
O código da WAN tem mais complexidade de código e mais complexidade algoritmica. O código da WAN usa:
`controllers/handlers/acs/wan/list_parser.js > parseTR098Data()`
Que, além de ficar rechamando `cpe.getModelFields()` e `cpe.modelPermissions()` dentro de loop, fica manipulando o retorno das seguintes funções pra poder acessar campos com 2 wildcards.
`controllers/handlers/util.js > traverseNestedKey()`
`controllers/handlers/util.js > replaceWildcardsOnField()`
Que precisam ser usados em conjunto pra encontrar os dados de 1 campo definido construido pela provision.
Essa função encontra sozinha o que é encontrado usando essas 3 funções.

Se vc considera essa função um canhão, como ela é mais fácil de usar e custa menos pra usar, vou ficar com o canhão.

2023-12-19 20:44 UTC, cassiohg commented on controllers/acs_device_info.js
> +    }
É, eu fiz um código mais difícil de elaborar pro benefício de todos nós.

2023-12-19 21:15 UTC, lucasperovani commented on controllers/acs_device_info.js
> +};
Cassio, calma, não estou querendo colocar o que eu acho sobre o teu código. Mas eu achei a função overkill porque a gente não precisa disso para agora e ela parece estar fazendo muito mais coisas do que é necessário, como por exemplo o `undefined` dentro do `indexes` do exemplo que fez ou a validação do `path` para array ou string. Entendo que você já fez pensando no futuro, e isso é legal. Mas estou levantando 2 pontos aqui: Será que a função não está tão genérica que a sua manutenção se tornará difícil no futuro (sei disso por experiência com próprio código que eu escrevi); Essa função é necessária para algo que a gente só precisava dar um `replace` nesse momento?

Outro motivo de eu estar falando isso é que eu não entendi todos os casos que você imaginou, talvez comentários dentro da função explicando passo a passo me ajudaria a entender o que você quis tratar e onde se encaixa...

Mas acho que deveria manter pelo menos o padrão das outras funções de receber o objeto `{value, writable}` ao invés de todo o objeto do ACS. Isso pode causar confusão no futuro para a gente

2023-12-20 17:15 UTC, cassiohg commented on controllers/acs_device_info.js
> +};
> como por exemplo o `undefined` dentro do `indexes`

Não ficou claro no exemplo que o `undefined` retornou todos os indícies na altura da árvore onde fica o `'*'` do path?

> a validação do `path` para array ou string.

Não tem validação, tem conversão de string com pontos pra array the hops na árvore.

> Será que a função não está tão genérica que a sua manutenção se tornará difícil no futuro

Essa função resolve um problema conceitual de estrutura de dados em árvore. Não tem que dar manutenção nela, porque ela é agnóstica de regra de negócio.

> Essa função é necessária para algo que a gente só precisava dar um `replace` nesse momento?

Não estava afim de fazer um código não reutilizável onde claramente eu poderia fazer um reutilizável sem tanta dificuldade.

> Outro motivo de eu estar falando isso é que eu não entendi todos os casos que você imaginou, talvez comentários dentro da função explicando passo a passo me ajudaria a entender o que você quis tratar e onde se encaixa...

Vou comentar o passo a passo da função.

> Mas acho que deveria manter pelo menos o padrão das outras funções de receber o objeto `{value, writable}` ao invés de todo o objeto do ACS. Isso pode causar confusão no futuro para a gente

Ela não foi feita pra traduzir nada que veio do ACS, só pra pra retornar o objeto criado pelo ACS, que tá nas folhas da árvore tr069 retornada pelo ACS. Se vc quiser, vc pode traduzir no seu código, assim como o `getFieldFromGenieData()` usa uma função que retorna os dados de uma árvore e depois traduz.

2023-12-20 19:03 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +                )+
> A questão da ordem já está implícita pela ordem no front - mesmo que você não explicite "Porta 1/2/3" a pessoa vai assumir que essa é a ordem, e isso pode gerar confusões como o Lucas apontou. Por hora a gente pode assumir o bom senso de que a ordem física é a ordem da árvore - o fix para isso pelo que entendi seria trivial, só trocar a ordem dos índices no array (ex.: [1, 2, 3, 4] vira [4, 3, 2, 1]).
> 
> Existe um tooltip ou algo que mostre o que verde/cinza/vermelho significa? Talvez fique mais claro se mostrar o status explicitamente ao lado de cada ícone, similar ao que fazemos na tabela de WANs, por exemplo. Visualmente ficaria algo assim:
> 
> ```
> [G] Up      [G] Up      [R] Down    [ ] NoLink
> ```
> 
> Basicamente cada `fa-square` ficaria dentro de um `col-3`, e todos dentro de um `row`. Se aparecer um CPE com 5+ portas LAN aí a gente pode repensar o design disso no front, talvez forçar a divisão em várias linhas.

Escolher o `col` não deve ser tão difícil, `12 / array.length`. Mas não é algo que seria preciso ver agora de fato...

2023-12-20 20:02 UTC, GThurler commented on public/javascripts/table_anim.js
> +                )+
> Escolher o col não deve ser tão difícil, 12 / array.length. Mas não é algo que seria preciso ver agora de fato...

Cuidado que `col` precisa ser um inteiro. O tamanho do `col` pode ser fixo em 3, pra sempre alinhar tudo do mesmo jeito:

```
[G] Up   [G] Up   [G] Up   [G] Up     (col-3 com 4 elementos)
[G] Up   [G] Up                       (col-3 com 2 elementos)
[G] Up            [G] Up              (col-6 com 2 elementos)
```

2023-12-23 01:45 UTC, cassiohg commented on public/javascripts/table_anim.js
> +                )+
![20231222-224404](https://github.com/anlix-io/flashman/assets/2954166/e7691b54-4fc1-4e71-a48b-ba1cbfd8ba43)
@GThurler @lucasperovani

2023-12-27 11:01 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +                )+
Poxa, seria bem legal se colocasse esse pedaço como uma outra função, que nem fez com o Wi-Fi power, para a gente ir separando o table anim

2023-12-27 11:31 UTC, lucasperovani commented on controllers/acs_device_info.js
> +    }
Mas poxa Cassio, para essa feature a gente só precisava dar um `replace` no `field` para os indexes que a gente anotou. Além disso, a gente tem funções que fazem quase a mesma coisa que essa função no arquivo `controllers/handlers/utils.js`

2023-12-27 11:38 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +                  '<div class="md-form input-entry input-group">'+
Quando tem apenas 3 portas LAN, 1 NoLink, 2 Up respectivamente, o texto está ficando quebrado. Imagino que seja o `input-group`

2023-12-27 12:54 UTC, cassiohg commented on public/javascripts/table_anim.js
> +                )+
Separei em uma função.

2023-12-27 13:55 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +              '<div class="row py-2 my-2 mx-2 w-100">'+
É estranho precisar colocar o `w-100` teoricamente o `row` deveria fazer isso. O que pode estar acontecendo é um `row` ou `col` atrás do outro, que aí ele se perde. Aí precisa intercalar... Vou tentar analisar isso melhor

2023-12-27 14:13 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +              '<div class="row py-2 my-2 mx-2 w-100">'+
Isso parece ser culpa mesmo do `input-group`. Ele tenta agrupar os itens juntos:
[Bootstrap - input-group](https://getbootstrap.com/docs/4.0/components/input-group/)

No caso então, o `w-100` não é necessário, mas é só remover esse `input-group`

2023-12-27 16:53 UTC, cassiohg commented on public/javascripts/table_anim.js
> +              '<div class="row py-2 my-2 mx-2 w-100">'+
Isso foje do padrão de espaçamento. Se fizer assim, esse componente vai ter que copiar todos os espaçamentos.

2023-12-27 17:03 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +              '<div class="row py-2 my-2 mx-2 w-100">'+
Não entendi o motivo dele ter que copiar todos os espaçamentos. Esse `input-group` não está apenas agrupando os itens? Quando eu removi ele, ficou do mesmo que o `w-100`, pelo menos ao meu ver

2023-12-27 19:02 UTC, cassiohg commented on public/javascripts/table_anim.js
> +              '<div class="row py-2 my-2 mx-2 w-100">'+
O `input-group` mexe com espaçamentos internos. Retirando ele, o componente fica achatado. Compensei isso mexendo em `div` interna.

2023-12-29 18:01 UTC, lucasperovani approved these changes

2024-01-03 18:52 UTC, GThurler approved these changes

2024-01-03 19:10 UTC, merged