Feature/flashify kpi on ci
anlix-io/flashman pull request #960
Opened 2023-12-08 19:53 UTC by rilpires

Não mergear! Mudei o actions do pull pra dev só pra fazer um teste...

2023-12-08 20:15 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +if (process.argv.includes('flashify_kpi')) {
Isso aqui só é executado quando for executado o "npm run flashify_kpi"

2023-12-11 14:04 UTC, CodiumAI-Agent commented
## PR Analysis

- 🎯 **Main theme:** Enhancing the flashify model and adding KPI generation
- 📝 **PR summary:** This PR enhances the flashify model by adding more functions and fields. It also introduces a new feature to generate Key Performance Indicators (KPIs) for the flashify model. The KPIs are saved in a markdown file and included in the GitHub release artifacts.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 4, because the PR introduces a significant amount of new code and logic, which requires careful review to ensure correctness and efficiency.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** The PR is generally well-structured and the changes are logically grouped. However, it would be beneficial to add tests to ensure the correctness of the new functions and KPI generation. Additionally, consider adding more comments to explain the logic behind the new code, especially for the KPI generation.


- <details><summary> 🤖 Code feedback:</summary>


  - **relevant file:** ``controllers/external-genieacs/cpe-models/flashify-model.js``  
   **suggestion:** Consider breaking down the `generateKpi` function into smaller, more manageable functions. This will improve readability and maintainability of the code. [important]  
   **relevant line:** [const generateKpi = function() {](https://github.com/anlix-io/flashman/pull/960/files#diff-e18f694992c0ca8a9f9099e0c3270aeedb179f4327006a8babd9f1ec6f2923bbR2250)  


  - **relevant file:** ``controllers/external-genieacs/cpe-models/flashify-model.js``  
   **suggestion:** It seems like the `wontDoFunctions`, `wontDoFields`, and `wontDoPermissions` sets are hardcoded. If these sets are expected to change frequently, consider moving them to a configuration file or environment variables. This will make it easier to update them without modifying the code. [medium]  
   **relevant line:** [const wontDoFunctions = new Set([](https://github.com/anlix-io/flashman/pull/960/files#diff-e18f694992c0ca8a9f9099e0c3270aeedb179f4327006a8babd9f1ec6f2923bbR10)  


  - **relevant file:** ``controllers/external-genieacs/cpe-models/flashify-model.js``  
   **suggestion:** The `flashifyModelConstructor` function has been modified to accept a new parameter `javascriptOverride`. Make sure to update all calls to this function throughout the codebase to include this new parameter. [important]  
   **relevant line:** [flashifyModelController.flashifyModelConstructor = function(](https://github.com/anlix-io/flashman/pull/960/files#diff-e18f694992c0ca8a9f9099e0c3270aeedb179f4327006a8babd9f1ec6f2923bbR1767)  


  - **relevant file:** ``.github/workflows/on-merge-to-master.yml``  
   **suggestion:** The `flashify_kpi` command is being run without any error handling. Consider adding error handling to ensure that the workflow doesn't fail if the command encounters an error. [important]  
   **relevant line:** [run: npm run flashify_kpi > flashifyKpi.md](https://github.com/anlix-io/flashman/pull/960/files#diff-d846b34e453fdd78b0c9e84ce60d121b7c5d72e85d1f0df36cbff6150329d006R117)  

</details>


### How to use

 <details> <summary> Instructions</summary>

> Tag me in a comment '@CodiumAI-Agent' and add one of the following commands:  
> **/review**: Request a review of your Pull Request.   
> **/describe**: Update the PR title and description based on the contents of the PR.   
> **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> **/ask \<QUESTION\>**: Ask a question about the PR.   
> **/update_changelog**: Update the changelog based on the PR's contents.   
> **/add_docs**: Generate docstring for new components introduced in the PR.   
> **/generate_labels**: Generate labels for the PR based on the PR's contents.   
> see the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.

>To edit any configuration parameter from the [configuration.toml](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml), add --config_path=new_value.  
>For example: /review --pr_reviewer.extra_instructions="focus on the file: ..."    
>To list the possible configuration parameters, add a **/config** comment.   

</details>

2023-12-11 15:31 UTC, lucasperovani requested changes
Acho válido o que o Codium pontuou de separar a função `generateKpi` em funções menoreszinhas e colocar mais comentário. Adicionar JSDoc é uma boa também. Seria legal ter esse KPI em um arquivo a parte para separar a lógica de fato do flashify da métrica, se for possível

2023-12-11 15:31 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      timesInherited: timesInherited,
Não foi trocado não? `baseValue !== value` incrementa o `timesInherited`, enquanto que o `differentValues` é todo o `allFields`?

2023-12-11 15:31 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  });
Acredito que as lógicas sejam similares, só precisando passar o `getModelFields` ou `jsModel.modelPermissions`. Seria legal separar numa função

2023-12-11 15:31 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  }).join(`\n`)
Poxa Romeu, tem como quebrar essa linha para não desabilitar o linter

2023-12-11 15:31 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +if (process.argv.includes('flashify_kpi')) {
Seria legal colocar um comentário para isso, pode não ser intuitivo quando outra pessoa for ver

2023-12-11 15:31 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +${Array.from(baseModelFunctions.keys()).map(function(k) {
Agora função é `k`? FunçãoFunçãoFunçãoFunção (kkkk)

2023-12-11 17:10 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +const generateKpi = function() {
Eu não queria ter tirado daqui antes pq eu vou ter q exportar coisas q eu não exportava e não faz sentido exportar, mas vou tirar

2023-12-11 18:00 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      };
Cara, eu fiz mas achei isso bem difícil, e achei q ficou mais confuso ainda abstrair essa lógica pra modelFields e modelPermissions

2023-12-11 18:40 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      timesInherited: timesInherited,
Tá certo, não entendi a sua dúvida.
`allFields.size` é o size de um `Set`, então ele tem todos os diferentes valores existentes
`timesInherited` é incrementado sempre que o campo é sobrescrito, independente se foi com um valor já observado antes ou não

2023-12-11 18:41 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  }).join(`\n`)
😭😭😭😭

2023-12-11 18:41 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  }).join(`\n`)
Isso em linha quebrada vai ser a coisa mais ilegível de todas mas beleza

2023-12-11 18:53 UTC, rilpires commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +${Array.from(baseModelFunctions.keys()).map(function(k) {
![image](https://media1.tenor.com/m/aZ1PR9DpnOYAAAAC/annoyed-disappointed.gif)

2023-12-11 21:29 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +  }).join(`\n`)
Naah, ficou bonito

2023-12-11 21:30 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/flashify-model.js
> +      };
Tranquilo, se ficou difícil, pode deixar assim, significa que outra pessoa terá dificuldade futuramente ao tentar ler

2023-12-11 21:43 UTC, lucasperovani approved these changes

2023-12-11 21:43 UTC, merged