Feature/enable lan dhcpv6
anlix-io/flashman pull request #965
Opened 2023-12-11 20:35 UTC by RaphaelAN

Adiciona campo que habilita o uso de DHCP IpV6 na lan

2023-12-12 20:38 UTC, lucasperovani requested changes

2023-12-12 20:38 UTC, lucasperovani commented on controllers/device_list.js
> +        util.returnObjOrEmptyStr(content.lan_dhcp_ipv6_enable);
Essa função vai te retornar o valor ou uma `string`. Seria legal validar se o tipo veio de fato `boolean`. Se vier algo inválido, não setar na base

2023-12-14 22:16 UTC, rilpires commented on controllers/acs_device_info.js
> +  }
Pra explicar um pouco melhor, é pra acrescentar o campo apropriado do `lanDhcpIpv6Enable` dentro do `changes` quando o hardReset for true

2023-12-14 22:18 UTC, rilpires commented on controllers/acs_device_info.js
> +        hasChanges = true;
faltando o changes!

2023-12-20 00:10 UTC, rilpires requested changes
Eu testei e já vi que funciona a edição do campo pelo front, show. Mas existe uma lógica que não está funcionando: no `syncDeviceData`, ele não está recebendo a informação no `data`.
Por dois motivos:
        1 - É preciso ser inserido no `acs_device_info.fetchSyncResult` a lógica que informa pra CPE quais os campos serem 'syncados'. Lá, na parte de lan, só estão o `lan.router_ip` e `lan.subnet_mask`.
        2 - no syncDeviceData, pra receber a informação do dhcp_ipv6_enable, você está checando data. lanDhcpIpv6Enable , mas esse valor precisa estar no nosso padrão de "árvore changes" (que é semelhante ao nosso getModelFields(), com algumas pequenas modificações quando é multiwan/multilan), ou seja, dentro do syncDeviceData você vai buscar por `data.dhcp_ipv6_enable`

2023-12-20 00:11 UTC, rilpires commented on controllers/acs_device_info.js
> +  if (data.lan.lanDhcpIpv6Enable) {
dhcp_ipv6_enable

2023-12-28 19:13 UTC, rilpires commented on controllers/acs_device_info.js
>          hasChanges = true;
Aqui, o comportamento de quando é hardReset não está fazendo nada diferente, pois você manteve a alteração no `device.lan_dhcp_ipv6_enable` (banco de dados), e por causa disso o `changes.lan.dhcp_ipv6_enable` ficou igual ao `data.lan.lanDhcpIpv6Enable` (mesmo valor de entrada)

2023-12-28 19:16 UTC, rilpires requested changes
Ver o comentário que inseri na linha do `if (hardReset)`, é uma lógica que ficou faltando e é importante de se ter entendido...

2024-01-03 17:49 UTC, closed without merging

2024-01-03 17:49 UTC, GThurler commented
Seguindo o comentário do Romeu que ficou lá no Trello: foi constatado que a flag de DHCPv6 Enable que tem na árvore simplesmente não funciona (dispositivos continuam recebendo IPv6), e não faz sentido gerenciar algo que não tem o impacto desejado. Isso deveria ter sido avaliado lá quando o card foi criado, antes de ser delegado para alguém, mas por problemas de prioridade da Ligga isso ficou num limbo. Vou fechar o PR porque a funcionalidade não tem sentido no contexto dos modelos da Ligga.