Static WAN IP collecting in sync device operation
anlix-io/flashman pull request #978
Opened 2023-12-14 17:55 UTC by rilpires

Com isso, o syncWanData preenche o campo connection_type apropriadamente com "static" quando a conexão é de fato "Static"

2023-12-14 23:11 UTC, GThurler commented on controllers/handlers/acs/wan/config.js
> +      }
Dado que essa lógica aqui ficou muito parecida com a do TR-181, e ambas se baseiam na chamada para `readIpv4AddressingType` (ou no resultado dela), faz sentido essa lógica estar dentro de `readIpv4AddressingType`, que passaria a retornar uma string de um enum (no caso, "dhcp" e "static")

2023-12-18 14:53 UTC, rilpires commented on controllers/handlers/acs/wan/config.js
> +      }
donei

2023-12-18 15:57 UTC, GThurler commented
@rilpires Depois dá uma olhada nos commits que eu fiz, a parte de máscara da WAN estava com um legado zoado, tanto no base-model quanto no schema da base. Tinha um bugzinho na parte do DNS também que eu já ajeitei, mas enfim

2023-12-19 17:38 UTC, GThurler requested changes

2023-12-19 17:38 UTC, GThurler commented on controllers/handlers/acs/wan/ipv4.js
> +      addressingType = '';
O default tem que ser DHCP mesmo, o que pode é omitir o console.warn quando foi string vazia

2023-12-19 18:54 UTC, GThurler approved these changes

2023-12-19 18:56 UTC, merged