Feature: enable/disable wan
anlix-io/flashman pull request #980
Opened 2023-12-14 23:07 UTC by gabrielxfs

2023-12-21 23:38 UTC, GThurler requested changes
Ainda não rodei o código na minha máquina pra avaliar as mensagens e detalhes do front, vou ver isso amanhã. Deixo aqui meu review só da parte do código por enquanto

2023-12-21 23:38 UTC, GThurler commented on controllers/external-genieacs/cpe-models/base-model.js
> +      allowEditWanEnable: true, // can edit wan enable at flashman's wan tab
Po, eu trocaria o default pra false e só liberaria nos modelos da Ligga agora. Ajudaria a mitigar um pouco os provedores podendo fazer besteira

2023-12-21 23:38 UTC, GThurler commented on controllers/multiwan/permissions.js
> +  permissions.allowEditEnable = devicePermissions.grantWanEnableEdit;
Fiquei pensando aqui se não vale a pena ter uma permissão de usuário pra isso também, já que pode ser algo trágico editar isso por acidente. Sei que não estava no card, mas é algo que percebi só agora lendo o código

2023-12-21 23:38 UTC, GThurler commented on controllers/multiwan/types.js
> +      // If mtu is not empty and has permission and is invalid
Comentário saiu com o copy/paste do mtu

2023-12-22 15:21 UTC, gabrielxfs commented on controllers/multiwan/permissions.js
> +  permissions.allowEditEnable = devicePermissions.grantWanEnableEdit;
Ao invés de só criar uma grant só para o EditWanEnable, talvez usar a grant grantWanAdvancedInfo seja uma boa.

2023-12-22 17:28 UTC, GThurler commented on controllers/multiwan/permissions.js
> +  permissions.allowEditEnable = devicePermissions.grantWanEnableEdit;
Acho uma boa também

2023-12-22 19:24 UTC, GThurler requested changes
Sei que não estava no card, mas testando aqui achei melhor a gente capar o disable da WAN se TR-069 é um dos serviços associados. Ou se a gente não tem a lista de serviços ("Sem informações" no front). Vai evitar uma possível dor de cabeça para o suporte.

Um ponto adicional que peguei durante os testes: o disable de uma WAN PPPoE no F670L V9 não funciona, ele manda a task pra CPE mas a WAN fica UP eternamente. Tem que passar pelos modelos e avaliar se o disable de uma WAN PPP funciona de fato, e capar a opção do front.

2023-12-22 19:24 UTC, GThurler commented on public/locales/pt/translation.json
> +  "wanInterfaceBaseMessage": "Desativar esta interface poderá {{whichMessage}} tem certeza que deseja realizar esta ação?",
Como a opção pra TR-069 vai ser capada, talvez limitar isso aqui a uma frase customizada só para o serviço de internet:
```suggestion
  "disableWanInternetMessage": "Desativar esta interface deixará o cliente sem acesso à internet. Tem certeza que deseja desativá-la?",
```
E se for desabilitar uma WAN que só tenha voip / iptv, não precisaria mostrar um alerta

2023-12-27 22:28 UTC, GThurler commented
Por mim está aprovado agora, aguardo só o posicionamento do @gabrielxfs se a validação no backend vai entrar neste PR ou em outro pra dar o approve e mergear

2023-12-28 15:47 UTC, GThurler approved these changes

2023-12-28 15:53 UTC, merged