Feature/collecting wifi power
anlix-io/flashman pull request #981
Opened 2023-12-15 01:11 UTC by cassiohg

2023-12-19 19:36 UTC, lucasperovani requested changes

2023-12-19 19:36 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +          '</div>';
Seria legal converter essa lógica para um widget e colocar a lógica de power do firmware para usar esse widget também. O bom de fazer isso que aos poucos a gente vai aliviando o table-anim

2023-12-19 19:36 UTC, lucasperovani commented on public/locales/en/translation.json
> +  "willOnlyAcceptValueWifiPowerTr069": "$t(willOnlyAcceptValues, {\"values\": \"20%, 40%, 60%, 80% and 100%\"})",
Esses valores eles não são setados conforme cada CPE?

2023-12-19 19:36 UTC, lucasperovani commented on test/black-box/device_list.test.js
> +      expect(res.statusCode).toBe(200);
Seria legal verificar ou alterar esse valor antes, para não ter o caso que o simulador suba com esse exato valor e a gente não saiba se de fato o teste foi válido

2023-12-20 17:37 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/huawei-hg8245.js
> +  permissions.wifi.power2 = true;
Lembra que não temos como testar mas se ele não é dualband, deve ser porque só tem 1 banda e a banda é 2.4GHz

2023-12-20 18:53 UTC, cassiohg commented on controllers/acs_device_info.js
> +    }
Não tem nenhuma cpe que usa esse valor como string e de qualquer modo o mongoose converte de string pra número. Se for o caso de encontrarmos alguma cpe que use uma string num formato não conversível pelo mongoose, teria que fazer uma parser pra essa string e isso seria um problema maior do que ele é de fato.
É importe gravar undefined pra não parecer que o dado antigo é atual.

2023-12-20 18:53 UTC, cassiohg commented on controllers/acs_device_info.js
> +    }
Adicionei a checagem de permissão.

2023-12-20 18:53 UTC, cassiohg commented on public/javascripts/device_validator.js
> +        valid: [100, 80, 60, 40, 20].includes(Number(power)),
As opções vem da homologação e ficam nas features de wifi do modelo.

2023-12-20 18:53 UTC, cassiohg commented on models/device.js
> +      25, 50, 75, 100, 20, 40, 60, 80,
Não entendi. Isso nem deveria ter um enum eu só preenchi pra não tirar o enum.

2023-12-20 18:57 UTC, cassiohg commented on public/javascripts/table_anim.js
> +            ((device.use_tr069 || grantWifiPowerHiddenIpv6Box) &&
`grantWifiPowerHiddenIpv6Box` está sendo checado apenas para firmware.
`grantWifi2Power` e `grantWifi5Power` está sendo checado em outro ponto do código.

2023-12-20 19:56 UTC, cassiohg commented on public/locales/en/translation.json
> +  "willOnlyAcceptValueWifiPowerTr069": "$t(willOnlyAcceptValues, {\"values\": \"20%, 40%, 60%, 80% and 100%\"})",
É verdade, isso deveria ser um parâmetro. Fiz essa modificiação.

2023-12-20 19:58 UTC, cassiohg commented on public/javascripts/table_anim.js
> +          '</div>';
O thurler nao gosta que mexa em partes do código que não estão ligadas ao pull request a não ser que sejam coisas tão pequenas que não precisem ser testadas.

2023-12-20 20:05 UTC, cassiohg commented on test/black-box/device_list.test.js
> +      expect(res.statusCode).toBe(200);
Passei a ler o valor antes de alterar pra alterar pra algo diferente.

2023-12-21 11:57 UTC, lucasperovani commented on models/device.js
> +      25, 50, 75, 100, 20, 40, 60, 80,
Pois é, eu também acho que não deveria ser um enum. Vou ver aqui se a gente consegue remover esse enum sem problemas...

2023-12-21 12:00 UTC, lucasperovani commented on controllers/acs_device_info.js
> +    }
Sim, a minha ideia é a gente já ter essa função de parser pra caso a gente precisar no futuro, não ter que voltar ao código para implementar, mas já ter um stub para futuramente a gente poder usar, sabe? Estou imaginando que bão existir CPEs que vão usar dbm ao invés de % ou alguma outra conta doida...

2023-12-21 12:02 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/huawei-hg8245.js
> +  permissions.wifi.power2 = true;
Desculpa, não tinha visto a flag de `dualband`. Era só para confirmar mesmo

2023-12-21 12:06 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +          '</div>';
Isso é estranho porque ele mesmo alterou uma parte da WAN para jogar como um widget. O código foi praticamente copiado de um lado para o outro mas ele moveu esse código. Seria muito bom a gente fazer isso para diminuir o table-anim. Acredito que isso nos ajudaria no futuro. @GThurler o que acha?

2023-12-21 12:53 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +            ((device.use_tr069 || grantWifiPowerHiddenIpv6Box) &&
Esse pedaço adiciona a validação do front... O botão de salvar está crashando no WS7000-42 (AX2S), acredito que porque ele não possua o `power` e a validação estar sendo realizada para ele também...

2023-12-21 13:57 UTC, lucasperovani commented
Eu refiz o review, algumas coisas ainda continuam (como device_validator para o firmware), outras mantive para entender melhor com o Thurler. Adicionei mais uns 2 comentários do que observei nessa segunda passada

2023-12-21 15:29 UTC, GThurler commented on public/javascripts/edit_device.js
> +      {style: 'long', type: 'conjunction'});
Não é mais fácil a string de tradução lá na frente ser algo tipo "Valor inválido. Os valores válidos são: [${values}]", onde `values` aqui seria só os valores separados por vírgula? Porque isso aí pra mim faz mais sentido ser embutido lá no framework de tradução, e acho meio desnecessário toda essa lógica a mais

2023-12-21 15:30 UTC, GThurler commented on models/device.js
> +      25, 50, 75, 100, 20, 40, 60, 80,
Pode tirar o enum sem problemas, mas realmente se for manter o enum tem que ordenar em ordem crescente: `20, 25, 40, 50, 60, 75, 80, 100`

2023-12-21 15:55 UTC, cassiohg commented on public/javascripts/table_anim.js
> +            ((device.use_tr069 || grantWifiPowerHiddenIpv6Box) &&
Já imagino o que seja. A validação ta querendo usar um campo que não foi colocado no html porque ele não tem `grantWifi2Power` e `grantWifi5Power`. Consertei aqui.

2023-12-21 16:15 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +    case 'wifi5-power':
Estou deixando uma versão de conversão, inócua, apenas para existir um lugar certo para refazerem.

2023-12-21 16:15 UTC, cassiohg commented on models/device.js
> +      25, 50, 75, 100, 20, 40, 60, 80,
Removi o enum.

2023-12-21 16:20 UTC, cassiohg commented on public/javascripts/table_anim.js
> +          '</div>';
Não é igual. Só é muito parecido, mas não é igual.

2023-12-21 16:26 UTC, cassiohg commented on public/javascripts/table_anim.js
> +          '</div>';
> Isso é estranho porque ele mesmo alterou uma parte da WAN para jogar como um widget.
Mas aí foi ele que fez. Eu já pedi pra mudar identação e ele vetou.
Mas como ele ta falando que pode fazer...

2023-12-21 16:36 UTC, GThurler commented on public/javascripts/table_anim.js
> +          '</div>';
Uma coisa é mudar indentação de um trecho enorme de código, quando a alteração deveria ser pequena. Outra é relocar o código que está sendo refatorado para outro arquivo, ou alterar o legado pra evitar duplicar o código do widget do front, como é o caso aqui.

Só reiterando que o importante é evitar duplicar o HTML do dropdown de potência do wi-fi, o do firmware é igual ao do TR-069, salvo pelos valores das opções. E o código do TR-069 atende perfeitamente às necessidades do firmware. Agora, se vai separar isso num widget em outro arquivo, pra aproveitar que está mexendo nisso, tanto faz.

2023-12-21 17:02 UTC, cassiohg commented on public/javascripts/edit_device.js
> +    genericValidate(power, func, errors.power);
Consertei isso.

2023-12-21 17:07 UTC, cassiohg commented on public/javascripts/edit_device.js
> +      {style: 'long', type: 'conjunction'});
Eu estou mantendo o padrão do flashman. Tem certeza que na potencia de sinal wifi o padrão de mensagens fique diferente?

2023-12-21 18:52 UTC, cassiohg commented on public/javascripts/table_anim.js
> +          '</div>';
Inclui o formato do firmware na função.

2023-12-21 19:39 UTC, cassiohg commented on public/javascripts/edit_device.js
> +      {style: 'long', type: 'conjunction'});
Fiz exatamente a mensagem que vc disse.

2023-12-26 12:37 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +            ((device.use_tr069 || grantWifiPowerHiddenIpv6Box) &&
Mas acredito que o `data-validate-wifi-power` não pode aceitar para todos os TR-069 ou para quem tem o `grantWifiPowerHiddenIpv6Box`. Acredito que teria que validar também se possui as novas permissões...

2023-12-26 12:45 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +                : '',
Poxa Cassio, vou te pedir para não colocar 2 ternários um atrás do outro dessa forma, é um pouco confuso, é preferível deixar com os ifs. Você consegue testar o `!isTR069` tanto para o 2.4 GHz quanto para o 5 GHz ao mesmo tempo e facilita a leitura do código

2023-12-26 13:02 UTC, lucasperovani commented on models/device_version.js
> +    grantWifi5AvailablePowers: cpePermissions.wifi.availablePower5,
Cassio, vi que isso ainda não foi adicionado no grant do firmware. A ideia é manter lá também por segurança ou para quando a gente fizer a separação da lógica do firmware...

2023-12-26 13:38 UTC, cassiohg commented on public/javascripts/table_anim.js
> +            ((device.use_tr069 || grantWifiPowerHiddenIpv6Box) &&
O `data-validate-wifi-power` só aceita os tr069 se `isSuperuser || grantWifiInfo >= 1` e as novas permissões estão sendo checadas. O `grantWifiPowerHiddenIpv6Box` está seguindo a mesma regra de antes.

2023-12-26 13:49 UTC, cassiohg commented on models/device_version.js
> +    grantWifi5AvailablePowers: cpePermissions.wifi.availablePower5,
Ah ok. Feito.

2023-12-26 13:49 UTC, cassiohg commented on public/javascripts/table_anim.js
> +                : '',
Ok.

2023-12-26 14:59 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +basicCPEModel.convertWifiPowerFromCpeToFLashman = function(power) {
Poxa, o `'L'` do Flashman ficou maiúsculo 😅️

2023-12-26 15:27 UTC, lucasperovani commented on controllers/acs_device_info.js
> +    }
Muito obrigado Cassio. Sei que é algo meio sem sentido, mas é algo que a gente já está adiantando no futuro...

2023-12-26 15:40 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +basicCPEModel.convertWifiPowerFromCpeToFLashman = function(power) {
Botei min minúsculo.

2023-12-26 17:01 UTC, lucasperovani commented on public/javascripts/table_anim.js
> +            );
Faltou colocar o que dar `replace`

2023-12-26 17:06 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +    case 'wifi5-power':
Muito obrigado Cassio!

2023-12-26 18:57 UTC, cassiohg commented on public/javascripts/table_anim.js
> +            );
Pronto.

2023-12-26 21:07 UTC, lucasperovani approved these changes

2023-12-26 21:07 UTC, merged