Feature/sitesurvey hide btn user permission
anlix-io/flashman pull request #982
Opened 2023-12-18 17:16 UTC by naccaratocarolina

2023-12-19 17:53 UTC, GThurler requested changes

2023-12-19 17:53 UTC, GThurler commented on public/javascripts/show_site_survey_actions.js
> +    SHOW_CHANGE_CHANNEL = $(event.target).data('show-change-channel');
Idealmente isso aqui seria puxado do `row` também, para no mínimo manter coerência. O lance da variável global eu entendo que vai minimizar o diff e simplificar o código, por mim pode deixar. Mas dada as alterações que precisou fazer no table-anim, fica melhor seguir o padrão

2023-12-19 17:53 UTC, GThurler commented on public/javascripts/table_anim.js
> +              '<span $REPLACE-DATA-COLLECTING>&nbsp; $REPLACE_TEXT</span>'+
Conforme comentado, lendo do `row` não precisaria disso aqui

2023-12-19 19:13 UTC, GThurler requested changes
![image](https://github.com/anlix-io/flashman/assets/37554452/6010fb1c-f2d0-4aef-9183-54b992d05c62)
![image](https://github.com/anlix-io/flashman/assets/37554452/933dd14e-4544-41b9-a424-9caa85d1dc7a)
Quando não tem permissão de Flashboard, a permissão de VOIP fica desalinhada. Como foi inserido um novo elemento na 2a coluna, precisa reordenar a permissão de Flashboard com a de VOIP para que as permissões se alinhem à esquerda.

O mesmo problema acontece na visualização de criar uma nova classe de permissões:
![image](https://github.com/anlix-io/flashman/assets/37554452/31dd40a7-81d3-488e-8bc8-20266daa6c60)

O botão de troca de canal não aparece mais para o admin, provavelmente porque o `grant` dele vem false. Lembra que admin não tem role!
![image](https://github.com/anlix-io/flashman/assets/37554452/e5c46a7f-92d2-4452-bc64-464613509557)

2023-12-19 20:16 UTC, naccaratocarolina commented
> ![image](https://private-user-images.githubusercontent.com/37554452/291688695-6010fb1c-f2d0-4aef-9183-54b992d05c62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTcxNzgsIm5iZiI6MTcwMzAxNjg3OCwicGF0aCI6Ii8zNzU1NDQ1Mi8yOTE2ODg2OTUtNjAxMGZiMWMtZjJkMC00YWVmLTkxODMtNTRiOTkyZDA1YzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIwMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ODIzMDU2YWRlMTFiZjY0YjczMDViZDkwNWYzZGIwMmQ0NzQ4YjAxMDBhY2UyZDUzNDYxMWE3MzdhZDFkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2afXzUPEDQBqVY2G8-_y7gNsW53qV3wDY24hr_Bcqq4) ![image](https://private-user-images.githubusercontent.com/37554452/291688391-933dd14e-4544-41b9-a424-9caa85d1dc7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTcxNzgsIm5iZiI6MTcwMzAxNjg3OCwicGF0aCI6Ii8zNzU1NDQ1Mi8yOTE2ODgzOTEtOTMzZGQxNGUtNDU0NC00MWI5LWE0MjQtOWNhYTg1ZDFkYzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIwMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZjQ4NDZkMjI1Y2VlZTYzNGRlZjdiNjE0M2YxNTc0YWJhMGQ5ZDAzYzRlY2MwYThmOWNjOTY0ZTdlMGFlZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ONEs0hIzoLbwvvVHMUJBcJbDRkx6l_1r-Ysx1QLHTUo) Quando não tem permissão de Flashboard, a permissão de VOIP fica desalinhada. Como foi inserido um novo elemento na 2a coluna, precisa reordenar a permissão de Flashboard com a de VOIP para que as permissões se alinhem à esquerda.
> 
> O mesmo problema acontece na visualização de criar uma nova classe de permissões: ![image](https://private-user-images.githubusercontent.com/37554452/291688948-31dd40a7-81d3-488e-8bc8-20266daa6c60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTcxNzgsIm5iZiI6MTcwMzAxNjg3OCwicGF0aCI6Ii8zNzU1NDQ1Mi8yOTE2ODg5NDgtMzFkZDQwYTctODFkMy00ODhlLThiYzgtMjAyNjZkYWE2YzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIwMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OWI2MjdlZDJhMWU2N2MxZGQ1YTFkNzAyNDhlNjcwYjc1YTE4NzcwNjFkY2I0NWZiMmIyNDhmZTkyODQ5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4P3F1EW5LZsSeZfN9FfTsVHRzbQkwAymbRtqRtTwHQo)
> 
> O botão de troca de canal não aparece mais para o admin, provavelmente porque o `grant` dele vem false. Lembra que admin não tem role! ![image](https://private-user-images.githubusercontent.com/37554452/291689706-e5c46a7f-92d2-4452-bc64-464613509557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTcxNzgsIm5iZiI6MTcwMzAxNjg3OCwicGF0aCI6Ii8zNzU1NDQ1Mi8yOTE2ODk3MDYtZTVjNDZhN2YtOTJkMi00NDUyLWJjNjQtNDY0NjEzNTA5NTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIwMTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OWViOWFkOGI2ZWIwM2FjMDkzNjFhNzRjODM1YzZiZjcxZTJlMDNjMzFjODI1ZTRjMDkwZWFhM2MxNTUwZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dm-4xsgrD6-IBjLoWRAZSsx5GSpU02ceSsIPb5IwHPI)

Adicionar nova permissão alinhado:
![image](https://github.com/anlix-io/flashman/assets/41310085/6a593af0-4c48-4a03-8424-70d10f6b36c3)
E as permissões de site survey ficam juntas:
![image](https://github.com/anlix-io/flashman/assets/41310085/d2676bce-828c-4391-aae5-79fa9a65444d)

Permissão de VOIP alinhada a esquerda:
![image](https://github.com/anlix-io/flashman/assets/41310085/a0db50b9-93d9-4a53-889f-246c54a6010b)

2023-12-19 23:25 UTC, GThurler requested changes
As permissões ainda não estão alinhadas quando a permissão de Flashboard for renderizada
![image](https://github.com/anlix-io/flashman/assets/37554452/03d0517a-3edb-4e5e-842e-9874c5c4a7bc)

2023-12-19 23:25 UTC, GThurler commented on views/showroles.pug
> -                      option(value=2)= t('viewAndEdit')
A permissão de voip sumiu do pug?
![image](https://github.com/anlix-io/flashman/assets/37554452/e2a93fc6-3b1d-49c2-b154-b6c7e197d643)

2023-12-21 00:25 UTC, naccaratocarolina commented on views/showroles.pug
> -                      option(value=2)= t('viewAndEdit')
Me enrolei um pouco mas aqui está:
13 x 11, uma vez que as permissões de site survey devem ficar juntas

![image](https://github.com/anlix-io/flashman/assets/41310085/96e7f74f-c4cf-42b1-8e98-2ee511d1e0f8)

2023-12-21 17:21 UTC, GThurler approved these changes

2023-12-21 17:26 UTC, merged