Feature/static wan ip api edit
anlix-io/flashman pull request #987
Opened 2023-12-19 21:53 UTC by rilpires

Testei todos os novos parâmetros numa WAN minha (EG8145-X6, TR098) e todos funcionaram:
```
{
    "wans":[
        {
            "ipv4": {
                "ip": "192.168.88.58",
                "gateway": "192.168.88.1",
                "mask": "255.255.255.0",
                "dns": ["192.168.88.1","192.168.88.111"]
            },
            "_id":"wan_ip_1_1_1"
        }
    ]
}

```
OBS: Quando o IP da WAN que se comunica com o Genie muda, o Genie invariavelmente vai disparar uma fault de "session_terminated"... pq a sessão de antes da alteração do IP usava um IP e depois passou a ser outro - na visão do genie, a sessão antiga sofreu fault. Eu queria colocar uma variável no redis, com validade de só 5 minutos, que se aconteceu uma fault de "session_terminated", ele não loga! Talvez a gente possa só ignorar "session_terminated" mesmo...

2023-12-20 16:43 UTC, rilpires commented
TO-DO: Usar a permission adequadamente pra permitir ou não a edição pela API. Não é pra habilitar pra tr181 pq o default gateway, pelo menos os da TPLink, é uma macarronada de diferença

2023-12-20 18:40 UTC, rilpires commented
Precisei criar os grants correspondentes na role e no deviceVersion

2023-12-21 19:06 UTC, lucasperovani requested changes
Parabéns Romeu! Ficou direitinho, o que sobrou é coisa pequena. Só vou pedir para alterar por causa de algumas melhorias no código que são úteis a gente ter, mas do jeito que está, está funcionando direitinho!

2023-12-21 19:23 UTC, lucasperovani commented
Ahh esqueci de comentar... seria legal ter testes para essa nova adição

2023-12-22 20:28 UTC, rilpires commented
> Ahh esqueci de comentar... seria legal ter testes para essa nova adição
É o q tá faltando

2023-12-28 17:13 UTC, rilpires commented
Já fiz os testes

2023-12-28 23:20 UTC, GThurler approved these changes

2023-12-28 23:22 UTC, merged