Feature/upload front
anlix-io/flashman pull request #995
Opened 2023-12-22 18:30 UTC by naccaratocarolina

![success](https://github.com/anlix-io/flashman/assets/41310085/3dbfef79-1e8e-4d5d-ad45-bd7251f886ed)

![errorview](https://github.com/anlix-io/flashman/assets/41310085/08f2d941-a9a5-4b34-a943-616ee9d036f3)

2023-12-27 23:03 UTC, GThurler requested changes
O botão de teste de upload só deve ser mostrado se a funcionalidade está disponível para o modelo do CPE - idealmente o evento de `open` do modal deveria esconder/exibir o botão de upload de acordo com o que vier lá das permissões do device.

Por uma questão de concordância, o texto de "Clique em um dos botões abaixo" deveria ser trocado para o singular/plural de acordo com isso também. Ou ainda ser reescrito de forma que não referencie a quantidade de opções, por exemplo "Escolha qual teste de velocidade será realizado". Qual vai ficar melhor eu sei lá.

2023-12-27 23:03 UTC, GThurler commented
Tirando o ponto mencionado acima, o código está 100%, tudo funcionou e o front está todo certinho, parabéns! :)

Os gifs no PR também ficaram bem legais, vamos ter que passar a exigir imagens em PRs de front, rs.

2023-12-28 20:14 UTC, naccaratocarolina commented
@GThurler Optei por manter o modal com os textos que já existiam antes da feature para o caso em que o upload nao esta disponivel

2023-12-28 21:40 UTC, GThurler approved these changes

2023-12-28 21:47 UTC, merged