Feature/collecting firewall tr069
anlix-io/flashman pull request #996
Opened 2023-12-22 23:32 UTC by cassiohg

2023-12-27 12:01 UTC, lucasperovani commented on controllers/external-genieacs/cpe-models/base-model.js
> +      firewall: false,
Seria legal ter esses campos no `base-model.md`

2023-12-27 13:06 UTC, cassiohg commented on controllers/external-genieacs/cpe-models/base-model.js
> +      firewall: false,
Esqueci completamente. Coloquei agora.

2023-12-27 13:47 UTC, lucasperovani reviewed
Eu não parei para entender mas ao rodar o sync, a informação do firewall não está sendo atualizada na base. E  a informação de `firewall_enabled`está sendo enviada para todas as CPEs, mesmo que o campo não esteja presente (Testei firmware, AX2S e EG8145V5 sem o campo de `firwall_enabled`). Sobre a tradução, como eu ainda não vi no front, não posso opinar tanto, mas acredito que fique melhor caso seja: `"Habilitar Firewall"`

2023-12-27 13:47 UTC, lucasperovani commented on models/device_version.js
> +    grantFirewallEnabled: cpePermissions.features.firewall,
Vou te pedir para adicionar esse grant também para o firmware na função a abaixo por segurança

2023-12-27 13:53 UTC, lucasperovani requested changes
Esqueci de colocar para pedir alteração aqui no github rs

2023-12-27 17:44 UTC, cassiohg commented on controllers/acs_device_info.js
> +    wan: {}, lan: {}, wifi2: {}, wifi5: {}, common: {}, stun: {}, firewall: {},
Realmente ficou faltando atualizar esse changes. Eu atualizei no `device_list.js` mas não atualizei no `acs_device_info.js`.

2023-12-27 18:06 UTC, cassiohg commented on controllers/device_list.js
> +              content.firewall_enabled !== undefined &&
Adicionei checagem pro tipo booleano.

2023-12-27 18:06 UTC, cassiohg commented on public/javascripts/edit_device.js
> +        $(`#wan-${index}-firewallEnabled`).is(':checked');
Movi.

2023-12-27 18:06 UTC, cassiohg commented on models/device_version.js
> +    grantFirewallEnabled: cpePermissions.features.firewall,
Adicionei.

2023-12-27 18:06 UTC, cassiohg commented
> Eu não parei para entender mas ao rodar o sync, a informação do firewall não está sendo atualizada na base

Atualizando na base ele está, se não nem aparecia no front end. Percebi aqui que o flashman não estava fixando o valor após um sync. Corrigi isso. Era o `changes` não sendo marcado dentro do `syncDeviceData`.

> E a informação de `firewall_enabled`está sendo enviada para todas as CPEs, mesmo que o campo não esteja presente (Testei firmware, AX2S e EG8145V5 sem o campo de `firwall_enabled`)

Tem certeza que o firmeware está recebendo task do genie? Se o campo não está presente no front end, o parametro não é enviado pra atualziar o `device`. Se eu mudar um valor na sessao de wifi, a task enviada não contem nada de firewall.

> Sobre a tradução, como eu ainda não vi no front, não posso opinar tanto, mas acredito que fique melhor caso seja: `"Habilitar Firewall"`

Verbos se usam em ações, ações são feitas em botões. O check mark é um indicação de estado, ele não executa nenhuma ação, portanto é melhor ficar como adjetivo.

2023-12-27 18:20 UTC, cassiohg commented on controllers/acs_device_info.js
> +  }
O valor vem no `data` apenas quando é um sync iniciado pelo flashman ou pela cpe (através  de inform), porque é chamado `fetchSyncResult()`. Quando a CPE faz a primeira conexão com o genie, após já ter sido registrada, que seria o caso de restart ou de troca de endereço de ACS, é chamado `syncDeviceData()` e o `data` passado é o data que vem direto da provision.

2023-12-27 18:20 UTC, cassiohg commented on controllers/acs_device_info.js
> +    wan: {}, lan: {}, wifi2: {}, wifi5: {}, common: {}, stun: {}, firewall: {},
E isso significa que ficou faltando também na feature de wifi power

2023-12-28 00:51 UTC, cassiohg commented on controllers/acs_device_info.js
> +    wan: {}, lan: {}, wifi2: {}, wifi5: {}, common: {}, stun: {}, firewall: {},
Fiz um pull request resolvendo isso para wifi power.

2023-12-28 14:36 UTC, cassiohg commented on controllers/acs_device_info.js
> +    wan: {}, lan: {}, wifi2: {}, wifi5: {}, common: {}, stun: {}, firewall: {},
Removi o firewall do `changes`.

2024-01-04 00:08 UTC, GThurler approved these changes

2024-01-04 00:08 UTC, merged